### ISSUE TITLE
1.2版 代公众号调用接口WeChatComponent的问题

### ISSUE THREAD

**Issue by openpython** [wechatpy/wechatpy#102]
目前调用接口依然有问题，帮我看下是否调用逻辑有问题。
1、公众号 client 对象的获取的第二种场景，将公众号 appid传入`component.get_client_by_appid()`。适用于已经授权的场景。
 wechat_client=wechat_component.get_client_by_appid(wechat_info.authorizer_appid)引发异常：

```
    wechat_client=wechat_component.get_client_by_appid(wechat_info.authorizer_appid)
  File "/usr/local/lib/python2.7/dist-packages/wechatpy/component.py", line 399, in get_client_by_appid
    refresh_token
  File "/usr/local/lib/python2.7/dist-packages/wechatpy/component.py", line 317, in refresh_authorizer_token
    'authorizer_refresh_token': authorizer_refresh_token
  File "/usr/local/lib/python2.7/dist-packages/wechatpy/component.py", line 273, in post
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/wechatpy/component.py", line 147, in _request
    return self._handle_result(res, method, url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wechatpy/component.py", line 183, in _handle_result
    response=res
wechatpy.exceptions.WeChatClientException: Error code: 61023, message: refresh_token is invalid hint: [TbmG_a0893vr23]
```

这异常因为component.py中的方法get_client_by_appid(self, authorizer_appid)中的
refresh_token = self.session.get(refresh_token_key) #这里假设了refresh_token存在于session中。
但是我在component.py中没找到自动将refresh_token存储到session的代码。所以我写了如下代码测试（wechat_info是一个存储了公众号授权后各种资料的类）：

```
result=wechat_component.refresh_authorizer_token(wechat_info.authorizer_appid, wechat_info.authorizer_refresh_token)
refresh_token_key = '{0}_refresh_token'.format(wechat_info.authorizer_appid)
#redis_store.set(refresh_token_key, result.get('authorizer_access_token'))
redis_store.set(refresh_token_key, result)
wechat_client=wechat_component.get_client_by_appid(wechat_info.authorizer_appid)
```

将字典放入redis还是将值放入，再次调用get_client_by_appid，依然提示：wechatpy.exceptions.WeChatClientException: Error code: 61023, message: refresh_token is invalid hint: 
调用了redis的控制台查看key，存在"wx9ee5*****_refresh_token"的key，值也是正确的，这是何故？

**Comment by hunter007** [comment]
你的代码有刷新refresh_token的机制吗？

**Comment by openpython** [comment]
result=wechat_component.refresh_authorizer_token(wechat_info.authorizer_appid, wechat_info.authorizer_refresh_token)
这个不是吗？

**Comment by hunter007** [comment]
文档中有说明：

> 授权码和刷新码有效期为7200秒，需要在失效之前更新授权码。由于各个项目的差异性和复杂性，本项目并未实现更新逻辑，需要调用者根据项目来自己实现。在失效之前，只要调用 `client.fetch_access_token()`即可刷新缓存，所以这个逻辑很简单。

在你的项目中要有定时刷新机制，保证授权码和刷新码是有效的。

**Comment by hunter007** [comment]
@openpython , 这个问题搞定了吗？

**Comment by openpython** [comment]
抱歉，这段时间一直忙碌没来，上次提问后我做了以下修改，get_client_by_appid方法增加一个authorizer_refresh_token参数，默认为None，方法内判断这个参数，如果传递了，就直接使用，否则使用session里的。

``` python
def get_client_by_appid(self, authorizer_appid,authorizer_refresh_token=None):
    if authorizer_refresh_token:
        refresh_token =authorizer_refresh_token
    else:
        refresh_token = self.session.get(refresh_token_key)
```

目前使用比较稳定，解决了我的问题。

**Comment by hunter007** [comment]
ok。如果解决了，就把 issue关闭吧。
