### ISSUE TITLE
WeChatDataCube 数据分析 API的微信接口调用地址错误

### ISSUE THREAD

**Issue by openpython** [wechatpy/wechatpy#105]
一概返回404，debug后发现post出的地址是https://api.weixin.qq.com/cgi-bin/datacube/getuserread
微信文档上是https://api.weixin.qq.com/datacube/getuserread

http://mp.weixin.qq.com/wiki/2/c87fed3bb002a0ed8184cb996b2acbbe.html

**Comment by messense** [comment]
v1.2.1 released with fixes.
