### ISSUE TITLE
Drop support for Python 2.6

### ISSUE THREAD

**Issue by hunter007** [wechatpy/wechatpy#107]
建议去除对 python2.6的支持，促进大家向 python3转换。

**Comment by wangaicc** [comment]
#这样不好吧！

**Comment by messense** [comment]
@wangaicc Why?

**Comment by wangaicc** [comment]
@messense 毕竟用 2 的“老人”还是有很多的。。。。

**Comment by messense** [comment]
@wangaicc 用 2.6 的很少了吧，现在新一点儿的系统自带的大多是 2.7 的。

**Comment by hunter007** [comment]
我们也不用一下子就放弃 python2.6，可以在1.4或者1.5中放弃。@messense，你能在 github 中建个 milestone 吗？把放弃 python2.6作为1.4版本的一个特性。
