### ISSUE TITLE
异步 OAuth 接口

### ISSUE THREAD

**Issue by messense** [wechatpy/wechatpy#112]

**Comment by hunter007** [comment]
强烈建议把异步的特性单独成立一个项目，比如 wechatpy-async。对于我们的项目来说，完全用不到异步，但不得不安装一些无用的模块。虽然不用的时候，一般不会产生影响。但我们还是担心会出现意想不到的事情。

**类似的情况也有很多，但都是分开处理的。** 比如 一直有人想让requests支持异步，但requests没有这么做，于是出现了grequests。

**分开处理，保持项目的简单性。** 这在django-rest-framework中体现的最为突出。之前django-rest-framework是支持 xml、csv 等格式的，现在只支持 json，因为这是大部分情况。而把 xml、csv 单独出来，需要的人可以先安装django-rest-framework，再安装django-rest-framework-xml就可以用了。

现在返回数据的方式用着很不方便，以及一些东西显得多余，我想把这个库改造得更面向对象一些，屏蔽掉网络层。这样对调用者更方便。如果这时候还要考虑异步，情况会变得很复杂。

如果实现了更加面向对象的方式，需要异步支持时，也可以用更高层的设计模式方便的实现。
