### ISSUE TITLE
事件推送群发结果MsgID大小写bug

### ISSUE THREAD

**Issue by openpython** [wechatpy/wechatpy#116]
http://mp.weixin.qq.com/wiki/15/5380a4e6f02f2ffdc7981a8ed7a40753.html
群发返回事件 MsgID 的ID都是大写，实际监测返回值也是MsgID。
框架里的 BaseMessage 接收参数是 id = IntegerField('MsgId', 0)，所以取不到正确的值。

**Comment by messense** [comment]
Released in v1.2.3
