### ISSUE TITLE
发送模板消息

### ISSUE THREAD

**Issue by polyrabbit** [wechatpy/wechatpy#118]
Hi, 我看到现有的代码支持`设置所属行业`，`获得模板ID`，但是不支持`发送模板消息`，不知道为什么，还是我没有找对地方？

**Comment by messense** [comment]
发送消息相关的 API 都在 message endpoint 中。

https://github.com/jxtech/wechatpy/blob/master/wechatpy/client/api/message.py#L424

**Comment by messense** [comment]
BTW，早点睡~

**Comment by polyrabbit** [comment]
OK, 我明白了，wechatpy把发送消息相关的api都放到`WeChatMessage`中了。

BTW，我觉得wechatpy应该要有个`tutorial`，很多开源框架刚开始都会告诉用户怎样快速上手，然后再详细介绍每个api的用法。这样的文档才不至于让用户一上来就有点摸不着头脑 :smile: 

不知道我什么时候有没有空帮忙写一个。。

**Comment by messense** [comment]
文档基本上都是我一个人弄的，心有余而力不足啊。能帮忙当然好啊
