### ISSUE TITLE
支持微信个性化菜单接口

### ISSUE THREAD

**Issue by hunter007** [wechatpy/wechatpy#119]

**Comment by messense** [comment]
https://github.com/jxtech/wechatpy/blob/master/wechatpy/client/api/menu.py#L101

**Comment by hunter007** [comment]
这个特性放在1.3吧。

**Comment by messense** [comment]
cherry-picked and released in v1.2.3

https://github.com/jxtech/wechatpy/blob/v1.2.3/wechatpy/client/api/menu.py#L101
