### ISSUE TITLE
上传永久素材 API的微信接口调用地址错误

### ISSUE THREAD

**Issue by openpython** [wechatpy/wechatpy#121]
wechatpy.client.api.material 中 add方法
return self._post(
            url='http://file.api.weixin.qq.com/cgi-bin/material/add_material','''
微信文档：http://mp.weixin.qq.com/wiki/14/7e6c03263063f4813141c3e17dd4350a.html
## 请求地址：https://api.weixin.qq.com/cgi-bin/material/add_material

奇怪的是我替换后，错误信息变成了：Error code: 40066, message: invalid url hint 这是什么情况？

**Comment by messense** [comment]
40066 这个错误码似乎在文档里面找不到？

**Comment by openpython** [comment]
https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419318634&token=&lang=zh_CN
在这里，微信API文档组织有点渣。

**Comment by messense** [comment]
Not myself these days. Sorry.

你是直接用的微信公众号还是第三方平台代调用的那种方式？

**Comment by openpython** [comment]
是第三方平台代调用的！

**Comment by messense** [comment]
@openpython 建议试一下直接调用有没有问题

**Comment by openpython** [comment]
微信第三方API文档没有直观的说明,...究竟哪些是第三方调用不了的呢？

**Comment by openpython** [comment]
我使用的wechatpy是1.2，按照新版fix的代码修改后，刚刚详细测试了，公众号和第三方API调用都没有问题啦！

**Comment by messense** [comment]
OK, 稍后发布一个新版本。

**Comment by messense** [comment]
https://pypi.python.org/pypi/wechatpy/1.2.4
