### ISSUE TITLE
上传图片偶尔会引发Connection aborted错误

### ISSUE THREAD

**Issue by openpython** [wechatpy/wechatpy#123]
目前未发现规律，昨天监测到是 wechat_client.media.upload_mass_image(open(full_path))，上传3张图，第二张图片引发的，
`r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 412, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))`
这张图片以前发送成功过到微信服务器，应该与违禁图片无关。这个错误wechatpy无法捕捉呢，这样以后写异常处理要写两个？

**Comment by messense** [comment]
可以考虑捕捉一下，方便使用。

**Comment by openpython** [comment]
群发，总是出现 ('Connection aborted.', BadStatusLine("''",)) 错误，这错误大概反映了什么问题？奇怪的同样的群发文章，预览群发就正常，正常群发就出现 ('Connection aborted.', BadStatusLine("''",)) 错误

**Comment by messense** [comment]
https://github.com/kennethreitz/requests/issues/2364

**Comment by openpython** [comment]
我认为是微信公众平台的问题，是他们的图片检测软件的误报，正常图片被判定为色情图片。
