### ISSUE TITLE
文档过于简单了，建议能增加相应的实例

### ISSUE THREAD

**Issue by zhangfisher** [wechatpy/wechatpy#127]
不太明白WeChatComponent,WeChatClient什么区别，文档有很多说明搞不太懂，只能暂时放弃。
相比之下，wechat-python-sdk文档和使用方法更清晰些。

**Comment by messense** [comment]
文档没有太多时间去做。

WeChatComponent 是第三方代调用公众号接口（你在开发微信公众号第三方平台才会用这个），WeChatClient 是普通的公众号接口（大部分情况下用这个）。

建议简单读一下代码，不是很复杂，理解了基本的代码组织结构就很容易了。

**Comment by messense** [comment]
另外，测试用例里面有些可是当做示例来看。

https://github.com/jxtech/wechatpy/tree/master/tests

**Comment by zhangfisher** [comment]
通过比较wechat-python-sdk与wechatpy，得益于python的优雅，可以说均不错的库，wechat-python-sdk功能还不齐全，wechatpy功能已经比较全了，但是文档差很多，可以说一个新手使用wechat-python-sdk会很容易就上手，而wechatpy上手比较难，API设计也没有wechat-python-sdk优雅，可能是因为文档差太多理解比较困难的问题，这样可以预计wechat-python-sdk将超越wechatpy.

**Comment by messense** [comment]
wechat-python-sdk 与 wechatpy API 的设计最大的区别在于，wechat-python-sdk 将所有 API 都放在 `WechatBasic` 类里面，而 wechatpy 将 API 分组，抽象出不同的 API Endpoint 组，通过 metaclass 魔术方法统一放在 `WeChatClient` 上作为属性，如此可以写出这样的代码：

``` python
from wechatpy import WeChatClient

client = WeChatClient('appid', 'secret')

user = client.user.get('openid')
client.group.move_user('openid', 1234)
```

理解了这个之后结合文档和微信官方文档就很容易开发了，并且有兴趣了解如何实现的话看一下代码学习一下 metaclass 也很有意思。

而对应的 wechat-python-sdk 代码可能是：

``` python
from wechat_sdk import WechatConf, WechatBasic
conf = WechatConf(
    token='your_token', 
    appid='your_appid', 
    appsecret='your_appsecret', 
    encrypt_mode='safe',  # 可选项：normal/compatible/safe，分别对应于 明文/兼容/安全 模式
    encoding_aes_key='your_encoding_aes_key'  # 如果传入此值则必须保证同时传入 token, appid
)
wechat = WechatBasic(conf=conf)

user = wechat.get_user_info('openid')
wechat. update_group('openid', 1234)
```

哪个更优雅那得看使用者的审美。
但是很明显把所有 API 都放到一个 class 里面，对于库作者来说以后会越来越难维护（微信的接口已经很多了，未来可能会更多）。

**Comment by messense** [comment]
@cloverstd 
@hunter007 

文档的完善上面，各位有没有兴趣和时间？做一个快速入手的文档可能就好了，包含接入回调（可能需要 Flask/Django 等的示例）和使用主动调用 API。

**Comment by hunter007** [comment]
各种框架的示例项目？​

# 

赵文涛  steven zhao

Tel：（+86） 150 051 72386

# Email：wentao79@gmail.com

在 2016年3月5日 上午10:16，messense notifications@github.com写道：
