### ISSUE TITLE
增加 quick start 文档

### ISSUE THREAD

**Issue by messense** [wechatpy/wechatpy#129]
http://wechatpy.readthedocs.org/zh_CN/master/quickstart.html

Working in progress.

**Comment by messense** [comment]
@cloverstd @hunter007 @zhangfisher @weaming @imcncer

Would be great to get some suggestions.

**Comment by cloverstd** [comment]
一直在用 Markdown，还需要熟悉下 reStructuredText

**Comment by weaming** [comment]
Very well. Keep do it.

**Comment by messense** [comment]
Ref #124 #125 #127

**Comment by hunter007** [comment]
我可以写一个django的quickstart项目。

**Comment by messense** [comment]
@hunter007 That would be great.
