### ISSUE TITLE
处理微信头像“暂时无法查看”问题

### ISSUE THREAD

**Issue by zxygentoo** [wechatpy/wechatpy#146]
这是微信的一个已知 bug，有时候获取的用户头像是一个“暂时无法查看”的图，比如这样：

http://wx.qlogo.cn/mmopen/6VeN1aCWEIVAeMFsXww8EIczz5AHVCqh0DLAR35HddA4tt83wNibL4ZlH5f36uRAxngqhibzud1XaZxzGnOtt9ibOmbQAleflzk/0

不知道你们是否愿意把这个放进 wechatpy 里处理，如果愿意的话我可以研究一下提供一个 patch。

不过放进 wechatpy 处理有一个明显的坏处，就是这个错误头像的链接每次都不同，所以目前想到的方法就是把图片数据下载回来比对一下 hash 值，如果是错误图片就再拿一次用户信息。那么就会让所有授权都变慢，不过这个图片很小（5k），相当于只是多一次基本的网络开销，可能不是太大问题。

**Comment by messense** [comment]
发一个 PR 看看代码？

**Comment by akinLiu** [comment]
这个问题解决了吗

**Comment by supgeek-rod** [comment]
对头像文件进行 hash 以辨别是否为`暂时无法查看的头像`是个好思路，正好遇到这个坑

**Comment by holys** [comment]
其实http header  有个 error code 表明这是个无法查看的头像， 即缓存已失效，通常是由于微信用户修改了头像，但是微信并没有去更新缓存。

![image](https://user-images.githubusercontent.com/1198913/57901493-01ad2f80-7898-11e9-9aeb-43fac642120d.png)


建议的做法是把头像存起来，就不依赖微信的缓存了。
