### ISSUE TITLE
出现签名错误，不知道如何解决

### ISSUE THREAD

**Issue by yubang** [wechatpy/wechatpy#149]
控制台输出这个
wechatpy.exceptions.WeChatPayException: Error code: SUCCESS, message: 签名错误

**Comment by zqhong** [comment]
看到一个类似的问题，下面是简单的摘要

异常信息：签名错误
- 原因：mch_id 改对了，但是没有将 API key 修改为和 mch_id 一致的 API key
- 解决方案：登录移动应用微信支付对应的商户平台，复制 mch_id 和 API key 到 微信微信的 demo 应用程序的 Constant.java 中。

重新运行程序，即可正常使用Android端微信支付。

重点：`mch_id` 和 `API key`

参考的是这个：
[微信支付 - 签名错误](http://www.oschina.net/question/2340686_234452)

**Comment by messense** [comment]
@yubang 需要提供你的调用部分的代码，API Key 等机密信息用 \* 等字符代替。

**Comment by messense** [comment]
See also #148

**Comment by yubang** [comment]
@messense 

``` python
# coding:UTF-8

from wechatpy import WeChatPay
from config import base_config
import os


def send_money(open_id, money):
    """

    :param open_id:
    :param money:
    :return:
    """
    SSLKEY_PATH = os.path.dirname(os.path.dirname(os.path.realpath(__file__))) + '/apiclient_key.pem'
    SSLCERT_PATH = os.path.dirname(os.path.dirname(os.path.realpath(__file__))) + '/apiclient_cert.pem'

    dao = WeChatPay(base_config.app_id, base_config.KEY, base_config.mch_id, mch_cert=SSLCERT_PATH, mch_key=SSLKEY_PATH)
    r = dao.redpack.send(open_id, money, "chuanbay", "chuanbay", "test", "test2")
    print r

if __name__ == '__main__':
    send_money('[这是open_id]', 100)
```

**Comment by yubang** [comment]
@zqhong 一会重置key看看

**Comment by messense** [comment]
可以在这里 https://github.com/jxtech/wechatpy/blob/master/wechatpy/pay/__init__.py#L106 断点看下 `data` 和 `signature`，然后用 https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=20_1 使用自定义参数生成签名对比。

**Comment by yubang** [comment]
@messense 打了断点，用工具校验了，校验通过，但是微信接口还是返回签名错误

**Comment by messense** [comment]
那可能是接口更新了需要其他的参数？等我有空看下文档。

**Comment by yubang** [comment]
@messense 问题解决了，你的代码ok的，我重置了商户key就好了，非常感谢您

**Comment by yubang** [comment]
@zqhong 商户key真心是一个坑，错误提示特别误导人
