### ISSUE TITLE
如何解析微信支付后异步通知的结果？

### ISSUE THREAD

**Issue by openpython** [wechatpy/wechatpy#151]
文档：https://pay.weixin.qq.com/wiki/doc/api/native.php?chapter=9_7
## wechatpy里似乎没有内置的解析方法？

上篇微信支付问题提问后就被拉走干苦力活去了，今刚忙完。。。
支付是可以了，但是请求微信支付延时30s问题一直存在，换了一台服务器，貌似好了。

**Comment by messense** [comment]
直接用 xmltodict 解析就好了。

**Comment by messense** [comment]
有兴趣可以 PR

**Comment by openpython** [comment]
秒回呀:+1:
谢谢，我抽空测试下。

**Comment by messense** [comment]
master 分支中已经增加了此功能。
