### ISSUE TITLE
看文档 不支持公众号的oauth?

### ISSUE THREAD

**Issue by JasLin** [wechatpy/wechatpy#155]
rt,通过网页授权获取openid,nickname这些功能,目前不支持?

**Comment by messense** [comment]
文档没写....

https://github.com/jxtech/wechatpy/blob/master/wechatpy/oauth/__init__.py

**Comment by JasLin** [comment]
好;)

**Comment by messense** [comment]
http://wechatpy.readthedocs.io/zh_CN/master/oauth.html

**Comment by JasLin** [comment]
公众号那里写着TODO,以为只有企业号,可以文档那里加一点说明

**Comment by messense** [comment]
@JasLin 已经更新过了 API 文档，只是没空去写用法文档。
