### ISSUE TITLE
jssdk 可以考虑增加一个直接返回整个wx.config的接口

### ISSUE THREAD

**Issue by JasLin** [wechatpy/wechatpy#157]
rt. 其中jsapilist可以作为参数输入

**Comment by hbrls** [comment]
我是在自己的项目里面封装这个功能的，每个项目的实现都不一样，统一提供很难弄

**Comment by JasLin** [comment]
感觉这个较少有个性化的需求,这个wx.config里面,唯一可变的是apilis和签名里面的url(这两个可以作为这个接口的参数),其他的都是配置参数或者是随机以及从微信拿回来的签名:

``` Javascript
wx.config({
    debug: true, // 开启调试模式,调用的所有api的返回值会在客户端alert出来，若要查看传入的参数，可以在pc端打开，参数信息会通过log打出，仅在pc端时才会打印。
    appId: '', // 必填，公众号的唯一标识
    timestamp: , // 必填，生成签名的时间戳
    nonceStr: '', // 必填，生成签名的随机串
    signature: '',// 必填，签名，见附录1
    jsApiList: [] // 必填，需要使用的JS接口列表，所有JS接口列表见附录2
});
```

这样的话,直接提供一个这样的接口返回config就好,如下面这个sdk的封装:
https://github.com/overtrue/wechat/blob/master/src/Js/Js.php#L68

**Comment by messense** [comment]
自行封装并不麻烦，这个功能不考虑添加到 SDK 中。
