### ISSUE TITLE
接收消息然后不想自动回复，需要回复一个空字符串，但是好像没有这个函数

### ISSUE THREAD

**Issue by Since-future** [wechatpy/wechatpy#161]
假如服务器无法保证在五秒内处理并回复，必须直接回复空串（是指回复一个空字符串，而不是一个XML结构体中content字段的内容为空，请切勿误解），微信服务器不会对此作任何处理，并且不会发起重试。。这种情况下，可以使用客服消息接口进行异步回复。    这是微信的官方文档，请问这种情况怎么处理

**Comment by messense** [comment]
你就直接返回个空字符串啊。。。

**Comment by messense** [comment]
Like Flask:

``` python
from flask import Flask


app = Flask(__name__)


@app.route('/', methods=['GET', 'POST'])
def callback():
    # when you want to return empty string
    return ''
```

为什么非要一个函数返回空字符串。。。

**Comment by liu296779442** [comment]
我调用create_reply或者TextReply自动回复，如果填“”双引的空就会出现该公众号暂时无法提供服务

**Comment by Since-future** [comment]
@messense  我调用create_reply或者TextReply自动回复，如果填“”双引的空就会出现该公众号暂时无法提供服务

**Comment by Since-future** [comment]
@messense   reply = create_reply("", msg)  我是这样写的，但是就会提示该公众号暂时无法提供服务

**Comment by Since-future** [comment]
非常感谢 #162
