### ISSUE TITLE
bug in wechatpy.enterprise.client.api.material

### ISSUE THREAD

**Issue by xrivan** [wechatpy/wechatpy#172]
When using wechatpy.enterprise.client.api.material to upload material, the "add" method always report "ValueError: Data must not be a string.".

Check the source code:
def add(self, agent_id, media_type, media_file):
        data = {
            'agentid': agent_id,
            'type': media_type,
        }
        return self._post(
            url='material/add_material',
//the **data** should be changed to **params**
            **data**=data,  
            files={
                'media': media_file
            }
        )

**Comment by messense** [comment]
Thanks for reporting. Please use master branch for now before a new release issued.
