### ISSUE TITLE
不支持Python3.5 async和await异步写法

### ISSUE THREAD

**Issue by wojunnihou** [wechatpy/wechatpy#175]
源码中没有看到异步client的实现呢？？

**Comment by messense** [comment]
Moved to https://github.com/wechatpy/wechatpy.async.tornado and https://github.com/wechatpy/wechatpy.async.asyncio

但是 namespaced package 还有些问题并不能正常使用（开发中 OK 但是打包之后安装就挂了）。

**Comment by messense** [comment]
感觉也没有多少人需要异步所以一直没有很好推动这块的事情。

**Comment by aiportal** [comment]
建议支持异步，可以跟[Sanic](https://github.com/channelcat/sanic)结合起来使用。

**Comment by bright-pan** [comment]
@bfbd888 我已经处理了异步化的一部分工作，网页用户信息授权，和jsapi这块，已经可以使用了

但是测试用例没有编写，能否一起来维护一个异步版本aiowechatpy，已经在内部使用了，谢谢

**Comment by aiportal** [comment]
好的，我可以在Sanic项目中使用aiowechatpy，提交使用情况。

**Comment by messense** [comment]
ping #208

**Comment by liriansu-opus** [comment]
讨论性质的Issue先Close了，有什么想法可以继续留言讨论，欢迎各位贡献代码。
