### ISSUE TITLE
subscribe事件的小众情况

### ISSUE THREAD

**Issue by VxCoder** [wechatpy/wechatpy#178]
**问题描述:** 在一个公众号内完成微信的支付后,取消订阅,再重新订阅,微信返回的事件信息为:

```
<xml>
<ToUserName><![CDATA[gh_5d11d6624a52]]></ToUserName>
<FromUserName><![CDATA[o0gf2wLPLvE9bcZwri_Z0FWx4b6g]]></FromUserName>
<CreateTime>1484033813</CreateTime>
<MsgType><![CDATA[event]]></MsgType>
<Event><![CDATA[subscribe]]></Event>
<EventKey><![CDATA[last_trade_no_4008072001201701105817415015]]></EventKey>
</xml>
```

event为subscribe, 但是EventKey是最后的交易号(WTF!!!).
而parse_message会把EventKey的内容作为scene_id来处理了.

**Comment by messense** [comment]
有相关文档吗？

**Comment by VxCoder** [comment]
微信文档上没找到相关说明,自己调试时发现的问题.但是微信发过了来的数据确实是这样的.

**Comment by messense** [comment]
似乎业务层也可以暂时 workaround 下：对 `scene_id` 开头是 `last_trade_no_` 的消息特殊处理下。

**Comment by messense** [comment]
Google 搜索 `last_trade_no` 也没有什么有意义的结果。

**Comment by VxCoder** [comment]
不知道是不是微信的bug或是调试功能

**Comment by messense** [comment]
可以发邮件给 wepayTS@tencent.com 问一问。

**Comment by messense** [comment]
@VxCoder Any update on this issue?

**Comment by kh0x00** [comment]
我就直接在parse_message中加入了
```python
            elif event_key.startswith('last_trade_no_'):
                message['Event'] = event_type
```

不然event_type就变成subscribe_scan了

**Comment by messense** [comment]
@kenhancoder 发个 PR?

**Comment by messense** [comment]
给 `SubscribeEvent` 增加了 `key` 属性，现在也能正确 parse 了，不会再变成 subscribe_scan 了。
