### ISSUE TITLE
统一下单接口  Error code: 40066, message: invalid url

### ISSUE THREAD

**Issue by lsaint** [wechatpy/wechatpy#179]
微信支付的统一下单接口应该是: https://api.mch.weixin.qq.com/pay/unifiedorder
代码目前使用的这个:  https://api.weixin.qq.com/cgi-bin/pay/unifiedorder

报错：wechatpy.exceptions.WeChatClientException: Error code: 40066, message: invalid url hint: [e.UAiA0238rsz8!]

微信支付统一下单文档：
https://pay.weixin.qq.com/wiki/doc/api/app/app.php?chapter=9_1

**Comment by messense** [comment]
调用错了吧？

**Comment by messense** [comment]
请提供示例代码。

**Comment by lsaint** [comment]
weclient = WeChatClient(APPID_WECHAT_PAY,  APPSECRET_WECHAT_PAY)
order = WeChatOrder(weclient)
r = order.create('APP',
                    'X费',
                    1,
                    URL_WEHCHAT_PAY_NOTIFY,
                    out_trade_no = '123123123123')

**Comment by messense** [comment]
错误的调用，请查看文档：http://docs.wechatpy.org/zh_CN/master/pay.html#module-wechatpy.pay

```python
from wechatpy.pay import WeChatPay

pay = WeChatPay(appid, api_key, mch_id, mch_cert, mch_key)
pay.order.create(.....)
```
