### ISSUE TITLE
文档里似乎没有提到模板消息推送的接口

### ISSUE THREAD

**Issue by Fisherworks** [wechatpy/wechatpy#180]
请问该lib是否支持模板消息推送？

**Comment by Fisherworks** [comment]
已找到文档，隐藏的比较深，请忽略

**Comment by t0ny-peng** [comment]
找到后请拜托告知一下在哪里，我也没找到。

**Comment by Fisherworks** [comment]
send_template(user_id, template_id, url, top_color, data)
微信主动调用接口 - 主动消息接口

LZ的这个库是在下调研过的python的微信库里边已支持功能最多的，且至今还在维护的
唯一问题确实可能是tutorial少了一点，需要自己看一点源码来用

公众平台OAuth那段，发现企业号OAuth的example没啥参考价值
而基类的WechatClient本身不包含oauth方法，所以还是简单看下（没有深入）源码然后踩着小坑慢慢出来的，倒也不失为一种学习乐趣
