### ISSUE TITLE
自己实现 access_token 的获取和刷新

### ISSUE THREAD

**Issue by mutedstack** [wechatpy/wechatpy#185]
我自己实现了 access_token 的更新，如何操作实现用我自己的？重载 property `access_token` in WeChatClient 就行了吗？

PS:
我之前用的是 `wechat-python-sdk`，它允许你传入三个 access_token 相关函数，我觉得这样比较灵活。
```
'access_token_getfunc': access token 获取函数 (用于单机及分布式环境下, 具体格式参见文档)
'access_token_setfunc': access token 写入函数 (用于单机及分布式环境下, 具体格式参见文档)
'access_token_refreshfunc': access token 刷新函数 (用于单机及分布式环境下, 具体格式参见文档)
```

**Comment by messense** [comment]
希望自行管理 `access_token` 的话：

```python
from wechatpy.client import WeChatClient

def get_wechat_client():
    access_token = your_get_access_token_func()
    return WeChatClient('app_id', 'secret', access_token=access_token, auto_retry=False)
```

刷新 `access_token` 应当配置定时任务。

或者参考：http://docs.wechatpy.org/zh_CN/master/enterprise/quickstart.html#accesstoken

**Comment by mutedstack** [comment]
你这样的话，如果 access_token 过期了，那么就不行了吧。你再fetch_access_token会使我储存的 access_token 过期。
我试试重载 
```python
@property
access_token
```
另外，secret 是否只与 access_token 有关? 我打算传入错误的secret，防止 wechat_client 使我储存的 access_token 过期。 (这里应该使用 auto_retry=False，而不是传入错误的 secret)

这样随意的重载代码会不会有危险？比如之后你升级了改变了 access_token 的获取方式？所以我现在要固定 wechatpy==1.3.1，之后升级 wechatpy 还要检查重载的部分有没有变化。

**Comment by messense** [comment]
`auto_retry = False` 并不会自动刷新 `access_token`

**Comment by fbigun** [comment]
Mark ,是否是自动管理，单个app时是否可以不自行管理 access_token 。

**Comment by liriansu-opus** [comment]
要自行管理 access_token 的话可以设定 `auto_retry=False`
然后重载 `access_token`和`fetch_access_token`

之后考虑在 FAQ 文档中给出更详细的说明
