### ISSUE TITLE
requests.request timeout 类型错误

### ISSUE THREAD

**Issue by mutedstack** [wechatpy/wechatpy#186]
`WeChatClient` 中的 timeout=None，但是我实际请求后发现 self.timeout=False，不知道原因。但是！，这两个都是错误的类型

    :param timeout: (optional) How long to wait for the server to send data
        before giving up, as a float, or a :ref:`(connect timeout, read
        timeout) <timeouts>` tuple.
    :type timeout: float or tuple

**Comment by messense** [comment]
https://github.com/jxtech/wechatpy/search?utf8=%E2%9C%93&q=timeout

**Comment by messense** [comment]
https://github.com/kennethreitz/requests/blob/master/requests/sessions.py#L426

timeout 默认就是 None，表示没有 timeout.

**Comment by mutedstack** [comment]
我这里 self.timeout = False 的原因是：
```python
class MyWeChatClient(OriginalWechatClient):
    """重载 access_token property，使用自定义方式获取 access_token"""

    def __init__(self, appid, secret, access_token=None,
                 session=None, timeout=None, auto_retry=False):
        pdb.set_trace()
        super(MyWeChatClient, self).__init__(
            appid, secret, access_token, session, timeout, auto_retry
        )
        self.appid = appid
        self.secret = secret

    @property
    def access_token(self):
        return wechat_access_token()

```
之前这里的 super 是复制 
```python
        super(WeChatClient, self).__init__(
            appid, access_token, session, timeout, auto_retry
        )
```
相比上面少了一个 secret, 导致参数位置错误。
