### ISSUE TITLE
[文档] [相关]微信开发问题汇总、总结

### ISSUE THREAD

**Issue by mutedstack** [wechatpy/wechatpy#187]
由于微信的文档以及错误码并不完整，有时候还不一致。并且很多时候还搜索不到相关的问题，应该是搜索方法不对以及有些问题遇到的人并不是很多。
我想，我们能不能发出帖子，像 stackoverflow 那样，将微信开发中遇到的问题汇总起来。并定期进行总结。并且，由于这个和语言无关，所以可以联合其他语言 sdk 的作者一起加入。还可以邀请微信官方一起进行，毕竟锅还是他们的。

**Comment by messense** [comment]
GitHub issues 应该足够了。

**Comment by messense** [comment]
当然我们应当完善文档，Ref #129 #127 #124

**Comment by mutedstack** [comment]
也就是说，这里你不仅包含 sdk 的问题，还要包括微信开发中遇到的问题（可能与sdk关系不大的问题）？可能会有点多哦，并且覆盖的范围也更大，我觉得你不一定能忙的过来。

**Comment by hbrls** [comment]
我本来准备做一个 [给开发者看的微信开发文档](https://github.com/wechat-developer/wechat-developer.github.io/blob/master/doc-for-humans.md)。

微信的文档太敷衍了，离指导开发有一定距离。

**Comment by messense** [comment]
更多的问题是很多开发者根本不先看看微信的文档，随便找个 SDK 就上手开发……

**Comment by liriansu-opus** [comment]
我们可以拆分更细的去一点点完善文档、测试什么的。
感觉这个 Issue 比较宽泛，先 Close 了。
有什么想法欢迎留言讨论。
