### ISSUE TITLE
本项目的建设

### ISSUE THREAD

**Issue by mutedstack** [wechatpy/wechatpy#188]
我看到这个帖子，觉得很好。[如何在 Github 上做一个规范的开源项目？](https://www.zhihu.com/question/22195970/answer/135501803)
我认为本项目做的还不够的地方：
* 宣传不够。应该让更多人知道并参与进我们这个项目。比如让其他不再维护的 wechat sdk 项目的人员参与进来
* 规范不够。没有很好的说明代码结构，文件名、变量名等命名。后续贡献者提交没有一个很好的标准。

**Comment by messense** [comment]
规范：https://github.com/jxtech/wechatpy/blob/master/CONTRIBUTING.md

**Comment by messense** [comment]
关于宣传，需要大家一起努力。

**Comment by daimon99** [comment]
确实感觉微信方面开发，这个库是最好的。

**Comment by m17y** [comment]
庫還好，文檔就惡心了

**Comment by wushuang5112** [comment]
对呀，事件推送过来，我这边已经接收了，但是怎么去处理却不知道啊！！！

**Comment by bigzhu** [comment]
文档我完全看蒙了, 看来有这感觉的不光我一个.

案例的代码也跑不起来

**Comment by M-Kepler** [comment]
文档确实不如隔壁wechat-python-sdk,,,,,,看蒙了

**Comment by wweiradio** [comment]
我一直在用这个库，觉得不错。
