### ISSUE TITLE
如果我想打印消息内容，有没有更简洁的方法？

### ISSUE THREAD

**Issue by winturn** [wechatpy/wechatpy#198]
想实现功能
```print 'openid:%s content:%s' % (msg.source, msg.content)```

当msg.content包含中文的时候，我只能通过下面这种方式
```print 'openid:%s content:%s' % (msg.source.encode('utf8'), msg.content.encode('utf8'))```

有没有更好的方式？

**Comment by messense** [comment]
`print repr(msg)`
