### ISSUE TITLE
搞了几天了，一直check_signature失败，直接返回echostr倒是可以的。

### ISSUE THREAD

**Issue by yeakyang** [wechatpy/wechatpy#202]
```python
from wechatpy.utils import check_signature
from wechatpy.exceptions import InvalidSignatureException
from wechatpy import parse_message

 
WECHAT_TOKEN = 'steamtoken'
AppID = 'wx5ffb702f86fab88d'
AppSecret = '*************'

def wexin(request):
    # echo_str = request.GET.get('echostr', '')  
    # return HttpResponse(echo_str)

    if request.method == 'GET':  
        signature = request.GET.get('signature', '')  
        timestamp = request.GET.get('timestamp', '')  
        nonce = request.GET.get('nonce', '')  
        echo_str = request.GET.get('echostr', '')  
        #return HttpResponse(echo_str)
        try:  
            check_signature(WECHAT_TOKEN, signature, timestamp, nonce)  
        except InvalidSignatureException:  
            echo_str = 'error'        
        response = HttpResponse(echo_str, content_type="text/plain")
        return response
    else:  
        msg = parse_message(request.data)  
        if msg.type == 'text':  
            reply = create_reply(msg.content, msg)  
        else:  
            reply = create_reply('Sorry, can not handle this for now', msg)  
        return reply.render()  
```

**Comment by messense** [comment]
请确认 appid, secret, token 是否正确，另外不要把 secret 贴出来。

**Comment by yeakyang** [comment]
问题也就在这里，wechatpy怎么初始化？上面写了appid,但是好像没有用上啊。

**Comment by messense** [comment]
被动响应并没有什么初始化，Django 可以参考 https://github.com/polyrabbit/WeCron/blob/master/WeCron/wxhook/views.py

**Comment by messense** [comment]
另外，看下你回调开的是明文还是加密模式。

**Comment by yeakyang** [comment]
被动回复的搞定了，谢谢，再咨询另一个问题，网页授权的
from wechatpy.oauth import WeChatOAuth

wechat_instance = WeChatOAuth(
    app_id=AppID,
    secret=AppSecret,
    redirect_uri='http://steam.xiaowei.tech/oauth'
)
@csrf_exempt
def wechat_oauth(request):
    code = request.GET.get('code', '')
    if not code=='':
        response = wechat_instance.get_user_info()
        return HttpResponse(response)
    else:
        return HttpResponse(wechat_instance.authorize_url)

我不确定我的代码是否正确。。。
但是
一直返回redirect_uri非法，好像是url转码错了，只转义了前面的：号，后面的//应该要转成%2f的，但是并没有。看了源码
redirect_uri = quote(self.redirect_uri)
好像应该是要用quote_plus

**Comment by messense** [comment]
See #183
