### ISSUE TITLE
【疑问】关于token过期管理

### ISSUE THREAD

**Issue by ghost** [wechatpy/wechatpy#205]
我有个脚本，会不断轮询，当符合条件就发企业号微信给某个微信用户。其中client的token需要我定时去刷新，还是说我可以一直不用管它？代码如下：
client = WeChatClient(corp_id, secret_id)
while True:
     if XXXX:
          client.message.send_text(secret_id,receiver_id,content)

**Comment by messense** [comment]
如果你有其他程序也在用同一个 corp_id 的微信企业号的话，最好定时去刷新，让它自己管理问题也不大，只是可能会出现两边同时刷新 access token，导致 access token 获取接口被限制调用（不过不太可能，这个接口现在一天的调用限制应该被放宽很多了）

**Comment by ghost** [comment]
好的，明白了，只有一个程序在用，照你所说的话，我就不管他了，谢谢了~
