### ISSUE TITLE
关于aiowechatpy项目的开启

### ISSUE THREAD

**Issue by bright-pan** [wechatpy/wechatpy#208]
hi，

由于项目是基于asyncio，所以我打算使用aiohttp为基础来开启一个aiowechatpy的项目，并保持对wechatpy的版本同步，是否可以？

**Comment by bright-pan** [comment]
我先内部使用，如果可以再发布出来

**Comment by bright-pan** [comment]
移植难度不大，看了你们的代码

**Comment by messense** [comment]
可以的。其实之前也尝试过 aiohttp：

https://github.com/wechatpy/wechatpy.async.asyncio

但是因为用 namespace package 有 bug 暂时搁置了。 #122

**Comment by liriansu-opus** [comment]
感觉那个要做可以做成 Milestone

讨论性质的 Issue 就先关闭了，欢迎PR or Repo。
