### ISSUE TITLE
关于扫带参二维码返回“该公众号暂时无法提供服务，请稍后再试  ”的疑问

### ISSUE THREAD

**Issue by amiden** [wechatpy/wechatpy#219]
现象描述：
同代码在公众测试平台中扫码后能准确返回ok字段，在实际认证的服务号当中，同样返回ok字段，但是会额外显示“该公众号暂时无法提供服务，请稍后再试  ”的提示。
测试过直接返回空字段，同样有错误提示。

```python
@app.route('/wechat', methods=['GET', 'POST'])
def wechat():
    signature = request.args.get('signature', '')
    timestamp = request.args.get('timestamp', '')
    nonce = request.args.get('nonce', '')
    encrypt_type = request.args.get('encrypt_type', 'raw')
    msg_signature = request.args.get('msg_signature', '')
    try:
        check_signature(TOKEN, signature, timestamp, nonce)
    except InvalidSignatureException:
        abort(403)
    if request.method == 'GET':
        echo_str = request.args.get('echostr', '')
        return echo_str
    print request
    # POST request
    if encrypt_type == 'raw':
        # plaintext mode
        msg = parse_message(request.data)
        if msg.type == 'text':
            reply = create_reply(msg.content, msg)
        elif msg.type == 'event':
            if msg.event == 'subscribe_scan' or msg.event == 'scan':
                reply=create_reply('ok',msg)
            else:
		 reply = create_reply('ok2', msg)
        else:
            reply = create_reply('ok3', msg)
    else:
        reply = create_reply('ok4', msg)
    return reply.render()
if __name__ == '__main__':
    app.run('0.0.0.0', 80,debug=True, use_reloader=False)
```

**Comment by messense** [comment]
请求超时了？

**Comment by amiden** [comment]
应该没有，及时反馈的，不做任何处理，有没有可能是时间搓的问题。

**Comment by messense** [comment]
确认一下系统时间？

https://mp.weixin.qq.com/wiki

> 在微信用户和公众号产生交互的过程中，用户的某些操作会使得微信服务器通过事件推送的形式通知到开发者在开发者中心处设置的服务器地址，从而开发者可以获取到该信息。其中，某些事件推送在发生后，是允许开发者回复用户的，某些则不允许

> 用户在关注与取消关注公众号时，微信会把这个事件推送到开发者填写的URL。方便开发者给用户下发欢迎消息或者做帐号的解绑。
微信服务器在五秒内收不到响应会断掉连接，并且重新发起请求，总共重试三次。
关于重试的消息排重，推荐使用FromUserName + CreateTime 排重。
假如服务器无法保证在五秒内处理并回复，可以直接回复空串，微信服务器不会对此作任何处理，并且不会发起重试。

**Comment by messense** [comment]
看看微信有没有多次发送请求

**Comment by amiden** [comment]
时间确认过，服务器时间Sun Apr  9 14:24:26 CST 2017与世界时间无误，腾讯服务器的时间
多次请求状况正在确认中
 if msg.type == 'text':
分支的返回没有任何问题
图片回复没有问题

**Comment by amiden** [comment]
以下位服务器打印信息 ：
第一次为微信输入1 返回1
第二次发送一张图片 返回ok3
第三次扫描带参二维码 返回ok 额外返回标题错误字段
get muss
<Request 'http://XXXX.net/wechat?signature=4422daf24846a0bb8cd702966614439a673a8a67&timestamp=1491719402&nonce=1427181755&openid=oJ25Vs6eiYVDjC0_KlfDPn5lPQkw' [POST]>
msg TextMessage(OrderedDict([(u'ToUserName', u'gh_99dd0bb2692f'), (u'FromUserName', u'oJ25Vs6eiYVDjC0_KlfDPn5lPQkw'), (u'CreateTime', u'1491719402'), (u'MsgType', u'text'), (u'Content', u'1'), (u'MsgId', u'6406886046812118689')]))
182.254.86.144 - - [09/Apr/2017 14:30:02] "POST /wechat?signature=4422daf24846a0bb8cd702966614439a673a8a67&timestamp=1491719402&nonce=1427181755&openid=oJ25Vs6eiYVDjC0_KlfDPn5lPQkw HTTP/1.1" 200 -
get muss
<Request 'http://XXXX.net/wechat?signature=415740b176924b2c52c3a35a4b4ddd8df2b865f6&timestamp=1491719413&nonce=1312590781&openid=oJ25Vs6eiYVDjC0_KlfDPn5lPQkw' [POST]>
msg ImageMessage(OrderedDict([(u'ToUserName', u'gh_99dd0bb2692f'), (u'FromUserName', u'oJ25Vs6eiYVDjC0_KlfDPn5lPQkw'), (u'CreateTime', u'1491719412'), (u'MsgType', u'image'), (u'PicUrl', u'http://mmbiz.qpic.cn/mmbiz_jpg/RkXcic5l5Ggzq9Le5lm7ibqQPhicWUcRLdNn9QGCh57UPiaDIZmF827iapY24trngKrhCDCyIs8qQo3y4cH16KDia0fg/0'), (u'MsgId', u'6406886089761791654'), (u'MediaId', u'Y-tLqn21SUF6nSISBw5WbXqd2bEO1l_IYAeJRGv4aIuFLLUUDhRmDTMmZk9o7nCH')]))
182.254.86.154 - - [09/Apr/2017 14:30:13] "POST /wechat?signature=415740b176924b2c52c3a35a4b4ddd8df2b865f6&timestamp=1491719413&nonce=1312590781&openid=oJ25Vs6eiYVDjC0_KlfDPn5lPQkw HTTP/1.1" 200 -
get muss
<Request 'http://XXXX.net/wechat?signature=16f1b3d814da6369e23ff46280b7aa5d9e92e854&timestamp=1491719451&nonce=873918876&openid=oJ25Vs6eiYVDjC0_KlfDPn5lPQkw' [POST]>
msg ScanEvent(OrderedDict([(u'ToUserName', u'gh_99dd0bb2692f'), (u'FromUserName', u'oJ25Vs6eiYVDjC0_KlfDPn5lPQkw'), (u'CreateTime', u'1491719451'), (u'MsgType', u'event'), (u'Event', u'SCAN'), (u'EventKey', u'106'), (u'Ticket', u'gQFy8TwAAAAAAAAAAS5odHRwOi8vd2VpeGluLnFxLmNvbS9xLzAycnRsSWdtREs5bFAxMDAwME0wM3AAAgTmkuNYAwQAAAAA')]))
182.254.86.149 - - [09/Apr/2017 14:30:51] "POST /wechat?signature=16f1b3d814da6369e23ff46280b7aa5d9e92e854&timestamp=1491719451&nonce=873918876&openid=oJ25Vs6eiYVDjC0_KlfDPn5lPQkw HTTP/1.1" 200 -

**Comment by amiden** [comment]
带参二维码兑换地址
https://mp.weixin.qq.com/cgi-bin/showqrcode?ticket=gQFy8TwAAAAAAAAAAS5odHRwOi8vd2VpeGluLnFxLmNvbS9xLzAycnRsSWdtREs5bFAxMDAwME0wM3AAAgTmkuNYAwQAAAAA

**Comment by messense** [comment]
@amiden 我刚刚扫了一下上面的二维码没有显示“该公众号暂时无法提供服务，请稍后再试 ”的提示

**Comment by amiden** [comment]
我现在扫还有，用了2个微信号。 
服务器并没有收到你的扫码事件额！

**Comment by messense** [comment]
服务器是在国内还是国外？

**Comment by amiden** [comment]
服务器在国内，选的是腾讯的。

**Comment by amiden** [comment]
看到最后一条不是我扫的信息，是否与是否关注有关

**Comment by messense** [comment]
未关注是 subscribe_scan，已关注是 scan

**Comment by amiden** [comment]
代码中作同处理
 if msg.event == 'subscribe_scan' or msg.event == 'scan':
关注后再扫码会报错!

**Comment by amiden** [comment]
返回指定字段的同时返回标题错误灰字

**Comment by messense** [comment]
感觉对这类事件处理应该直接返回空串：`return ''`，然后用主动调用接口去发送消息给用户。

**Comment by amiden** [comment]
好的   我再测试一下直接返回空字段，
奇怪的就是测试平台没有任何问题，转移到正式公众号后出现，困扰2天多了

**Comment by amiden** [comment]
@messense  重测直接返回return '' 问题依旧，我梳理一下公众号设置。非常感谢

**Comment by amiden** [comment]
@messense  谢谢你的无私帮助。
在打爆了腾讯客服的技术热线后 解决了问题。原因：管理账号授权了第三方平台（我这里腾讯云）
1.登录微信公众平台。
2.点击左侧【添加功能插件】。
3.打开后切换到【授权管理】。
4.取消授权
5.再登录那个第三方平台，在用管理者账号授权时，选择自定义，去掉勾选的【账号服务授权】，
然后就ok啦

**Comment by 923145852** [comment]
@amiden 你好，我也在调试这个功能，碰到的问题和你一样。关注后再扫描二维码，会有这句提示。可是我并没有授权过第三方平台。现在也很困扰这个问题
