### ISSUE TITLE
遇到了一些问题

### ISSUE THREAD

**Issue by cloverstd** [wechatpy/wechatpy#22]
1. 图片消息缺少 media_id
2. 下载多媒体文件时，返回的不是 json，应该是文件 stream，对应的 requests 中应该是 r.content，

以上均在企业号中使用遇到的问题

PS：真是想不明白为什么『弹出系统拍照发图的事件推送』这个事件中微信不返回图片的 media_id，而是图片的 md5。

还有一个问题是『弹出拍照或者相册发图的事件推送』，在选择相册图片后，微信没有按照它规定的格式发过来 count 和 PicList，发过来的 PicList 为空，并且 count 为 0，造成了wechatpy 解析消息后得到的 PicList 为 None

**Comment by messense** [comment]
收到，有空会看下。同时欢迎 PR，最近有点忙.......

**Comment by messense** [comment]
发布了一个新的 bugfix 版本 0.7.4，发现其它问题的话欢迎再次提交 issue 或者 pull requests. :smile:
