### ISSUE TITLE
pypi上的1.3.1与这里master的不一样，建议尽快升级pypi上的

### ISSUE THREAD

**Issue by daimon99** [wechatpy/wechatpy#222]
主要是这段的bug，jsapiticket的Session的key命名，pypi上的版本，
```
self.session.set('jsapi_ticket', ticket)
```
没按appid区分key，导致多个公众号管理的时候出现问题。
但我看这里的master版本，已经修复这个bug了
```
ticket_key = '{0}_jsapi_ticket'.format(self.appid)
```
建议这里的wechatpy的`__init__`中把`version`改为1.3.2，并尽快升级pypi上的1.3.1版本。

**Comment by messense** [comment]
Will do a release this week as 1.4.0 contains some breaking changes.

**Comment by messense** [comment]
https://github.com/jxtech/wechatpy/milestone/2

**Comment by messense** [comment]
[v1.4.0](https://pypi.python.org/pypi/wechatpy/1.4.0) released on PyPi.
