### ISSUE TITLE
新版企业微信获取ACCESSTOKEN时功能不足

### ISSUE THREAD

**Issue by tedi3231** [wechatpy/wechatpy#224]
微信现在正将企业号全面升级为企业微信，新申请的企业号都会作为企业微信存在，但接口上作了小的调整，其中最重要的是调整了access_token的获取方式。
新的access_token在不同的应用中都不相同，而不是像之前只有一个，现在是根据：

- corpid
- secret 指应用的secret

那在缓存的时候也需要针对不同的应用进行缓存，目前的access_token_key是这样的，会导致不同的应用仍然获取了同一个值，从而导致失败：
`
    @property
    def access_token_key(self):
        return '{0}_access_token'.format(self.appid)
`
能否针对企业微信做些变更，可以把key值变为self.appid + appsecret[10:]这样的方式

**Comment by messense** [comment]
有兴趣可以发 PR.

**Comment by tedi3231** [comment]
好的，我先在本地测试下看看，目前基本上可行，但在session中发现总是一条数据。在企业号的__init__.py文件中加了下面的代码：

`
    @property
    def access_token_key(self):
        return "{0}_{1}_access_token".format(self.appid,self.secret[0:10])
`

`  
    @property
    def refesh_token_key(self):
        return "{0}_{1}_access_token".format(self.appid,self.secret[0:10])
`

**Comment by messense** [comment]
refresh_token 是第三方平台用的吧。
