### ISSUE TITLE
怎么获取登录成员的身份信息？

### ISSUE THREAD

**Issue by ryzn0518** [wechatpy/wechatpy#229]
官方有一个关于使用`oauth.get_user_info`的示例，可以在控制台打印出userid和deviceid，可是我要获取登录成员的身份信息，该怎么获取呢？

**Comment by xiaohuanshu** [comment]
知道了userid,就可以通过user.get继续获取用户详细信息啊

**Comment by ryzn0518** [comment]
@xiaohuanshu 可是并不能获取详细的身份信息呀。scope是snsapi_userinfo或snsapi_privateinfo的数据看不到呀。

**Comment by xiaohuanshu** [comment]
我这里能获取到详细信息啊，你有fetch_access_token吗？

**Comment by ryzn0518** [comment]
@xiaohuanshu 
```
client = WeChatClient(
    CORP_ID,
    SECRET
)


def oauth(method):
    @functools.wraps(method)
    def warpper(*args, **kwargs):
        user_agent = request.headers.get('User-Agent')
        print "user_agent",user_agent
        code = request.args.get('code', None)

        url = client.oauth.authorize_url(request.url)
        print "url",url
        print "code",code

        if code:
            try:
                user_info = client.oauth.get_user_info(code)
                # user = client.user.get(user_id=user_info["UserId"])
                # print "user", user

            except Exception as e:
                # 这里需要处理请求里包含的 code 无效的情况
                abort(403)
            else:
                session['user_info'] = user_info
        else:
            print "redirect(url)",redirect(url)
            return redirect(url)

        return method(*args, **kwargs)
    return warpper


@main.route('/')
@oauth
def index():
    user_info = session.get('user_info')

    print "user_info",user_info
    return "Hello"
```
我是这么写的。可是只能获取到userid和deviceid，执行 user = client.user.get(user_id=user_info["UserId"])就会报错。报错提示是没有权限。

**Comment by xiaohuanshu** [comment]
我没用client.oauth这种方式（不太清楚能不能这么用）
先from wechatpy.oauth import WeChatOAuth
wechatoauth = WeChatOAuth(APPID, APPSECRET,"URL",'snsapi_userinfo')
然后从get中获取code.
response = wechatoauth.fetch_access_token(code)
最后userinfo = wechatoauth.get_user_info()
userinfo里面就是详细信息。
你试试看吧

**Comment by xiaohuanshu** [comment]
你用的client.oauth？企业号？我没有在WechatClient中找到oauth啊

**Comment by xiaohuanshu** [comment]
看你用了CORP_ID还真是企业号啊。。提问说清楚啊。。企业号和公众号不一样的。企业号get_user_info确实只能获得userid和deviceid,获取详细信息使用user.get。这里获取的详细信息也和公众号不一样，是企业内账户的详细信息。无法获得省份啊之类的

**Comment by xiaohuanshu** [comment]
具体能看到的数据微信的文档写的很清楚了。http://qydev.weixin.qq.com/wiki/index.php?title=OAuth%E9%AA%8C%E8%AF%81%E6%8E%A5%E5%8F%A3
  "userid":"lisi",
  "name":"李四",
  "department":[3],
  "position": "后台工程师",
  "mobile":"15050495892",
  "gender":1,
  "email":"xxx@xx.com",
  "avatar":"http://shp.qpic.cn/bizmp/xxxxxxxxxxx/0"

**Comment by ryzn0518** [comment]
@xiaohuanshu 不知道，你用过企业号没有，我想再浏览器打开我们服务，怎么能自动生成一个二维码供用户扫描登陆啊

**Comment by cloverstd** [comment]
@diaojunxian 

上面的是在手机上的 OAuth 认证登录

你需要在电脑上通过手机扫描登录，应该用企业号提供的[单点登录](http://qydev.weixin.qq.com/wiki/index.php?title=%E5%8D%95%E7%82%B9%E7%99%BB%E5%BD%95%E6%8E%88%E6%9D%83)

我最开始用企业号的时候，没有这个，我自己实现了二维码扫描登录，不过我用的是微信服务号的接口，具体可以参考[这里](https://hui.lu/wechat-qr-scan-login/)，这种 hack 方式不太推荐，推荐使用官方提供的[单点登录](http://qydev.weixin.qq.com/wiki/index.php?title=%E5%8D%95%E7%82%B9%E7%99%BB%E5%BD%95%E6%8E%88%E6%9D%83)接口

**Comment by xiaohuanshu** [comment]
wechatpy中已经实现了企业号单点登录的接口

**Comment by ryzn0518** [comment]
@xiaohuanshu @cloverstd 我好奇为啥都说是单点登录而不是成员登陆授权，我自己在本地试了成员登陆，可是一直提示校验码错误。wechapy中看不到单点登录的api呀。

**Comment by cloverstd** [comment]
@diaojunxian 按照你的需求描述，按照企业号提供的接口，就是单点登录

**Comment by xiaohuanshu** [comment]
抱歉抱歉，被前一个人误导了，没错是“成员登录授权”，“成员登录授权”是用来登录自己网站的，“单点登录”是用来登录企业号官网的。wechatpy对应的api在service.get_login_info

**Comment by ryzn0518** [comment]
@xiaohuanshu 我看到service的确有这个对应的api，但是成员授权登陆，应该会是生成一个二维码，然后让用户扫描之后，获取一个auth_code，传给service.get_login_info使用，我这里不知道如何生成这个二维码

**Comment by xiaohuanshu** [comment]
@diaojunxian 你应该仔细阅读一下开发文档，目前没有办法生成二维码（看企业微信的文档估计很快就有了），它的登录是通过跳转到一个url再让用户扫描二维码的。也就是目前没法在自己的登录页面放置二维码扫描
