### ISSUE TITLE
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

### ISSUE THREAD

**Issue by acatadog** [wechatpy/wechatpy#230]
我使用WeChatOAuth.fetch_access_token()方法的时候，出现了下面的错误

> Traceback (most recent call last):
>   File "c:\python34\lib\site-packages\django-1.10.6-py3.4.egg\django\core\handlers\exception.py", line 42, in inner
>     response = get_response(request)
>   File "c:\python34\lib\site-packages\django-1.10.6-py3.4.egg\django\core\handlers\base.py", line 187, in _get_response
>     response = self.process_exception_by_middleware(e, request)
>   File "c:\python34\lib\site-packages\django-1.10.6-py3.4.egg\django\core\handlers\base.py", line 185, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
> 
>   ...
> 
>   File "c:\python34\lib\site-packages\wechatpy\oauth\__init__.py", line 153, in fetch_access_token
>     'grant_type': 'authorization_code'
>   File "c:\python34\lib\site-packages\wechatpy\oauth\__init__.py", line 96, in _get
>     **kwargs
>   File "c:\python34\lib\site-packages\wechatpy\oauth\__init__.py", line 65, in _request
>     **kwargs
>   File "c:\python34\lib\site-packages\requests\api.py", line 58, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "c:\python34\lib\site-packages\requests\sessions.py", line 513, in request
>     resp = self.send(prep, **send_kwargs)
>   File "c:\python34\lib\site-packages\requests\sessions.py", line 623, in send
>     r = adapter.send(request, **kwargs)
>   File "c:\python34\lib\site-packages\requests\adapters.py", line 514, in send
>     raise SSLError(e, request=request)
> requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

我baidu了一下上面的错误，其中一篇文章是说这是由于证书校验的问题，可以使用verify=False来解决，但由于WeChatOAuth.fetch_access_token()方法在封装的时候并没有留下额外的参数方法，所以不知道官方有什么好的解决方案？或者可以考虑在下个版本的时候为所有类似这样的接口都増加额外的方法？
附：baidu出来的解决方案
http://blog.csdn.net/xiaopangxia/article/details/49908889

**Comment by messense** [comment]
#128

**Comment by acatadog** [comment]
用了@fydot的方法，把 certifi 的版本降级到 2015.9.6.2 ，问题解决。
