### ISSUE TITLE
获取预授权码的方法是不是少了参数

### ISSUE THREAD

**Issue by MyJoiT** [wechatpy/wechatpy#231]
[component.py](https://github.com/jxtech/wechatpy/blob/master/wechatpy/component.py)
中的WeChatComponent类里面有一个方法：**create_preauthcode**

此方法用来获取预授权码，方法内部发送的请求是  **/component/api_create_preauthcode**

但是看到微信文档中的请求是  **/component/api_create_preauthcode?component_access_token=xxx**

这方法中是不是少了**component_access_token**这个参数

**Comment by messense** [comment]
https://github.com/jxtech/wechatpy/blob/master/wechatpy/component.py#L105

`component_access_token` 会被自动填充。
