### ISSUE TITLE
api调用 报ssl handshake 错误

### ISSUE THREAD

**Issue by tinyms** [wechatpy/wechatpy#234]
centos6，pyenv python版本3.5.3，key与cert都是从官方下载并指定的，参数传递再三检查没有传递错误，但是请求的时候还是报错

**Comment by messense** [comment]
#128

**Comment by messense** [comment]
问题解决了吗？

**Comment by tinyms** [comment]
还没有，既然已经有一个类似问题，我先关闭这个吧

**Comment by tinyms** [comment]
我使用 #128 提及的命令 `openssl s_client -showcerts -connect api.weixin.qq.com:443` 检测，返回一个错误 `Verify return code: 20 (unable to get local issuer certificate)`，然后给这个命令加一个选项 -CAfile rootca.pem，这次返回正常 `Verify return code: 0 (ok)`，能不能在创建WeChatClient的时候加多一个参数，传入 CA 证书?

**Comment by messense** [comment]
你可以把 root ca 导入到系统中并设置为信任。

**Comment by tinyms** [comment]
导入过，没成功，一直提示这个错误，`p11-kit: duplicate 'Equifax Secure Certificate Authority' certificate found in: ca-bundle.legacy.crt`，还没找到为什么会出现这个错误提示。
如果能直接通过参数传递的话是最好的，这样就不需要额外去配置，即使不是很熟悉某个操作系统，功能都不会出现错误。

**Comment by messense** [comment]
https 证书的问题不应该要求 library 来解决，毕竟腾讯也不是用的自签名的证书。
出现这种问题要么是用户系统的问题，要么是腾讯部署的证书的问题，如果浏览器或者 openssl s_client 都无法连接，建议更换系统或者和腾讯客服联系解决。

**Comment by tinyms** [comment]
查看requests请求参数说明：
verify: (optional) Either a boolean, in which case it controls whether we verify
            the server's TLS certificate, or a string, in which case it must be a path
            to a CA bundle to use. Defaults to ``True``
然后我继承WeChatPay传递一个verify参数进去，重载_request方法，在商户证书那里增加kwargs['verify'] = self.verify，创建对象时给verify赋一个rootca.pem路径给它，再次测试，问题解决, 可以支付了。
上面那个重复错误，说明系统已经有了相同的CA证书，只是在pyenv中，requests可能获取不到这个CA证书。
最后，我还是建议可以添加一个verify的参数进去，方便传递CA证书。这样在任何环境中功能都正常。

**Comment by messense** [comment]
`verify=False` 存在被中间人攻击的风险，it's a [footgun](http://www.urbandictionary.com/define.php?term=footgun).

**Comment by ramwin** [comment]
设置verify=False小心服务器被劫持后钱都被盗走哦。说不定就是因为被劫持了，所以verify才是false的
