### ISSUE TITLE
已关注用户扫描带场景值二维码没有接收到事件推送

### ISSUE THREAD

**Issue by MyJoiT** [wechatpy/wechatpy#236]
未关注用户扫描**可以**接收到
单击菜单跳转网页**可以**接收到
单击菜单拉取消息**没有接收**到
是我url配置有问题吗。。

**Comment by messense** [comment]
依靠什么判断出来那些没有接收到而不是没有正确处理？

**Comment by MyJoiT** [comment]
接收到post推送之后，我是在控制台上实时打印。其他的推送都可以直接打印正确的消息。

**Comment by messense** [comment]
需要提供一些日志帮助 debug.

**Comment by MyJoiT** [comment]
并没有记录日志。。我昨天刚开始写这个。
这是接收事件url
![default](https://user-images.githubusercontent.com/8382072/27625231-78878600-5c16-11e7-866f-d971950fd3f9.png)

**Comment by MyJoiT** [comment]
莫非一些事件需要不同的处理？可以URL只有一个。。。有些事件我在微信上触发后，这个URL第一条print也没有执行。所以感觉很疑惑。

**Comment by messense** [comment]
加密模式 reply xml 也需要加密。

https://github.com/jxtech/wechatpy/blob/master/examples/echo-encrypted/app.py#L64

**Comment by messense** [comment]
接受不到请求很难确定是什么问题，看看微信公众号后台有没什么信息提示。

**Comment by MyJoiT** [comment]
我的开发里面包含了第三方的。微信后台配置我基本可以确定。官方文档也是全部看了。就觉得奇怪有些事件正常接收。有些事件就接收不到。你那边有条件可以试试吗。

**Comment by messense** [comment]
第三方是指？

**Comment by MyJoiT** [comment]
微信开放平台里的第三方
![_20170628160926](https://user-images.githubusercontent.com/8382072/27626848-320a0f30-5c1c-11e7-9d0d-05ccdaf36843.png)

**Comment by messense** [comment]
这个不是很清楚。

cc @hunter007

**Comment by hunter007** [comment]
这个事件早已出现，wechatpy 也支持了。没有收到不好判断，建议用微信提供的测试方法进行调试。
另外，如果使用第三方接口的话，按下面代码处理就行：
        component = get_component()
        content = component.crypto.decrypt_message(
            request.body,
            request.query_params['msg_signature'],
            int(request.query_params['timestamp']),
            int(request.query_params['nonce'])
        )

request是 django 下的 Request 实例。

**Comment by MyJoiT** [comment]
好的。我再试试看吧。

**Comment by shoutrain** [comment]
@MyJoiT 我也遇到这个问题：对于已经关注的用户来说，再次扫描带参数二维码，这个推送消息后端服务收不到。我也是第三方平台的授权接入。请问您现在解决了吗？

**Comment by MyJoiT** [comment]
@shoutrain 我的解决方法非常的奇葩。代码我一句没改。

1、去开放平台里的“权限集”里面，加上“开放平台帐号管理权限”这一项
2、把公众平台绑定的你的第三方解绑
3、用管理员的微信再去重新绑定，注意把这个权限一定要勾上

**Comment by MyJoiT** [comment]
@shoutrain 我之前也重新绑定过。不过我用的运营者的微信。死活都不行。用管理员的重新绑定了之后就可以了。而且此时再解绑。用运营者微信去绑定也没问题了。

**Comment by shoutrain** [comment]
@MyJoiT 感谢：）我也刚解决，在和其他正常的第三放平台的权限列表比较后，果然是少了“帐号管理权限”
