### ISSUE TITLE
优化requests的使用，启用Session方式，优化和微信服务器的连接

### ISSUE THREAD

**Issue by zhaoqz** [wechatpy/wechatpy#237]
目前是直接使用requests.request来和微信服务器通信，每个请求都要建立https连接。
建议修改为：初始化全局requests.Session对象，请求使用session.request方法来通信。
在频繁访问微信服务器时，可以减少不少https链接的建立。
下面的文章介绍了requests包的连接池的有些案例
https://laike9m.com/blog/requests-secret-pool_connections-and-pool_maxsize,89/

**Comment by messense** [comment]
Pull requests are welcome.

**Comment by zhaoqz** [comment]
我就加了一句话:
import requests
http = requests.Session()

-    requests.request
+    http.request

要发起pull requests，第一步，变量命名就觉得不合适，第二步，觉得测试按时也要同步修改。
再等等了。
