### ISSUE TITLE
更新OAuth相关代码

### ISSUE THREAD

**Issue by liriansu-opus** [wechatpy/wechatpy#243]
> 背景：
> 微信网页授权采用 OAuth2.0，需要用code来换openid
> 文档参见 https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140842

我找了下发现[`wechatpy/oauth/__init__.py`](https://github.com/jxtech/wechatpy/blob/master/wechatpy/oauth/__init__.py)里面有相关代码

不过感觉这个和其它的模块风格很不统一啊，
不如整合进`wechatpy.client.api`里面，
然后调用方式就可以变成`wechat_client.oauth.get_access_token`这样了。

建议如何？
假如可以的话我提个PR

**Comment by messense** [comment]
因为 OAuth 2 有自己的授权机制，和 `WeChatClient` 没有什么关系，所以独立出来了。企业号的 OAuth 2 反而是和 client 有关的所以放在 client 上。

**Comment by messense** [comment]
另外 access_token 在 `WeChatClient` 里面有自己的含义，OAuth 里面又是另一种含义，放在一起也比较 confusing.

**Comment by liriansu-opus** [comment]
嗯，了解了~
