### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by messense** [wechatpy/wechatpy#245]
You will be given write access to this repository.

Requirements:

1. Understand advanced Python techniques (mostly meta-programming).
2. Understand `wechatpy`'s internal design.

**Comment by liriansu-opus** [comment]
唔，举手自荐，我愿意当maintainer。

[我司 (zaihui)][zaihui]目前做的是SaaS服务，
用的 Python + Django。

因为一部分东西是基于微信开发的，
以前用的库是[wechat-python-sdk][wxpy-sdk]。
一直想换库，
最近才换完，
换成了wechatpy。

有什么想法求交流，
比如一些 milestone, todo 什么之类的。

[zaihui]: https://www.kezaihui.com
[wxpy-sdk]: https://github.com/doraemonext/wechat-python-sdk

**Comment by messense** [comment]
@LKI Invited. Please check your email.

**Comment by messense** [comment]
@cloverstd @LKI 你们的 pypi 用户名都是啥，我给你们发布权限。

**Comment by cloverstd** [comment]
@messense 同 ID

:confused: 现在的工作已经没有做与微信相关的了，只是个人玩玩了

**Comment by messense** [comment]
@cloverstd Added.

目前工作中也用得不多，一些基础的接口。所以比较需要更多的 maintainers

**Comment by messense** [comment]
@cloverstd BTW, https://github.com/wechatpy/wechatpy-tornado 估计现在可用了...

**Comment by liriansu-opus** [comment]
@messense ID是`lirian`~
具体发布流程什么的，小弟我不太熟悉，所以可能要先学习一个……

是要先`bumpversion`，再`py27/py34/py35/py36`挨个build一遍吗

**Comment by cloverstd** [comment]
@messense 工作中用到 Tornado，然而发现如果不能所有的操作都异步化的话，对于性能的是副作用。
而且 Tornado 不是一般人 hold 住的，很容易写出 block 的代码。

pypi 的发布能不能和 github 的 release 结合在一起自动发布呀？
通过 robot，当某一个版本的 roadmap 完成后，然后自动发布。

**Comment by liriansu-opus** [comment]
@cloverstd 自动release感觉很科学，不过我没找到比较热门的bot。是不是因为release往往要password之类的，不好搞的原因？

**Comment by messense** [comment]
patch 版本（major.minor.x）bumpversion patch
minor 版本：bumpversion minor

构建：python setup.py sdist bdist_wheel
上传：twine upload dist/*

auto release 我近期可以弄一下。

**Comment by messense** [comment]
@LKI 自动 release 并不麻烦，我司内部的库目前大多是自动 release 到私有 PypiCloud 上的。password 可以用加密环境变量。

**Comment by messense** [comment]
发布之前还需要确认一下 [`docs/changelog.rst`](https://github.com/jxtech/wechatpy/blob/master/docs/changelog.rst) 更新好了。

**Comment by messense** [comment]
> 再py27/py34/py35/py36挨个build一遍吗

@LKI 因为是 universal wheel 只需要在一个版本下构建上传就可以了。带二进制文件的即非 universal wheel 才需要各个版本构建。

**Comment by liriansu-opus** [comment]
@messense 好的！多谢指教！我先理解学习一下。 😃
