### ISSUE TITLE
device_event 事件被解析成UnknownMessage

### ISSUE THREAD

**Issue by bl52785592** [wechatpy/wechatpy#246]
parse.py 中parse_message函数 在转换device_event事件时，event_type 赋值为XML中的MsgType，导致MESSAGE_TYPES.get(event_type , UnknownMessage)函数中 event_type全部为‘device_event’。此情况出现在 设备的绑定、解绑、订阅状态、取消订阅状态等事件中。

```python
OrderedDict(
[(u'ToUserName', u'gh_1111111'), 
(u'FromUserName', u'1111111'),
 (u'CreateTime', u'1500873376'), 
 (u'MsgType', u'device_event'),
 (u'Event', u'bind'),
 (u'DeviceType', u'gh_19028e11c2e0'),
 (u'DeviceID', u'gh_19028e11c2e0_111111111'),
 (u'Content', None),
 (u'SessionID', u'0'),
 (u'OpenID', u'o011111111')
])
```

其他朋友提出的  device_text事件中没有event字段，我并没有使用到。如果有必要  device_event与device_text事件应该分开处理。

**Comment by messense** [comment]
cc #235
