### ISSUE TITLE
公众号群发消息当目标是全部用户，仍然需要传参group_or_users

### ISSUE THREAD

**Issue by lxkaka** [wechatpy/wechatpy#258]
建议group_or_users改为关键字参数

**Comment by messense** [comment]
因为参数改变是一个 break change，可能需要想想如何避免 break 很多人的代码。

**Comment by liriansu-opus** [comment]
想了一下，假如要做这个的话，以前函数signature是这样的：

```
def send_mass_text(self, group_or_users, content, is_to_all=False, preview=False):
    ...
```

改了以后可能是这样子：

```
def send_mass_text(self, group_or_users=None, content=None, is_to_all=False, preview=False):
    if content is None:
        raise ValueError('content must not be None')
    ...
```

这样改动调用方想设置`is_to_all=True`的确方便了，
但是函数signature会很迷，有种什么参数都不用传也能跑的错觉。
或者我们也可以开个新的函数？但那样就感觉得不偿失了。。。

@messense 你的看法是怎么样的？

**Comment by messense** [comment]
目前的情况下只是增加需要传 `None` 的麻烦，感觉不一定值得去改这个 API，可以先文档上提一下。

**Comment by liriansu-opus** [comment]
@messense 赞同，就取个妥协办法，加个文档说明一下好了。
API这么改动，反而变得丑陋了。

**Comment by messense** [comment]
reopen 作为以后可以做 breaking changes 时的任务

**Comment by messense** [comment]
这个可以改了。
