### ISSUE TITLE
需要有个 WeChatErrorCode 类来记一下常见的微信错误码

### ISSUE THREAD

**Issue by liriansu-opus** [wechatpy/wechatpy#260]
微信的ErrCode什么的太分散了，
需要有一个类来汇总记一下错。

这样那些40001, 42001也不用写成Magic Number

**Comment by messense** [comment]
叫 `WeChatErrorCode` 合适些。可以用 [enum](https://docs.python.org/3/library/enum.html) 来做，对 Python 2 可以用 [enum34](https://pypi.python.org/pypi/enum34)

**Comment by liriansu-opus** [comment]
嗯，可以，我去想想咋整
