### ISSUE TITLE
create_reply中的reply

### ISSUE THREAD

**Issue by snowleung** [wechatpy/wechatpy#263]
如过reply参数是数字的话，将会返回空。
已经检测了reply是字符串，请问改为
“尝试reply 是否可以被转换为string，可以就用TextReply包装返回”
会不会跟好一些？

**Comment by snowleung** [comment]
https://github.com/jxtech/wechatpy/blob/master/wechatpy/replies.py#L318

**Comment by liriansu-opus** [comment]
嗯，多谢反馈。
这个改动相当于把默认返回类型改成了字符串，
可能会造成一定的兼容性问题。

不过鉴于这个本身是quick reply，
应该这个改动是可以接受的。

@messense 觉得怎么样

**Comment by messense** [comment]
如果只是为了返回数字，那最好还是调用者保证把数字显式转换成字符串。如果还有其它用途，请说明。

**Comment by messense** [comment]
在 Python 中大部分类型都可以转换成字符串，但它们的行为并不一定是你想要的，默认转换可能会出现奇奇怪怪的字符串。

**Comment by messense** [comment]
For instance:

```python
In [1]: a = object()

In [2]: str(a)
Out[2]: '<object object at 0x1056c0cf0>'
```
