### ISSUE TITLE
微信支付退款通知解析

### ISSUE THREAD

**Issue by messense** [wechatpy/wechatpy#266]
https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=9_16

**Comment by messense** [comment]
> 解密步骤如下： 
（1）对加密串A做base64解码，得到加密串B
（2）对商户key做md5，得到32位小写key* ( key设置路径：微信商户平台(pay.weixin.qq.com)-->账户设置-->API安全-->密钥设置 )
（3）用key*对加密串B做AES解密

这个文档太晦涩了，需要退款通知的例子才能开发...

**Comment by liriansu-opus** [comment]
这个看了看，没太看懂。真的需要实际的例子来debug一下才行。

**Comment by tom-master** [comment]
//对加密串A做base64解码，得到加密串B
			var encryptionStrB = Convert.FromBase64String(request);
			//对商户key做md5，得到32位小写key*
			var key = CreateSign(ConfigHelper.Key.ToLower() , "UTF-8");

			Byte[] encryptedBytes = encryptionStrB;
			Byte[] bKey = new Byte[32];
			Array.Copy(Encoding.UTF8.GetBytes(key.PadRight(bKey.Length)) , bKey , bKey.Length);

			MemoryStream mStream = new MemoryStream(encryptedBytes);
			RijndaelManaged aes = new RijndaelManaged();
			aes.Mode = CipherMode.ECB;
			aes.Padding = PaddingMode.PKCS7;
			aes.KeySize = 128;
			aes.Key = bKey;
			CryptoStream cryptoStream = new CryptoStream(mStream , aes.CreateDecryptor() , CryptoStreamMode.Read);
			try
			{
				byte[] tmp = new byte[encryptedBytes.Length + 32];
				int len = cryptoStream.Read(tmp , 0 , encryptedBytes.Length + 32);
				byte[] ret = new byte[len];
				Array.Copy(tmp , 0 , ret , 0 , len);
				return Encoding.UTF8.GetString(ret);
			}
			finally
			{
				cryptoStream.Close();
				mStream.Close();
				aes.Clear();
			}
替换掉ConfigHelper.Key为你的商户秘钥  大家可以试下哈

**Comment by messense** [comment]
@haoxiaofan 来源？

**Comment by tom-master** [comment]
@messense http://www.cnblogs.com/sunxuchu/p/5622307.html

**Comment by sjava** [comment]
pip install pycryptodome

import xmltodict
import base64
import hashlib
from Crypto.Cipher import AES

def parse_refund_result(xml):
    BS = AES.block_size
    pad = lambda s: s + (BS - len(s) % BS) * chr(BS - len(s) % BS)
    unpad = lambda s: s[0:-ord(s[-1])]

    data = xmltodict.parse(xml)['xml']
    req_info = data['req_info'].encode()
    req_info = base64.decodebytes(req_info)
    hash = hashlib.md5()
    hash.update(current_app.config['WECHAT_PAY_API_KEY'].encode())
    key = hash.hexdigest().encode()

    cipher = AES.new(key, AES.MODE_ECB)
    decrypt_bytes = cipher.decrypt(req_info)
    decrypt_str = decrypt_bytes.decode()
    decrypt_str = unpad(decrypt_str)

    info = xmltodict.parse(decrypt_str)['root']
    data = dict(data, **info)
    data.pop('req_info')
    return data

**Comment by sjava** [comment]
pip install pycryptodome
```python
import xmltodict
import base64
import hashlib
from Crypto.Cipher import AES
def parse_refund_result(xml):
    BS = AES.block_size
    pad = lambda s: s + (BS - len(s) % BS) * chr(BS - len(s) % BS)
    unpad = lambda s: s[0:-ord(s[-1])]

    data = xmltodict.parse(xml)['xml']
    req_info = data['req_info'].encode()
    req_info = base64.decodebytes(req_info)
    hash = hashlib.md5()
    hash.update(current_app.config['WECHAT_PAY_API_KEY'].encode())
    key = hash.hexdigest().encode()

    cipher = AES.new(key, AES.MODE_ECB)
    decrypt_bytes = cipher.decrypt(req_info)
    decrypt_str = decrypt_bytes.decode()
    decrypt_str = unpad(decrypt_str)

    info = xmltodict.parse(decrypt_str)['root']
    data = dict(data, **info)
    data.pop('req_info')
    return data
```

**Comment by playwolf719** [comment]
> pip install pycryptodome
> 
> ```python
> import xmltodict
> import base64
> import hashlib
> from Crypto.Cipher import AES
> def parse_refund_result(xml):
>     BS = AES.block_size
>     pad = lambda s: s + (BS - len(s) % BS) * chr(BS - len(s) % BS)
>     unpad = lambda s: s[0:-ord(s[-1])]
> 
>     data = xmltodict.parse(xml)['xml']
>     req_info = data['req_info'].encode()
>     req_info = base64.decodebytes(req_info)
>     hash = hashlib.md5()
>     hash.update(current_app.config['WECHAT_PAY_API_KEY'].encode())
>     key = hash.hexdigest().encode()
> 
>     cipher = AES.new(key, AES.MODE_ECB)
>     decrypt_bytes = cipher.decrypt(req_info)
>     decrypt_str = decrypt_bytes.decode()
>     decrypt_str = unpad(decrypt_str)
> 
>     info = xmltodict.parse(decrypt_str)['root']
>     data = dict(data, **info)
>     data.pop('req_info')
>     return data
> ```

@sjava 我出现了'utf-8' codec can't decode byte 0x9e的错误，你碰到过吗？
谢谢啦，原来WECHAT_PAY_API_KEY指的是商户key，哎，我弄错了

**Comment by zeroleo12345** [comment]
wechatpy库不含这个退款结果通知的解密函数吗?
