### ISSUE TITLE
企业号是不是应该考虑将通讯录接口分离开？

### ISSUE THREAD

**Issue by xiaohuanshu** [wechatpy/wechatpy#268]
目前企业号升级到企业微信后，通讯录相关操作需要使用通讯录操作系统的Secret进行开发，与应用的Secret不同，相关文档：https://work.weixin.qq.com/api/doc#10016 ，个人感觉可以参考服务号将Oauth分离的方式，将通讯录相关接口从wechatpy.enterprise.client中分离出来

**Comment by messense** [comment]
可以尝试，企业号方面我目前没有开发相关的项目，所以这部分的 API 如果有兴趣可以主动发 Pull Requests 来推进。

**Comment by messense** [comment]
在 #431 中处理。
