### ISSUE TITLE
【事件】events中DeviceUnsubscribeStatus的key不正确

### ISSUE THREAD

**Issue by mark-tianfs** [wechatpy/wechatpy#272]
原文件第410行开始：
`@register_event('device_unsubscribe_status')
class DeviceUnsubscribeStatusEvent(BaseEvent):
    event = 'device_subscribe_status'
    device_type = StringField('DeviceType')
    device_id = StringField('DeviceID')
    open_id = StringField('OpenID')
    op_type = IntegerField('OpType')`
第412行应为：
`event = 'device_unsubscribe_status'`

这样的错误没有发现，看来社区里用来做微信硬件的不多。

**Comment by liriansu-opus** [comment]
感谢报bug，我看看~~~
（社区里做微信硬件的，真的不多）
