### ISSUE TITLE
用户标签的get_tag_users传入tag_id后报错

### ISSUE THREAD

**Issue by hayt0n** [wechatpy/wechatpy#273]
![image](https://user-images.githubusercontent.com/5023850/29486095-a1689550-8510-11e7-9f51-c3c5c9763a52.png)

![image](https://user-images.githubusercontent.com/5023850/29486096-b18d6b90-8510-11e7-91d8-205f5e28ffb4.png)

**Comment by liriansu-opus** [comment]
感谢报bug，我试试重现看看。

**Comment by liriansu-opus** [comment]
尝试了一下，未能重现（伪代码如下）：

```
>>> wc
<libs.wechat.client.WeChatClient object at 0x7f96355fbe48>
>>> wc.tag.get()
[{'name': '星标组', 'count': 0, 'id': 2}]
>>> wc.tag.get_tag_users(tag_id=2)
{'count': 0}
```

希望可以做这么几件事情尝试解决这个问题：

1. 升级到最新的版本（目前是`wechatpy==1.5.1`）
2. 尝试调用`client.tag.get()`，根据控制变量法确保微信别的接口是正常的
3. 尝试修改`site-packages/wechatpy/client/api/tag.py`的`get_tag_users`函数，在函数体内增加`print`或者`log`来定位参数问题。

假如还有问题的话，
求一个更详细的重现步骤。

感谢报bug

**Comment by messense** [comment]
不是很懂，标题里说 get_tag_users 而描述里面用的是 get_user_tag 也没有传参数.

https://github.com/jxtech/wechatpy/blob/06da2a06bc122d722f1f08cb766d89d2e24b486a/wechatpy/client/api/tag.py#L111-L124

**Comment by liriansu-opus** [comment]
@messense 我猜是下面那张图贴错了…
忽略掉第二张图，只看标题和第一张图，应该就是@herunyu 想报的issue了。

不过没办法重现 😿

**Comment by messense** [comment]
@LKI 我们应该增加个 issue template，让填一下系统类型、Python、wechatpy 版本。

https://help.github.com/articles/creating-an-issue-template-for-your-repository/

**Comment by liriansu-opus** [comment]
@messense 可以啊，我来搞个草稿吧。
我看很多开源项目（比如vue）都有一个.github文件夹，这种文件也可以丢进去：

https://github.com/vuejs/vue/tree/dev/.github

**Comment by hayt0n** [comment]
抱歉第二张图贴错了...
![image](https://user-images.githubusercontent.com/5023850/29488093-96d78bca-8536-11e7-9670-b05e4b1617d6.png)

我的python版本是3.6
wechatpy是最新版本...我尝试进入源码chac查查

**Comment by hayt0n** [comment]
![image](https://user-images.githubusercontent.com/5023850/29488213-e1e05c30-8538-11e7-8eda-922f12b96d32.png)
我换成python3.5还是这样...其他的接口貌似都没问题..

**Comment by hayt0n** [comment]
![image](https://user-images.githubusercontent.com/5023850/29488249-a1a0ceba-8539-11e7-8b48-8edde3292d5c.png)
很尴尬= =

**Comment by liriansu-opus** [comment]
@herunyu 
你尝试升级一下`requests`包，看能解决不。
不行的话，求贴出来`pip freeze`这条命令的结果

**Comment by liriansu-opus** [comment]
要是还不行，就是玄学问题了……
可以尝试自己实现一下看看有没有问题：

```
url = 'https://api.weixin.qq.com/cgi-bin/user/tag/get'
print(requests.get(url, params={'access_token': wechat_client.access_token, 'tag_id': tag_id}).json())
```

**Comment by hayt0n** [comment]
![image](https://user-images.githubusercontent.com/5023850/29491662-f8f4365c-8593-11e7-8d41-48c7434c634b.png)
是真的很无奈啊...我找朋友也试了也是不行诶...
你能创建一个新的虚拟环境然后试试吗？

**Comment by messense** [comment]
一个 GET 的接口报错 empty post data 也是奇葩.

**Comment by hayt0n** [comment]
![image](https://user-images.githubusercontent.com/5023850/29491735-1d72984a-8597-11e7-8bb5-a474710c5329.png)
我改成这样有东西返回了...但是无论tagid是什么，返回的都是一样的json..就算tagid是一个string他也是这样返回的

**Comment by hayt0n** [comment]
![image](https://user-images.githubusercontent.com/5023850/29491739-43b590b6-8597-11e7-87ed-0bb4bc73393d.png)
我这里几个人都能重现这个问题欸。。

**Comment by messense** [comment]
建议和微信客服联系？可能他们改了 API 没有更新文档，文档上说是 GET 方法。
![image](https://user-images.githubusercontent.com/1556054/29491746-859f76ae-8597-11e7-8654-5ab2b1f549ab.png)

https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140837

**Comment by messense** [comment]
😤下面又写的 POST....傻逼腾讯...

**Comment by hayt0n** [comment]
可是为什么 @LKI 昨天可以跑出来= =

**Comment by messense** [comment]
可能微信公众号的 API 后端是产品经理写的……

发自我的 iPhone

**Comment by hayt0n** [comment]
找了半天，只能发个email过去给他们反应，不知道会不会回复我。
请问有什么其他方法来获取标签下的用户吗？
我的需求是某些用户是同一个组/标签的，然后我需要推送模板消息给这些用户。。

**Comment by liriansu-opus** [comment]
奇怪了，我昨天的`GET`是能跑出来的。
我等下试试`POST`，假如可以的话，我们改成`POST`吧。

**Comment by hayt0n** [comment]
POST我也试了虽然是有东西但是不是正确的返回值啊。。。

**Comment by liriansu-opus** [comment]
😿 我待会按你的代码去跑跑看。

**Comment by liriansu-opus** [comment]
毕竟微信啊，只能说……

**Comment by messense** [comment]
@herunyu @LKI any update?

**Comment by liriansu-opus** [comment]
@messense 暂时没时间搞这个。。。先放一会，有啥更新了我再留言

**Comment by hayt0n** [comment]
@messense  腾讯客服并没有鸟我...

**Comment by messense** [comment]
更新成 POST 了，传正常的 tagid 返回值应该是对的，传字符串好像会返回所有.

**Comment by hayt0n** [comment]
@messense  新建的公众号有个默认的标签叫星标组，tagid=2.获取的数据count应该为0.你那返回的是0吗？

**Comment by messense** [comment]
@herunyu 是的

```python
In [2]: wechat_client.tag.get_tag_users(2)
Out[2]: {'count': 0}
```

**Comment by hayt0n** [comment]
@messense 已经更新了版本还是我去更新源码？

**Comment by messense** [comment]
@herunyu `pip install -U https://github.com/jxtech/wechatpy/archive/master.zip`

**Comment by hayt0n** [comment]
@messense 完美！感谢！
