### ISSUE TITLE
面向硬件平台的get,post需token

### ISSUE THREAD

**Issue by mark-tianfs** [wechatpy/wechatpy#275]
感谢作者对上一个问题的回复，
另一个问题，所有面向硬件平台的get,post请求，需要在baseurl+item后面加
?access_token=ACCESS_TOKEN
目标文件 client=>api=>device=>class WeChatDevice

**Comment by messense** [comment]
access_token will be populated here

https://github.com/jxtech/wechatpy/blob/836fdd3afe921a34f9f661f17b6d0fe496aec4c5/wechatpy/client/base.py#L79

**Comment by liriansu-opus** [comment]
如同上面所说，wechatpy会自动在请求里加上access_token。
假如接口不够用，想手动调用接口的话，可以使用`wechatpy.client.base.BaseWeChatClient.get`函数

https://github.com/jxtech/wechatpy/blob/461eab0ce0325a01ed5f764156c39937effceb29/wechatpy/client/base.py#L170-L175

**Comment by mark-tianfs** [comment]
经验证，你是对的
当然，在证明你是对的时候，我发现了新问题 ，我明天集中一下报给你吧
