### ISSUE TITLE
已经获取到了openid,如何向该用户推送一条文本消息？

### ISSUE THREAD

**Issue by jonahfang** [wechatpy/wechatpy#281]
看了文档和程序，仍然不知道如何做？请教。

**Comment by jonahfang** [comment]
我现在实现了模板消息推送:

```
...
client2 = WeChatClient(app_id, app_secret)
tid = 'ZLIh5f32H0VtYmR9Ven1IuHy0NCyVB-tV2cXepegs3o'  #模板id
data = {'content':{
      'value':u':你好,%s' % user['nickname'],
      'color':'#173177'}}
client2.message.send_template(open_id,tid,data)
```

**Comment by liriansu-opus** [comment]
一般而言有两种办法给用户推送文本消息：

一个是群发接口（给两个以上的用户推送）：
https://github.com/jxtech/wechatpy/blob/b225075d963a6622ea71ec9fe25f6e95142d95a5/wechatpy/client/api/message.py#L303-L332

一个是客服消息回复（要求用户四十八小时内跟公众号有互动）：
https://github.com/jxtech/wechatpy/blob/b225075d963a6622ea71ec9fe25f6e95142d95a5/wechatpy/client/api/message.py#L26-L51
