### ISSUE TITLE
获取access_token时报错

### ISSUE THREAD

**Issue by xiaomacai** [wechatpy/wechatpy#283]
## 问题描述 (Description)
在获取access_token 时报错如下
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.weixin.qq.com', port=443): 
## 配置信息 (Environment/Version)

- OS

linux
- Python

2.7.5
- wechatpy

**Comment by liriansu-opus** [comment]
应该是ssl安全检查没过去？
简单的做法是降低`requests`包的版本，彻底的办法是升级server的证书。

简单的解决办法如下：
```
pip install requests==2.15.1 certifi==2015.4.28
```

**Comment by messense** [comment]
Duplicated of #128 #230 #234 

Maybe we should add this to FAQ #189
