### ISSUE TITLE
shorturl 链接地址api更改

### ISSUE THREAD

**Issue by mengyou658** [wechatpy/wechatpy#289]
## 问题描述 (Description)
http请求方式: POST
https://api.weixin.qq.com/cgi-bin/ **shorturl** ?access_token=ACCESS_TOKEN
代码中依然是'tools/shorturl'
## 配置信息 (Environment/Version)
无
- OS

windows
- Python

3.4
- wechatpy

1.51
## 重现步骤 (Reproducing)
调用short_url接口 Error code: 40066, message: invalid url

**Comment by messense** [comment]
Why did you close the issue?
