### ISSUE TITLE
windows 下用 pip 安装报错

### ISSUE THREAD

**Issue by iouniuniu** [wechatpy/wechatpy#30]
Log 如下，Python 3.4。为什么会用到 Visual C++？如果一定要的话，那怎样才能部署到服务器上去呢？刚开始学习，请多指教

```
creating build\lib.win32-3.4\Crypto\Signature
copying lib\Crypto\Signature\PKCS1_v1_5.py -> build\lib.win32-3.4\Crypto\Signature
copying lib\Crypto\Signature\__init__.py -> build\lib.win32-3.4\Crypto\Signature

Skipping implicit fixer: buffer
Skipping implicit fixer: idioms
Skipping implicit fixer: set_literal

Skipping implicit fixer: ws_comma
running build_ext
building 'Crypto.Random.OSRNG.winrandom' extension
warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.
error: Microsoft Visual C++ 10.0 is required (Unable to find vcvarsall.bat).
----------------------------------------
```

**Comment by messense** [comment]
加解密依赖 PyCrypto，Linux 下会自动编译好。Windows 下可以先安装预编译的二进制 PyCrypto 包之后再 pip 安装。

http://www.voidspace.org.uk/python/modules.shtml#pycrypto

**Comment by messense** [comment]
收到你的邮件了。可以在 SAE 和 BAE 部署。

SAE 参考：
https://github.com/sinacloud/sae-python-dev-guide/issues/39
https://github.com/messense/wechatpy/issues/8

BAE 参考 examples 里面的：
https://github.com/messense/wechatpy/tree/master/examples/bae-echo-enterprise

**Comment by iouniuniu** [comment]
非常感谢你的回复。现在 Pycrypto 好像支持到3.3。我琢磨一下，有问题再请教。

**Comment by messense** [comment]
2.6.1 的支持 3.4
http://www.voidspace.org.uk/python/pycrypto-2.6.1/

32 位： http://www.voidspace.org.uk/python/pycrypto-2.6.1/pycrypto-2.6.1.win32-py3.4.msi
64 位： http://www.voidspace.org.uk/python/pycrypto-2.6.1/pycrypto-2.6.1.win-amd64-py3.4.msi

**Comment by iouniuniu** [comment]
你太棒了。多谢。Github 上也有一个。https://github.com/axper/python3-pycrypto-windows-installer
现在已经安装成功了。多谢

**Comment by bopo** [comment]
windows下使用pip痛苦到蛋碎
