### ISSUE TITLE
找不到 create_menu 方法 

### ISSUE THREAD

**Issue by iouniuniu** [wechatpy/wechatpy#31]
你好，又来请教。

我在使用 client.py 去创建菜单的时候，总提示找不到任何定义的方法，比如 create_menu, send_text_message 等。

代码如下：

from wechatpy import WeChatClient

client = WeChatClient(APPID, AESKEY)
print(client.API_BASE_URL)
client.send_text_message(TOKEN,"123456")

提示
AttributeError: 'WeChatClient' object has no attribute 'send_text_message'

如何把 send_text_message 换成 WeChatClient 的其他方法，也会出现相应的错误 。但是 API_BASE_URL 是可以找到的。请帮忙。谢谢

**Comment by messense** [comment]
请参考文档 http://wechatpy.readthedocs.io/zh_CN/master/client.html#wechatpy.client.api.WeChatMenu.create
发自我的 iPhone

**Comment by iouniuniu** [comment]
多谢。这个转换是怎么来的，为什么要这么做？

**Comment by messense** [comment]
转换的实现看代码就知道了，这样做的目的是避免 WeChatClient 类产生太多的方法以及更好的抽象。

发自我的 iPhone

**Comment by px200** [comment]
@messense 你好！ 你的

> 请参考文档 http://wechatpy.readthedocs.org/en/latest/client.html#wechatmenu-api

失效了，现在正在琢磨如何正常使用client.menu.create, 特别是组织完按钮之后如何把命令发送出去？

**Comment by messense** [comment]
@px200 http://wechatpy.readthedocs.io/zh_CN/master/client.html#wechatpy.client.api.WeChatMenu.create
