### ISSUE TITLE
接受微信支付消息失败

### ISSUE THREAD

**Issue by sum1201** [wechatpy/wechatpy#313]
## 配置信息 (Environment/Version)

微信公众号支付成功后，服务接受微信公众号事件推送收到的信息格式为：
`
<xml>
<appid><![CDATA[*****************]]></appid>
<bank_type><![CDATA[SPDB_CREDIT]]></bank_type>
<cash_fee><![CDATA[1]]></cash_fee>
<fee_type><![CDATA[CNY]]></fee_type>
<is_subscribe><![CDATA[Y]]></is_subscribe>
<mch_id><![CDATA[1493066722]]></mch_id>
<nonce_str><![CDATA[*********************]]></nonce_str>
<openid><![CDATA[********************]]></openid>
<out_trade_no><![CDATA[20171205010109]]></out_trade_no>
<result_code><![CDATA[SUCCESS]]></result_code>
<return_code><![CDATA[SUCCESS]]></return_code>
<sign><![CDATA[83780DD2B0FB606FD20E07D499A76A0D]]></sign>
<time_end><![CDATA[20171205090123]]></time_end>
<total_fee>1</total_fee>
<trade_type><![CDATA[JSAPI]]></trade_type>
<transaction_id><![CDATA[***************************]]></transaction_id>
</xml>
`

使用 一下代码时出错：
`
msg = parse_message(xml)
`
错误信息：

`File "/usr/local/lib/python2.7/dist-packages/wechatpy/parser.py", line 28, in parse_message
    message_type = message['MsgType'].lower()
KeyError: u'MsgType'`

- OS

Ubuntu
- Python

2.7
- wechatpy

1.5.3

**Comment by messense** [comment]
接口使用错误，微信支付结果通知应使用 [parse_payment_result](http://docs.wechatpy.org/zh_CN/master/pay.html#wechatpy.pay.WeChatPay.parse_payment_result) API 解析。

**Comment by sum1201** [comment]
有没有方法判断接受的消息是事件消息，还是支付消息？

**Comment by ramwin** [comment]
> 有没有方法判断接受的消息是事件消息，还是支付消息？

事件消息和支付消息用不同的回调url就可以。
