### ISSUE TITLE
2017下半年新注册微信小程序获取access_token报错Error code: 48001, message: api unauthorized hint: [ulmGqA09071097]

### ISSUE THREAD

**Issue by azurecn** [wechatpy/wechatpy#316]
## 问题描述 (Description)
2017下半年（具体时间未验证）新注册微信小程序获取access_token报错
Error code: 48001, message: api unauthorized hint: [ulmGqA09071097]
## 配置信息 (Environment/Version)

- OS
All Plantform

- Python
2.7 / 3.4 / 3.5 / 3.6 / 

- wechatpy
All

## 重现步骤 (Reproducing)
小程序获取 access_token 或 有关 access_token 的接口操作

**Comment by liriansu-opus** [comment]
确认一下第三方平台有没有开小程序权限？

微信应该是改过了开放平台的权限集。
而且48001是未授权的错
