### ISSUE TITLE
文档里安装最新代码链接错误

### ISSUE THREAD

**Issue by hyacinthus** [wechatpy/wechatpy#321]
由于需要发送小程序，pip上的还没更新，就按照文章上的链接装github的master分支，
结果文档里是这样写的

pip install https://github.com/messense/wechatpy/archive/master.zip

这是一个fork的版本，我研究了好久，怎么都装不了最新的，以为碰到了灵异事件，仔细核对才发现链接不对。。。

**Comment by messense** [comment]
欢迎发 PR 修正。

**Comment by hyacinthus** [comment]
#322
