### ISSUE TITLE
代公众号调用接口 component_verify_ticket 

### ISSUE THREAD

**Issue by lyroge** [wechatpy/wechatpy#323]
## 问题描述 (Description)
调用component.cache_component_verify_ticket(msg, signature, timestamp, nonce)接口时报错，提示parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: syntax error: line 1, column 0

查看代码时，xml.parse 解析时不为xml结构

## 配置信息 (Environment/Version)

- OS

Mac

- Python

2.7

- wechatpy

1.5.4

**Comment by lyroge** [comment]
xmltodict==0.11.0

**Comment by messense** [comment]
Closes as inactive.
