### ISSUE TITLE
微信支付增加HTTP请求参数

### ISSUE THREAD

**Issue by richieyan** [wechatpy/wechatpy#324]
## 问题描述 (Description)
调用微信支付的接口没有超时判断，增加一个http参数，可以按需求控制http请求参数
## 配置信息 (Environment/Version)

- OS

- Python

- wechatpy

**Comment by messense** [comment]
Thanks!

已增加 `timeout` 参数，需要细致定制 requests session 行为可以继承重写 `_http` 属性：
https://github.com/jxtech/wechatpy/blob/721444c16d01d85876b5e7c66e47dbc57726f916/wechatpy/pay/__init__.py#L39
