### ISSUE TITLE
取不出component_verify_ticket

### ISSUE THREAD

**Issue by diguaxiaozi** [wechatpy/wechatpy#327]
在微信推送ticket的接口中，我调用了cache_component_verify_ticket将ticket保存在默认的Memerystorage中，此时能够取到ticket的信息

在另一个接口中，我重新写了component=Component(xxx,xx,xx,xx)，这个时候输出component.component_verify_ticket 却显示为空，这是为什么呀？

他们之间不是应该共同去memerystorage中去取ticket的信息么？

**Comment by NullYing** [comment]
因为你并没有去读取缓存，看代码就知道了
