### ISSUE TITLE
企业付款接口

### ISSUE THREAD

**Issue by zxmsdyz** [wechatpy/wechatpy#330]
## 问题描述 (Description)
企业付款调用微信接口时少了签名sign字段，导致无法调用成功

## 配置信息 (Environment/Version)
- OS
Windows

- Python
3.6 

- wechatpy
1.5.1

## 重现步骤 (Reproducing)
调用WechatPay.transfer.transfer方法即可重现。

**Comment by messense** [comment]
重现步骤请提供部分调用参数，敏感信息用 xxx 等替代。

**Comment by zxmsdyz** [comment]
不好意思  自己的问题，仔细跟踪了下post的时候是有带签名的
