### ISSUE TITLE
请教一下wechatpy这几个立体字是用软件生成的吗？

### ISSUE THREAD

**Issue by owenqsx** [wechatpy/wechatpy#331]
## 问题描述 (Description)
请教一下wechatpy这几个立体字是用软件生成的吗？具体是什么软件？
## 配置信息 (Environment/Version)

- OS

不涉及
- Python

不涉及
- wechatpy

不涉及
## 重现步骤 (Reproducing)

不涉及

**Comment by messense** [comment]
http://patorjk.com/software/taag/#p=display&f=Graffiti&t=Type%20Something%20
