### ISSUE TITLE
为什么 author 是 messense

### ISSUE THREAD

**Issue by wuyazi** [wechatpy/wechatpy#340]
为什么 setup.py 里
author='messense'
和 https://github.com/messense/wechatpy 有什么关系

**Comment by liriansu-opus** [comment]
@messense 是本项目的主contributor，只不过项目挂到了@jxtech 名下

**Comment by liriansu-opus** [comment]
https://github.com/messense/wechatpy 是本项目的一个fork之一

**Comment by wuyazi** [comment]
我知道是 fork 的
我执行
pip install wechatpy
后
pip show wechatpy
显示的是
Home-page: https://github.com/messense/wechatpy
为什么不是
Home-page: https://github.com/jxtech/wechatpy

**Comment by liriansu-opus** [comment]
噢，那个是 https://github.com/jxtech/wechatpy/blob/master/setup.py 文件里写死的，大概没有更新

**Comment by messense** [comment]
url fixed in https://github.com/jxtech/wechatpy/commit/465c85887720070be59a23b3b7702522cec92c5b
