### ISSUE TITLE
请问下这个项目支持 公众号内手机网页的微信登录 吗？

### ISSUE THREAD

**Issue by guotong1988** [wechatpy/wechatpy#351]
很好的项目，赞赞赞，谢谢谢谢！
@messense @hunter007 @filosfino @cloverstd

**Comment by messense** [comment]
OAuth?

https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140842

http://docs.wechatpy.org/zh_CN/master/oauth.html
