### ISSUE TITLE
文档里面链接失效

### ISSUE THREAD

**Issue by ramwin** [wechatpy/wechatpy#355]
## 问题描述 (Description)
文档里面的链接失效了

## 配置信息 (Environment/Version)

- OS
Mac / Windows / Linux

- Python
2.7 / 3.4 / 3.5 / 3.6 

- wechatpy
1.5.1

## 重现步骤 (Reproducing)
访问[文档](http://wechatpy.readthedocs.io/zh_CN/master/client/qrcode.html)，里面的` 详情请参考`后面的链接已经失效，无法跳转到对应的二维码文档页面

**Comment by messense** [comment]
微信的官方文档管理很混乱，没有精力做到完全同步更新，有兴趣可以提 PR 更新，otherwise won't fix.
