### ISSUE TITLE
关于get_appapi_params函数

### ISSUE THREAD

**Issue by xingzhiyuan** [wechatpy/wechatpy#356]
根据我们的get_appapi_params接口得到结果：
        data = {
            'appid': self.appid,
            'partnerid': self.mch_id,
            'prepayid': prepay_id,
            'package': 'Sign=WXPay',
            'timestamp': timestamp or to_text(int(time.time())),
            'noncestr': nonce_str or random_string(32)
        }
        sign = calculate_signature(data, self._client.api_key)
        data['sign'] = sign

然是我对照微信的开发文档的示例：
paySign = MD5(appId=wxd678efh567hg6787&nonceStr=5K8264ILTKCH16CQ2502SI8ZNMTM67VS&package=prepay_id=wx2017033010242291fcfe0db70013231072&signType=MD5&timeStamp=1490840662&key=qazwsxedcrfvtgbyhnujmikolp111111) = 22D9B4E54AB1950F51E0649E8810ACD6

其中
signType字段是MD5
package字段是‘prepay_id=wx2017033010242291fcfe0db70013231072’
https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=7_7&index=3

**Comment by liriansu-opus** [comment]
感觉另外一个函数可以满足需求？
↓
https://github.com/jxtech/wechatpy/blob/master/wechatpy/pay/api/jsapi.py#L33-L59

**Comment by xingzhiyuan** [comment]
妙啊
