### ISSUE TITLE
PyPI 打包问题

### ISSUE THREAD

**Issue by ldsink** [wechatpy/wechatpy#367]
https://pypi.org/project/wechatpy/
这个是现在的，首页介绍 Markdown 完全没编译。

我自己改了个包名测试。
https://pypi.org/project/YMFK6DXQ34MCRDNYQBUJG2C3/
首页的介绍是正常的。

```
python setup.py sdist bdist_wheel
twine upload dist/* 
```
现在打包往 PyPI 上推的是不是有什么问题呀。

**Comment by messense** [comment]
发布一个新版本就会好了。

**Comment by messense** [comment]
https://github.com/jxtech/wechatpy/commit/57c5d007a3826f3948082ef7aae874fd27303215

**Comment by messense** [comment]
发布了新版还是有问题...不知道 PyPI 对 description 格式更新是怎么处理的。

**Comment by ldsink** [comment]
现在 wechatpy 上的，里面 `.dist-info` 里面会多带上一个 `DESCRIPTION.rst` 和 `metadata.json` 的文件。
Travis 打包比本地打包会有这种差异么。

**Comment by messense** [comment]
本地没有 `DESCRIPTION.rst`， 怀疑是 Travis CI 上的 wheel 包版本过低。

**Comment by messense** [comment]
Fixed
