### ISSUE TITLE
微信支付关于XML解析存在的安全问题

### ISSUE THREAD

**Issue by TonyMistark** [wechatpy/wechatpy#374]
## 问题描述 (Description)
微信支付商户，最近暴露的XML外部实体注入漏洞(XML External Entity Injection，简称 XXE)，该安全问题是由XML组件默认没有禁用外部实体引用导致，非微信支付系统存在漏洞。
https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=23_5

这个版本需要相应的改动吗？
微信官网给出的Python的修改方案
【Python】 
from lxml import etree
xmlData = etree.parse(xmlSource,etree.XMLParser(resolve_entities=False))
## 配置信息 (Environment/Version)

- Linux

- Python 3.6

- wechatpy 1.4.2

**Comment by TonyMistark** [comment]
厉害了，感恩。

**Comment by 5long** [comment]
额外指出一个事: xmltodict 从最新的 v0.11.0 版本开始, 才默认不去解析 external entities. 如果应用使用的是较旧的版本, 那么需要手动升级一下 xmltodict 才行.

**Comment by messense** [comment]
[两年前就关闭了](https://github.com/martinblech/xmltodict/pull/134)，一年前发的[新版](https://pypi.org/project/xmltodict/0.11.0/)，可以增加 `xmltodict>=0.11.0` 的最低版本要求。
