### ISSUE TITLE
上传图文素材接口的缩略图参数thumb_media_id是用哪个接口上传获取得到的？

### ISSUE THREAD

**Issue by wx5** [wechatpy/wechatpy#377]
## 使用client.material.add()接口上传图片返回的media_id好像是无效的。
求大神指点迷津。

**Comment by liriansu-opus** [comment]
是使用 `client.material.add` 接口，其中 `media_type` 指明为 `thumb` 即可。

可以参见 [微信官方的上传其它素材接口](https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1444738729)

**Comment by wx5** [comment]
楼上正解，谢谢指点。
