### ISSUE TITLE
缺少微信支付获取沙箱密钥接口

### ISSUE THREAD

**Issue by sillfox** [wechatpy/wechatpy#384]
根据微信支付的[文档](https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=23_1)，做沙箱测试之前要先通过接口获取沙箱密钥，看了wechatpy 的文档没有找到有这个接口的支持。

**Comment by messense** [comment]
https://github.com/jxtech/wechatpy/blob/f79e2a0f589dce2cd26467bc24bb9fa28b9a76da/wechatpy/pay/__init__.py#L73

传 `sandbox=True`

**Comment by sillfox** [comment]
原来是这个用法，不好意思，没有仔细看文档。可是这样的话，如果我想要在订单接口使用沙箱模式该怎么调用呢？
