### ISSUE TITLE
OAuth授权中的检验授权凭证（access_token）是否有效 中的URL错误

### ISSUE THREAD

**Issue by iblogc** [wechatpy/wechatpy#39]
`/wechatpy/oauth.py` 162行

`sns/oauth2/auth`应改为`sns/auth`

微信官方资料
![qq 20150416183422](https://cloud.githubusercontent.com/assets/3283023/7179130/4f8eb81e-e467-11e4-9a3a-85aba8e7a208.png)

**Comment by messense** [comment]
方便的话直接发个 Pull Requests 吧。

发自我的 iPhone
