### ISSUE TITLE
ArticlesReply 内容显示不完全

### ISSUE THREAD

**Issue by jezhang** [wechatpy/wechatpy#392]
## 问题描述 (Description)
使用ArticlesReply回复用户查询的关键字，最终形成的xml(reply.render())打印出来如下，但是在手机里只显示第一条记录([iPhone]查询结果)
`
<xml>
<MsgType><![CDATA[news]]></MsgType>
<ArticleCount>7</ArticleCount>
        <Articles><item>
            <Title><![CDATA[[iPhone]查询结果]]></Title>
            <Description><![CDATA[]]></Description>
            <PicUrl><![CDATA[https://img.xxx.com/wechat/search_banner.jpg]]></PicUrl>
            <Url><![CDATA[]]></Url>
            </item>
<item>
            <Title><![CDATA[斯泰克  iPhonex无线充电器 Qi无线快充头小米三星通用充电底座 支持苹果XS//XS Max/XR/8 Plus]]></Title>
            <Description><![CDATA[]]></Description>
            <PicUrl><![CDATA[https://qncdn.xxx.com/2018/10/23/11145452.jpg]]></PicUrl>
            <Url><![CDATA[https://www.xxx.com/youhui/detail/1959862/]]></Url>
            </item>
<item>
            <Title><![CDATA[Apple iPhone 6s Plus (A1699) 32G 深空灰 色 移动联通电信4G手机]]></Title>
            <Description><![CDATA[]]></Description>
            <PicUrl><![CDATA[https://qncdn.xxx.com/2018/10/23/11145364.jpg]]></PicUrl>
            <Url><![CDATA[https://www.xxx.com/youhui/detail/1959820/]]></Url>
            </item>
<item>
            <Title><![CDATA[UAG iPhone  Xs/X (5.8 英寸)  防摔手机壳/保护套 尊贵系列  亚黑+凑单品]]></Title>
            <Description><![CDATA[]]></Description>
            <PicUrl><![CDATA[https://qncdn.xxx.com/2018/10/22/11144494.jpg]]></PicUrl>
            <Url><![CDATA[https://www.xxx.com/youhui/detail/1959419/]]></Url>
            </item>
<item>
            <Title><![CDATA[途马TOURMAX 家用车载无线充手机支架 中控仪表台导航 多功能手机座 苹果iPhoneX/8三星安卓无线快充通用抖音]]></Title>
            <Description><![CDATA[]]></Description>
            <PicUrl><![CDATA[https://qncdn.xxx.com/2018/10/22/11143181.jpg]]></PicUrl>
            <Url><![CDATA[https://www.xxx.com/youhui/detail/1958845/]]></Url>
            </item>
<item>
            <Title><![CDATA[ZMI 紫米MFi认证苹果数据线1米编织线手机充电线支持iphone6s/7/7P/8/8P/X/XS/XR/X MAX/SE/ipad AL803黑色]]></Title>
            <Description><![CDATA[]]></Description>
            <PicUrl><![CDATA[https://qncdn.xxx.com/2018/10/22/11141664.jpg]]></PicUrl>
            <Url><![CDATA[https://www.xxx.com/youhui/detail/1958210/]]></Url>
            </item>
<item>
            <Title><![CDATA[摩斯维 苹果XS/iPhoneXs max手机壳]]></Title>
            <Description><![CDATA[]]></Description>
            <PicUrl><![CDATA[https://qncdn.xxx.com/2018/10/22/11135363.jpg]]></PicUrl>
            <Url><![CDATA[https://www.xxx.com/youhui/detail/1957017/]]></Url>
            </item></Articles>
<FromUserName><![CDATA[gh_15a69609a154]]></FromUserName>
<ToUserName><![CDATA[oriKI0j_DpB_DkSxb6HyUrq0CLUA]]></ToUserName>
<CreateTime>1540251816</CreateTime>
</xml>
`
## 配置信息 (Environment/Version)

- OS
CentOS 6.5

- Python
3.6 

- wechatpy
1.7.5

**Comment by messense** [comment]
https://mp.weixin.qq.com/cgi-bin/announce?action=getannouncement&announce_id=115383153198yAvN&version=&lang=zh_CN&token=

> 针对近期被动回复消息与客服消息接口能力使用不合理的情况，微信公众平台将对上述接口的多图文消息类型进行调整。10月12日起，被动回复消息与客服消息接口的图文消息类型中图文数目只能为一条，请知悉。

**Comment by jezhang** [comment]
thx

**Comment by jezhang** [comment]
> https://mp.weixin.qq.com/cgi-bin/announce?action=getannouncement&announce_id=115383153198yAvN&version=&lang=zh_CN&token=
> 
> > 针对近期被动回复消息与客服消息接口能力使用不合理的情况，微信公众平台将对上述接口的多图文消息类型进行调整。10月12日起，被动回复消息与客服消息接口的图文消息类型中图文数目只能为一条，请知悉。

thx
