### ISSUE TITLE
WeChatComponent中增加方法获取移动端链接快速授权

### ISSUE THREAD

**Issue by cougarwww** [wechatpy/wechatpy#393]
原方法有get_pre_auth_url用于网页扫码授权，现在微信文档增加了移动端的快速授权，这个地址可以直接微信里发给用户的，不验证来源地址

授权地址的接口不同，参数有一点区别：

    def get_pre_auth_url_m(self, redirect_uri):
        url = "https://mp.weixin.qq.com/safe/bindcomponent"
        redirect_uri = quote(redirect_uri, safe='')
        return "{0}?action=bindcomponent&auth_type=3&no_scan=0&component_appid={1}&pre_auth_code={2}&redirect_uri={3}".format(
                url, self.component_appid, self.create_preauthcode()['pre_auth_code'], redirect_uri
            )

微信文档地址：
https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1453779503&token=ca7b301f23f1acbbd9f6302eb3fce6b5c2a3027c&lang=zh_CN

**Comment by messense** [comment]
Pull request is welcome.
