### ISSUE TITLE
component_access_token和component_verify_ticket中key的名字加上component_appid

### ISSUE THREAD

**Issue by cougarwww** [wechatpy/wechatpy#394]
三方平台key的处理，直接写死了key名字
    @property
    def access_token(self):
        """ WeChat component access token """
        access_token = self.session.get('component_access_token')

    普通公众号的key处理
    def access_token_key(self):
        return '{0}_access_token'.format(self.appid)

**Comment by NullYing** [comment]
可以自己改改，提一下mr，不过一般都只用一个开放平台，多的话，放另外的redis db咯。
