### ISSUE TITLE
缓存使用Memcache出现问题

### ISSUE THREAD

**Issue by CodeAlmas** [wechatpy/wechatpy#395]
## 问题描述 (Description)
使用Memcache 报TypeError
因为Memcache的.get()获取不到 默认返回None , 没有第二个参数的.
问题:

    expires_at = self.session.get(expires_at_key, 0)

改善:

    expires_at = self.session.get(expires_at_key) or 0

## 配置信息 (Environment/Version)

- OS

Mac, Linux, Windows
- Python

Python: 3.6
- wechatpy

Version: 1.7.3
## 重现步骤 (Reproducing)
文件:client/api/jsapi.py
对应方法: get_jsapi_ticket

**Comment by ldsink** [comment]
Fixed by #562
