### ISSUE TITLE
建议，Readme里写清楚，支持的Python版本。

### ISSUE THREAD

**Issue by jikoy** [wechatpy/wechatpy#398]
现在支持Python3.7吗？一直签名验证失败中。

**Comment by messense** [comment]
支持。

https://github.com/jxtech/wechatpy/blob/90b509a1bc7271234e860ac0c5fdb816877d98b7/setup.py#L76

看看是不是你的配置有问题。

**Comment by jikoy** [comment]
是作都本人吗？大牛，佩服！！！

**Comment by jikoy** [comment]
是作者本人吗？大牛级人物，佩服！！！
