### ISSUE TITLE
签名验证一直失败，请大牛看下。

### ISSUE THREAD

**Issue by jikoy** [wechatpy/wechatpy#399]
Python 3.7，所有的包都装了。
使用Django2.x框架。
![qq 20181212102633](https://user-images.githubusercontent.com/10125432/49842997-98ad2180-fdf8-11e8-9d66-aaae75a61849.png)

![qq 20181212102954](https://user-images.githubusercontent.com/10125432/49843088-e3c73480-fdf8-11e8-97a6-3e8584605777.png)

我是从JAVA转过来的，请大牛不吝赐教！

**Comment by jikoy** [comment]
![qq 20181212103408](https://user-images.githubusercontent.com/10125432/49843246-78ca2d80-fdf9-11e8-872b-d61d7cd5e1cc.png)

**Comment by messense** [comment]
signature 不能为空，encrypt_type 按道理也不应该为空，你先试试明文回调模式，再试试加密模式。

**Comment by jikoy** [comment]
用企业号，默认都是密文的吧？只有公众号才有明文和密文之说。

**Comment by messense** [comment]
企业号参考这里的代码：https://github.com/jxtech/wechatpy/blob/master/examples/echo-enterprise/app.py

**Comment by messense** [comment]
不过企业号的相关代码很久没有更新了。

**Comment by jikoy** [comment]
![qq 20181212104556](https://user-images.githubusercontent.com/10125432/49843753-3275ce00-fdfb-11e8-9607-69f797fb3e75.png)

**Comment by jikoy** [comment]
![qq 20181212104740](https://user-images.githubusercontent.com/10125432/49843805-605b1280-fdfb-11e8-9d97-e4578eff5e06.png)

值都取到了。是我安装的方法有问题吗？
请给个链接，我想捐助一下这个项目50块。

**Comment by messense** [comment]
https://github.com/jxtech/wechatpy/blob/90b509a1bc7271234e860ac0c5fdb816877d98b7/wechatpy/enterprise/crypto.py#L22

应该是你 import 错了，企业号有专门的加解密代码。

**Comment by messense** [comment]
> 请给个链接，我想捐助一下这个项目50块。

![img_2195](https://user-images.githubusercontent.com/1556054/49843976-0f97e980-fdfc-11e8-8a75-b792c8f26a83.JPG)

Thanks!

**Comment by jikoy** [comment]
已向大牛捐赠50元。请查收！

**Comment by jikoy** [comment]
终于成功了！！！

**Comment by messense** [comment]
Great, 有其它问题再另开 issue.
