### ISSUE TITLE
AttributeError: 'WSGIRequest' object has no attribute 'data'

### ISSUE THREAD

**Issue by jikoy** [wechatpy/wechatpy#400]
![image](https://user-images.githubusercontent.com/10125432/49849528-f0f21c80-fe14-11e8-82b4-dd42f267d3e0.png)

我的环境是Python3.7

**Comment by jikoy** [comment]
现在是被动响应消息时，这个解密的错误。

**Comment by jikoy** [comment]
处理好了，应该改成这样才可以。

**Comment by jikoy** [comment]
elif request.method == 'POST':
        data = request.body
        try:
            msg = crypto.decrypt_message(
                data,
                signature,
                timestamp,
                nonce
            )

应该这样写，麻烦改一下代码。

**Comment by messense** [comment]
examples 里面的是 Flask 的项目。

**Comment by jikoy** [comment]
我用的是django。改改能用就行了。最主要是加解密两段
