### ISSUE TITLE
获取体验小程序的体验二维码get_qrcode() 

### ISSUE THREAD

**Issue by hp66722667** [wechatpy/wechatpy#402]
## 文档上给了返回数据的介绍，小白真没搞懂该如何处理，google了半天。我是直接
local = open('tmp.png', 'wb')
 local.write(result)
local.close()
打开文件进行存储的也报错
(Description)

## 配置信息 (Environment/Version)

- Linux 

- Python3.6

- wechatpy

**Comment by liriansu-opus** [comment]
假如是指 [get_wxa_code_unlimited](https://github.com/jxtech/wechatpy/blob/f79e2a0f589dce2cd26467bc24bb9fa28b9a76da/wechatpy/client/api/wxa.py#L48) 这个接口的话，返回的是 response 类型的数据。

可以用下面的（伪）代码来实现：

```
response = client.wxa.get_wxa_code_unlimited(scene='test', width=280)
response.raise_for_status()
with open('file.jpg', 'wb') as f:
    f.write(response.content)
```
