### ISSUE TITLE
上传图片时，关于file object问题，新人求解答。

### ISSUE THREAD

**Issue by zhangwen9229** [wechatpy/wechatpy#41]
``` python
weMedia = WeChatMedia(client)
fo = open("E:\hh.jpg", 'rb+')
try:
    imageJson = weMedia.upload('image', fo )
finally:
    pass
```

报错I/O operation on closed file

**Comment by messense** [comment]
试试下面这样行不行？

``` python
with open('E:\hh.jpg', 'rb') as f:
    media = client.media.upload('image', f)
```

（不需要手动初始化一个 WeChatMedia）
另外，没在 Windows 下用过，不知道是不是平台差异的问题。

**Comment by zhangwen9229** [comment]
（不需要手动初始化一个 WeChatMedia） 是什么意思,下面的代码对么？
client = WeChatClient('xxxxxx', 'xxxxxxxxxxxxxxxxxxxxx')
    weMedia = WeChatMedia(client)
    fo = open("E:\hh.jpg", 'rb+')
    try:
        imageJson = weMedia.upload('image', fo )
    finally:
        pass

**Comment by messense** [comment]
这样子：

``` python
from wechatpy import WeChatClient

client = WeChatClient('xxx', 'xxxxxxx')
with open('E:\hh.jpg', 'rb') as f:
    media = client.media.upload('image', f)
```

**Comment by messense** [comment]
参考测试用例里面的写法：
https://github.com/messense/wechatpy/blob/master/tests/test_client.py#L57

**Comment by zhangwen9229** [comment]
好，我看下。3q。 哈哈。Can I make friends with you?

**Comment by zhangwen9229** [comment]
media_file = six.StringIO('nothing')
图片，还是按我刚那种方式写，可以吧？？

**Comment by messense** [comment]
`media_file = six.StringIO('nothing')` 只是为了伪造一个 File-like Object，测试里面常用的方法

**Comment by zhangwen9229** [comment]
按照你上面的格式，上传成功了。非常感谢
