### ISSUE TITLE
Stop using PyCrypto

### ISSUE THREAD

**Issue by ldsink** [wechatpy/wechatpy#410]
## 问题描述 (Description)
* Pycrypto didn’t release any fix to that vulnerability and no commit was made to the project since Jun 20, 2014.
* PyCrypto has security problems.

![deepinscreenshot_select-area_20190107144402](https://user-images.githubusercontent.com/1937610/50753223-0cbdd680-128c-11e9-9a8d-4e862da9e561.png)

## 解决方法（Solution）

**Use [cryptography](https://github.com/pyca/cryptography) as default**

OR

[Stop using pycrypto. Use pycryptodome instead](https://blog.sqreen.io/stop-using-pycrypto-use-pycryptodome/)

**Comment by messense** [comment]
I am in favor of moving to use pycryptodome.
