### ISSUE TITLE
微信被动回复的非必须字段报UnboundLocalError

### ISSUE THREAD

**Issue by Xavier-Lam** [wechatpy/wechatpy#418]
## 问题描述 (Description)
对于微信被动回复的非必须字段(如video的title字段)render时报
> UnboundLocalError: local variable 'title' referenced before assignment

所有非必填字段应该都存在该问题,在拼tpl时应拿掉没有值的非必填字段

## 重现步骤 (Reproducing)
```
from wechatpy import replies
reply = replies.VideoReply(
    source="source",
    target="target",
    media_id="media_id",
    title="title"
)
reply.render()
```

**Comment by messense** [comment]
欢迎发 Pull Request 修正。
