### ISSUE TITLE
将企业号相关内容全部整理到企业微信相关

### ISSUE THREAD

**Issue by ldsink** [wechatpy/wechatpy#431]
## 问题描述 (Description)
微信企业号是早期的功能，相关文档地址 qydev.weixin.qq.com，最后更新于2016年。
微信现在大力推广企业微信，API地址 https://work.weixin.qq.com/api/doc# 。API接口继承自以前的微信企业号，并提供新的功能。

现在这个库的文档、注释，还是旧的微信企业号和企业微信混用。有两个问题：
1、名称相似但又不一样，容易混淆。
2、对应的接口来自于微信企业号，而不是新的企业微信，存在：接口参数更新、文档地址失效等问题。

我想整理一下代码和文档，将现在的微信企业号全部更新、整理到企业微信下面，包括
* 文档名称修改（“微信企业号” 到“企业微信” ）
* 相关链接更新（更新到 https://work.weixin.qq.com/api/doc# 开头的地址）
* 企业号 Issue 整理 #268 ，该关闭关闭，改修改修改。

大家意见如何？

**Comment by messense** [comment]
赞同👍

**Comment by liriansu-opus** [comment]
cool!

**Comment by ldsink** [comment]
#432 这个整理了现在的接口，更新了文档和链接。可以看一下。

对照企业微信API文档，当前未添加的 API。

- [ ] 外部联系人管理 crm
- [ ] 第三方应用开发 - 应用授权 sevice 内
- [ ] 互联企业消息 linkedcorp
- [ ] 企业微信打卡 checkin
- [ ] 企业微信审批 corp
- [ ] 公费电话 dial
- [ ] 企业支付
- [ ] 电子发票

按照这个列表，大伙再慢慢添加新的接口吧。

**Comment by messense** [comment]
为上面的列表单独创建了 issue.
