### ISSUE TITLE
企业微信外部联系人管理 crm 接口

### ISSUE THREAD

**Issue by messense** [wechatpy/wechatpy#437]

**Comment by beck0505** [comment]
在做了. 大概端午节附近 PR 吧. 

文档大概分以下4 大块: 
- [x] 基础接口

- [x] 客户联系工具接口

- [x] 离职管理

- [ ] ~~外部联系人变更回调, 这部分不需要做, 只需要在对应回调处理即可~~

**Comment by beck0505** [comment]
@messense 已经 pull-request. 
帮忙看下continuous-integration/appveyor/pr — AppVeyor build failed内的问题? 
这部分没太看懂 failed 原因. 
The Travis CI 已经 passed 了.

**Comment by messense** [comment]
rebase 一下

**Comment by beck0505** [comment]
已经 rebase.

**Comment by kxu1988** [comment]
在线文档没有关于此部分的介绍 http://docs.wechatpy.org/zh_CN/stable/

**Comment by messense** [comment]
@kxu1988 http://docs.wechatpy.org/zh_CN/master/work/client.html#id17

注意 v1 里面 work 叫 enterprise
