### ISSUE TITLE
企业微信审批 corp 接口

### ISSUE THREAD

**Issue by messense** [wechatpy/wechatpy#441]

**Comment by beck0505** [comment]
是OA数据接口内的部分么? 如果是, 这部分考虑贡献. 
目前问题是本库需要支持2.7及3.5,3.6, 3.7版本, 本机只安装了3.6. 不方便做兼容性测试.

**Comment by ldsink** [comment]
欢迎贡献代码。

本库涉及到Python版本相关的主要是加密解密相关部分，这部分使用现有的应该不会有兼容性问题。

**Comment by messense** [comment]
> 目前问题是本库需要支持2.7及3.5,3.6, 3.7版本, 本机只安装了3.6. 不方便做兼容性测试

不需要担心这个问题，需要保证有测试用例，发 PR 之后 CI 会测试这些版本，发现了问题再修就好了。

**Comment by huimingz** [comment]
是查询自建应用审批单当前状态的接口吗？如果是，那么以及做了

**Comment by messense** [comment]
@huimingz https://work.weixin.qq.com/api/doc/90000/90135/90264

应该是这个。

**Comment by huimingz** [comment]
> @huimingz https://work.weixin.qq.com/api/doc/90000/90135/90264
> 
> 应该是这个。

如果是这个的话，oa部分的内容差不多已经完成了。另外我之前的一次提交同样也添加了一个关于审批的接口https://work.weixin.qq.com/api/doc/90000/90135/90269#4.%E6%9F%A5%E8%AF%A2%E8%87%AA%E5%BB%BA%E5%BA%94%E7%94%A8%E5%AE%A1%E6%89%B9%E5%8D%95%E5%BD%93%E5%89%8D%E7%8A%B6%E6%80%81
