### ISSUE TITLE
统一下单接口字段receipt 未包含在调用参数中

### ISSUE THREAD

**Issue by Xavier-Lam** [wechatpy/wechatpy#453]
## 问题描述 (Description)
根据文档,统一下单接口包含字段receipt
https://pay.weixin.qq.com/wiki/doc/api/jsapi_sl.php?chapter=9_1

| 开发票入口开放标识 | receipt |
| --- | --- |

但统一下单接口中并不包含该字段
http://docs.wechatpy.org/zh_CN/master/pay.html#id5

建议在统一下单接口后追加`**kwargs`,并在`create`方法增加`data.update(kwargs)` 以避免后期微信支付追加字段造成的不兼容问题

**Comment by messense** [comment]
欢迎 PR.
