### ISSUE TITLE
第三方授权消息类型定义

### ISSUE THREAD

**Issue by cougarwww** [wechatpy/wechatpy#462]
这么定义继承关系，是有意为之还是笔误了？

这样收消息判断的时候 isinstance 就惨了，想收unauth的，其实是消息都收了。
if isinstance(message, ComponentUnauthorizedMessage):
    pass

@register_component_message('unauthorized')
class ComponentUnauthorizedMessage(BaseComponentMessage):

@register_component_message('authorized')
class ComponentAuthorizedMessage(ComponentUnauthorizedMessage):

@register_component_message('updateauthorized')
class ComponentUpdateauthorizedMessage(ComponentAuthorizedMessage):

**Comment by liriansu-opus** [comment]
看了一下，应该是~~图方便~~有意为之的。
目前暂时的解决办法是从子类往父类判断 `isinstance`。

更好的办法是改一下~
我待会提个 PR

**Comment by messense** [comment]
@LKI 可以试下发布个 patch 版本

https://github.com/jxtech/wechatpy/blob/master/.github/CONTRIBUTING.md#%E5%8F%91%E5%B8%83%E6%96%B0%E7%89%88%E6%9C%AC

**Comment by liriansu-opus** [comment]
@cougarwww @messense 
wechatpy 已经发布了 1.8.3 版本啦，这个问题在新版中也得到修复了~
