### ISSUE TITLE
统一下单订单生成时区转换问题

### ISSUE THREAD

**Issue by Xavier-Lam** [wechatpy/wechatpy#464]
## 问题描述 (Description)
对于统一下单接口,如果传入的时间time_start,time_expire 有时区,且时区非UTC+8时,会被当做UTC+8处理.
https://github.com/jxtech/wechatpy/blob/8d7f9f3ffb1b868d0337d1dc9247fbd15ce51ede/wechatpy/pay/api/order.py#L71

有时我们服务器时间是UTC时间,生成的带时区的datetime timezone也是UTC,建议在此处.astimezone(timezone('Asia/Shanghai')) 一下

**Comment by liriansu-opus** [comment]
求个微信支付的文档地址~
或者这个是微信支付的隐性实现，文档上没说的？

**Comment by Xavier-Lam** [comment]
API文档: https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=9_1

这个是这样的 微信这边的时间表示是`20190618190000`这种格式,时间要求是北京时间,wechatpy代码里直接.strftime 是在假定时区是Asia/Shanghai的情况下进行的,如果传入一个`datetime.datetime(2019, 6, 18, 11, 0, 0, tzinfo=tzwin('UTC'))`,会被直接格式化成`20190618110000`,实际上这个时间转换为UTC+8应该是`20190618190000`.

**Comment by liriansu-opus** [comment]
科学的，在微信支付的[时间规则](https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=4_2)里的确指出了时区应该是东八区，这个可以加一下。
