### ISSUE TITLE
关于发送模板消息的问题

### ISSUE THREAD

**Issue by zhangwen9229** [wechatpy/wechatpy#48]
下面的"TM00015" 是否要手动获取模板ID，请问在wechatpy API 中没有获取模板ID的封装接口吗？

一下代码返回错误码：Error code: 40037, message: invalid template_id
client.message.send_template(open_id, "TM00015", "http://127.0.0.1:5000/", "#FF0000",
                                          {
                                              "first": {
                                                  "value": u"恭喜您下单成功！",
                                                  "color": "#173177"
                                              },
                                              "orderMoneySum": {
                                                  "value": u"10000",
                                                  "color": "#173177"
                                              },
                                              "orderProductName": {
                                                  "value": u"这是商品名",
                                                  "color": "#173177"
                                              },
                                              "remark": {
                                                  "value": u"欢迎再次购买！",
                                                  "color": "#173177"
                                              }
                                          })

**Comment by messense** [comment]
之前微信没有开放这个接口，稍后有时间给加上。谢谢反馈。

http://mp.weixin.qq.com/wiki/17/304c1885ea66dbedf7dc170d84999a9d.html#.E8.8E.B7.E5.BE.97.E6.A8.A1.E6.9D.BFID

**Comment by zhangwen9229** [comment]
客气。  感谢回复。

**Comment by messense** [comment]
@zhangwen9229 v0.8.5 版本中包含了获取模板 ID 接口，已经发布到 PyPi.文档：
http://wechatpy.readthedocs.org/en/latest/client.html#wechatpy.client.api.WeChatTemplate.get
