### ISSUE TITLE
小程序统一服务消息

### ISSUE THREAD

**Issue by bluesky001** [wechatpy/wechatpy#481]
下发小程序和公众号统一的服务消息，是不是还没有这接口？

`POST https://api.weixin.qq.com/cgi-bin/message/wxopen/template/uniform_send?access_token=ACCESS_TOKEN`

**Comment by liriansu-opus** [comment]
已确认，目前还没实现这个接口。欢迎 PR

文档地址：https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/uniform-message/uniformMessage.send.html

**Comment by MidTin** [comment]
小程序模板下线后，统一服务消息接口也同时会失效，因此没什么必要再实现这个接口了
