### ISSUE TITLE
企业付款到零钱失败，需要拿原商户订单号进行重试，如何处理这种需求？

### ISSUE THREAD

**Issue by whkendny** [wechatpy/wechatpy#482]
企业付款到零钱失败，需要拿原商户订单号进行重试，如何处理这种需求？

**Comment by liriansu-opus** [comment]
这个我们是付款后抓一下 `wechatpy.exceptions.WeChatPayException`，然后根据[微信支付定义的错误码](https://pay.weixin.qq.com/wiki/doc/api/tools/mch_pay.php?chapter=14_2) 来重试（当然记得设最大重试时间）

商户订单号就是纯业务的订单号，用同单号是做幂等，防止重复打款。
