### ISSUE TITLE
构造wechat_client时，access_token_key 能否自定义？

### ISSUE THREAD

**Issue by lx1054331851** [wechatpy/wechatpy#484]
1. 因为有别的应用程序也在使用redis维护access_token，而原有的程序和wechatpy对于access_token_key的命名规则不一样。虽然可以使用CustomStorage来重写wechatpy的redisstorage的一部分命名规则，但是写在base.py里面的函数：
```python
@property
    def access_token_key(self):
        return '{0}_access_token'.format(self.appid)
```
则无法修改。

2. 另外有一个问题就是，wechatpy存入redis的access_token带有双引号，以字符串的形式存储数据，应该不需要特意在带上引号吧。这样在调用的时候会有问题。
```python
    def set(self, key, value, ttl=None):
        if value is None:
            return
        key = self.key_name(key)
        value = json.dumps(value)   # 这句话不知道是为了什么
        self.redis.set(key, value, ex=ttl)
```

**Comment by liriansu-opus** [comment]
关于1的命名规则，目前没有配置项支持自定义，建议是继承一个类来做自定义。
关于2的存储，应该是早期兼容留下的逻辑，建议也是继承一个类来做自定义……
