### ISSUE TITLE
微信服务号主动发送视频消息，内容详情的title， 和description中文乱码

### ISSUE THREAD

**Issue by kendny** [wechatpy/wechatpy#486]
## 问题描述 (Description)
点进去 title和description中文乱码

## 配置信息 (Environment/Version)
在安卓手机上看乱码
![中文乱码](https://user-images.githubusercontent.com/13364272/68380193-50be8800-018a-11ea-8c08-364c240b992b.jpeg)

- OS：15.1

- Python：3.6

- wechatpy： 1.8.3

**Comment by liriansu-opus** [comment]
这个看起来是发送图文消息的接口？理论上是好的。
可以提供一小段重现的代码吗？

**Comment by liriansu-opus** [comment]
我尝试发了一下，应该是正常的。

从截图看，可能是发送字符串的编码问题，就是 `b''.decode()` 这种，
可以从这个角度尝试修复一下。
