### ISSUE TITLE
小程序订阅消息相关接口

### ISSUE THREAD

**Issue by Xavier-Lam** [wechatpy/wechatpy#489]
## 问题描述 (Description)
根据微信的文档,小程序模板消息将在20年1月份下线,以订阅消息作为取代,似乎还没有相关接口

https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/subscribe-message/subscribeMessage.addTemplate.html

**Comment by heliang-whut** [comment]
Hi, 我实现了一个发送订阅消息的接口，也许可以解决你的问题，https://github.com/jxtech/wechatpy/pull/495
