### ISSUE TITLE
微信开放平台

### ISSUE THREAD

**Issue by iblogc** [wechatpy/wechatpy#50]
作者可以看看有没有可能转成新的方式

|  | 原先方式 | 新方式(登录授权) |
| --- | --- | --- |
| 公众号是否需要提供appid和appsecret | 需要 | 不需要 |
| 公众号是否需要配置服务器url和token | 需要 | 不需要 |
| 可接入几个第三方开发服务 | 1个 | 5个(消息与菜单权限集只能授权给一家) |

https://open.weixin.qq.com/cgi-bin/frame?t=home/wx_plugin_tmpl&lang=zh_CN
https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&lang=zh_CN

**Comment by messense** [comment]
有这个意向，但是这个微信开发平台只能企业申请吧？苦于没有测试账号。

**Comment by zhangwen9229** [comment]
我有企业账号。可以提供测试。邮箱私密给你吧，作者。 @messense

**Comment by iblogc** [comment]
@lazygunner :+1::+1::+1:

**Comment by messense** [comment]
@zhangwen9229 Thanks. 邮箱是用户 (at) icloud 。不过最近比较忙（毕设、答辩什么的），可能得过一段时间才能开始。

**Comment by zhangwen9229** [comment]
企业号：  衣助手   是否需要先关注。我也没怎么弄过。

**Comment by zhangwen9229** [comment]
@messense  你的邮箱 是不是 被github 屏蔽了 怎么是 “用户 (at) icloud”？

**Comment by messense** [comment]
@zhangwen9229 No. 我故意的（避免爬虫抓取邮箱发垃圾邮件......虽然不怎么有效）....... messense (at) icloud (dot) com，(at) 是 @ ，(dot) 是点。

**Comment by zhangwen9229** [comment]
@messense 已发送你邮箱，你查看下。收到，请回复。

**Comment by iblogc** [comment]
> 企业号： 衣助手 是否需要先关注。我也没怎么弄过。

@zhangwen9229 企业号只能企业内部人员才能关注，而且是不能搜索找到的

**Comment by zhangwen9229** [comment]
@korvin101 我将账号和密码发给 @messense 了,可是需要微信扫一下。绑定的是我的微信，这个咋办呢？ 绑定的微信可不能改其他人啊。

**Comment by zhangwen9229** [comment]
@korvin101 企业号，不是企业内部人，也可以关注吧？ @messense 有收到邮件吗？

**Comment by messense** [comment]
@zhangwen9229 邮件收到了。

不过我觉得你们理解错了我上面说的“企业”，不是企业号，是微信开放平台要求开发者认证，而这个开发者认证目前好像只能企业进行认证，个人做不了。

![image](https://cloud.githubusercontent.com/assets/1556054/7630057/f1d7984e-fa64-11e4-8a7e-d5838bc9de15.png)

@zhangwen9229 给的账号也登陆不上微信开放平台。

**Comment by iblogc** [comment]
@messense 
- 如果你说的企业号是这个平台的话[https://qy.weixin.qq.com/cgi-bin/loginpage](https://qy.weixin.qq.com/cgi-bin/loginpage)
  需要先在企业号管理后台添加A用户信息，然后A用户才能关注，不然就不能关注。
- 「微信开放平台」和这个企业号无关，是开放平台的「开发者资质认证」个人申请不出来，只能是企业或是组织团体才能申请，见下图
  ![Uploading QQ截图20150514181235.png…](http://i1.tietuku.com/81403598cc3a413d.png)
  ![Uploading QQ截图20150514181241.png…](http://i1.tietuku.com/0fae8980077c0b0d.png)

**Comment by iblogc** [comment]
@messense 
- 如果你说的企业号是这个平台的话[https://qy.weixin.qq.com/cgi-bin/loginpage](https://qy.weixin.qq.com/cgi-bin/loginpage)
  需要先在企业号管理后台添加A用户信息，然后A用户才能关注，不然就不能关注。
- 「微信开放平台」和这个企业号无关，是开放平台的「开发者资质认证」个人申请不出来，只能是企业或是组织团体才能申请，见下图
  ![Uploading QQ截图20150514181235.png…](http://i1.tietuku.com/81403598cc3a413d.png)
  ![Uploading QQ截图20150514181241.png…](http://i1.tietuku.com/0fae8980077c0b0d.png)

**Comment by zhangwen9229** [comment]
@messense 开放平台，我明天上去注册试试，我这边有朋友的企业证件。 之前我说的确实是企业号，可能我理解错了。^_^

**Comment by zhangwen9229** [comment]
![qq 20150514182225](https://cloud.githubusercontent.com/assets/5137377/7630246/c275946e-fa66-11e4-8be7-a3314bf46b59.png)

**Comment by iblogc** [comment]
@zhangwen9229 只有成员才能关注，我说的内部人员指的就是已经添加到企业号成员里的人，所以现在这个号只有**@message**能关注，就算把这个号发给其它人，其它人也关注不了

**Comment by zhangwen9229** [comment]
@korvin101 明白了。3q for your explanation。

**Comment by navcat** [comment]
代码中的  # NOQA 是啥意思？

**Comment by messense** [comment]
@navcat https://flake8.readthedocs.org/en/2.4.1/

lines that contain a `# noqa` comment at the end will not issue warnings.

**Comment by hunter007** [comment]
这块代码可以发布了。

**Comment by iblogc** [comment]
:+1:

**Comment by messense** [comment]
@hunter007 @korvin101 貌似还有“推送component_verify_ticket协议”和“推送取消授权通知”这块没做吧？

**Comment by hunter007** [comment]
这两个内容都是 Wechat server 向特定的 url 推送消息，但它的格式既不是 event，也不是 message。

目前我们的项目中是直接解析处理的。

**Comment by messense** [comment]
@hunter007 是这样的。但是应该可以提供一个方便的解析工具吧？否则这一块就不够完整了。

**Comment by hunter007** [comment]
可以在 conponent.py 中提供两个方法处理他们。他们接收请求体。

不过他们都需要解密。这个解密和公众号的加解密又有些不同。

我这边按官方提供的示例写了一个。

**Comment by messense** [comment]
@hunter007 可以，发个 PR 吧。

**Comment by hunter007** [comment]
或者提供一个 BaseComponentMessage 类，从MessageMetaClass继承。

**Comment by messense** [comment]
@hunter007 

https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419318482&lang=zh_CN

http://mp.weixin.qq.com/wiki/2/3478f69c0d0bbe8deb48d66a3111ff6e.html

这两个加解密方案没看出来区别啊？

**Comment by hunter007** [comment]
除了由原来的公众号的参数，被开放平台的参数替换了。还有什么区别吗？

加密过程是一样的吧？这个我没看。因为当时你说是一样的。

今天在ipython 下手动执行了一遍代码，可以了；但还没有在我们的项目里面使用。

要等下周了。

**Comment by messense** [comment]
@hunter007 没其他区别。下周你再验证一下吧，如果有测试数据，可以用测试数据写个测试用例，当然在不泄露你们的 secret key 之类的东西前提下。

**Comment by hunter007** [comment]
OK
