### ISSUE TITLE
最新版本在ubuntu上安装提示cffi版本冲突

### ISSUE THREAD

**Issue by sanren99999** [wechatpy/wechatpy#501]
Exception: Version mismatch: this is the 'cffi' package version 1.13.2, located in '/home/ubuntu/.local/lib/python3.6/site-packages/cffi/api.py'.  When we import the top-level '_cffi_backend' extension module, we get version 1.11.5, located in '/usr/lib/python3/dist-packages/_cffi_backend.cpython-36m-x86_64-linux-gnu.so'.  The two versions should be equal; check your installation.
[2020-01-11 10:57:38 +0800] [10933] [INFO] Worker exiting (pid: 10933)

**Comment by messense** [comment]
用 virtualenv，不建议在系统全局安装。

**Comment by sanren99999** [comment]
后来我发现，这个跟python版本还有关系，最后我升级了python版本（由3.6.8升级到了3.7.6），这个冲突就解决了

**Comment by messense** [comment]
可能是你以前在那个 Python 版本下安装的某个包依赖了 cffi
