### ISSUE TITLE
完全移除对 Python 2 的支持

### ISSUE THREAD

**Issue by ldsink** [wechatpy/wechatpy#504]
## 问题描述 (Description)

Python 2.7 尽管4月可能还会有一次安全更新发布，但是现在已经正式停止支持。

是否考虑升级一次大版本，从 `1.X.X` 跳到 `3.X.X`（以前讨论过 2.0 的想法，为避免混淆，大版本直接跳到 3），彻底移除 Python2 相关的兼容代码。

## 坏处
依旧使用 Python2.7 的用户可能无法使用之后的版本

## 好处

* 可以删掉大量兼容性代码
* 使用的一些第三方库不需要考虑 Python2 的兼容性

**Comment by messense** [comment]
LGTM, 不过可以晚一点，半年以后？

**Comment by king3200** [comment]
支持~~~

**Comment by leeyisoft** [comment]
支持3.0

**Comment by azurecn** [comment]
支持~~

**Comment by messense** [comment]
建了个 [v1](https://github.com/jxtech/wechatpy/tree/v1) 分支，我们可以先在 master 分支上渐渐移除 Python 2 的支持了。

**Comment by messense** [comment]
master 分支已经移除 Python 2 兼容，issue 先 close 掉，置顶至只支持 Python 3 的 wechatpy 新版本发布后。

**Comment by ldsink** [comment]
十一长假，发个 v3 大版本嘛。

**Comment by messense** [comment]
@ldsink 最近有点事没太多空哎，要发还是 v2 吧，v2 之前并没有实际落地的东西感觉不需要跳到 v3。

**Comment by messense** [comment]
v2.x alpha 版本可通过 `pip install -U --pre wechatpy` 安装。
