### ISSUE TITLE
消息加密解密

### ISSUE THREAD

**Issue by iblogc** [wechatpy/wechatpy#51]
看了下好像没看到消息加密解密的代码:smile:
https://mp.weixin.qq.com/wiki/0/61c3a8b9d50ac74f18bdf2e54ddfc4e0.html

**Comment by messense** [comment]
有的。。。

https://github.com/messense/wechatpy/tree/master/wechatpy/crypto

Example：

https://github.com/messense/wechatpy/tree/master/examples/echo-encrypted

**Comment by iblogc** [comment]
好吧，粗心了
