### ISSUE TITLE
没有看到回复消息的菜单消息类别--msgmenu

### ISSUE THREAD

**Issue by aiaiwuai** [wechatpy/wechatpy#515]
## 问题描述 (Description)
回复一个可点击的菜单，算是公众号不错的feature 但是好像wechatpy好像没有
## 配置信息 (Environment/Version)

- OS

- Python

- wechatpy

**Comment by messense** [comment]
欢迎 PR 增加此功能。

**Comment by NullYing** [comment]
https://github.com/jxtech/wechatpy/pull/518

实际上展示效果不好，这个功能还是有点垃圾
