### ISSUE TITLE
企业微信标签模块缺失部门ID

### ISSUE THREAD

**Issue by maobole** [wechatpy/wechatpy#517]
## 问题描述 (Description)
企业微信标签模块缺失部门ID，list接口返回为空，其他创建接口无相关参数

## 配置信息 (Environment/Version)

- OS

Mac
- Python

3.7
- wechatpy

1.8.6

**Comment by messense** [comment]
没有看懂，标签管理文档里面没有提到部门 ID？

https://work.weixin.qq.com/api/doc/90000/90135/90209
