### ISSUE TITLE
今天从 0.6.3 升级到 0.8 时发现 API 接口变了

### ISSUE THREAD

**Issue by cloverstd** [wechatpy/wechatpy#52]

**Comment by messense** [comment]
具体一点？

另外，wechatpy 项目目前还处于 Beta 阶段，一些 API 接口变更是会产生的。

**Comment by messense** [comment]
微信公众平台的接口也一直在更新，所以有些变更在所难免。Changelog 一直没怎么写，以后需要注意。谢谢提醒。

**Comment by cloverstd** [comment]
@messense 
0.6.3 `client.send_text_message`
0.8 `client.message.send_text`

是我自己的问题，我几个版本混着在用，有些旧的code没有及时更新

**Comment by messense** [comment]
@cloverstd 
这个变更是为了能更方便的扩展 API，也是挺久之前做的了。 #16

**Comment by cloverstd** [comment]
@messense
我是今天更新旧code依赖时发现的，很久之前的代码，新的都有用新的接口，今天更新后报错发现的

还是谢谢你的代码 :)

**Comment by messense** [comment]
@cloverstd 不用谢 :-) 有问题欢迎随时开 issue，也非常欢迎 Pull Request.
