### ISSUE TITLE
如何设置代理

### ISSUE THREAD

**Issue by wangcongxing** [wechatpy/wechatpy#520]
## 问题描述 (Description)
因项目发布在内网,需要配置代理才能和外网通讯, 在项目中没有找到设置代理的地方

## 配置信息 (Environment/Version)
proxies = {
      "https": "https://27.254.52.99:8080",
   }
client._http.proxies.update(proxies)
- OS

- Python

- wechatpy

**Comment by messense** [comment]
```python
proxies = {
    "http": "http://27.254.52.99:8080",
    "https": "http://27.254.52.99:8080",
}
client._http.proxies.update(proxies)
```
