### ISSUE TITLE
微信公众号发送永久素材

### ISSUE THREAD

**Issue by uptoheart** [wechatpy/wechatpy#522]
## 问题描述 (Description)
微信公众号的mdiea类型，只能发送图文，不能发送永久图文素材。这一点不太方便，麻烦新增一个这样的接口。谢谢啦

## 配置信息 (Environment/Version)

- OS
linux

- Python
3.6

- wechatpy
1.8.6

## 重现步骤 (Reproducing)
总是

**Comment by ldsink** [comment]
material 下提供永久素材的接口，media 主要是临时素材。

https://developers.weixin.qq.com/doc/offiaccount/Asset_Management/New_temporary_materials.html

#524
