### ISSUE TITLE
按照文档上标注的参数应该为 thumb_url，而代码中为 picurl/image

### ISSUE THREAD

**Issue by hylarucoder** [wechatpy/wechatpy#534]
https://github.com/jxtech/wechatpy/blob/b7d07a820cf13a79e29da3016ec876e39b7160f5/wechatpy/client/api/message.py#L238

在文档页中搜索 thumb_url 可得

https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/customer-message/customerServiceMessage.send.html#method-http

**Comment by messense** [comment]
cc @zephyrrr

**Comment by messense** [comment]
@twocucao 需要发布新版本不？

**Comment by hylarucoder** [comment]
@messense 可以，谢谢啦。

**Comment by hylarucoder** [comment]
@messense 可以，谢谢啦。

**Comment by messense** [comment]
@twocucao v1.8.13 发布了。
