### ISSUE TITLE
群发视频上传报错

### ISSUE THREAD

**Issue by lipengfei911** [wechatpy/wechatpy#54]
报错信息

```
SSLError: hostname 'file.api.weixin.qq.com' doesn't match either of 'game.weixin.qq.com', 'long.open.weixin.qq.com', 'open.weixin.qq.com', 'api.weixin.qq.com', 'a.weixin.qq.com', 'mp.weixinbridge.com', 'mp.weixin.qq.com'
```

调用此接口时出错
`https://file.api.weixin.qq.com/cgi-bin/media/uploadvideo?access_token=ACCESS_TOKEN`
好像是证书问题
http://cn.python-requests.org/en/latest/user/advanced.html#ssl
![qq 20150521164218](https://cloud.githubusercontent.com/assets/7742152/7744724/4310cef6-ffd8-11e4-96c0-47b5490a4210.png)

**Comment by messense** [comment]
谢谢反馈，稍后有时间看下。同时也非常欢迎 Pull Request.

发自我的 iPhone

**Comment by messense** [comment]
@lipengfei911 安装 develop 分支的代码测试下，分组删除的接口也有了。如果没有问题的话稍后发布一个新版本到 PyPi. :-)

``` bash
pip install https://github.com/messense/wechatpy/archive/develop.zip
```

**Comment by lipengfei911** [comment]
测试上传视频的可以了,but 群发视频报错4008类型错误,send_mass_video()方法里改类型video加mp就能发了
![image](https://cloud.githubusercontent.com/assets/7742152/7762316/5747c54a-0065-11e5-8383-c3d7f9933363.png)

**Comment by messense** [comment]
发个 Pull Request？

发自我的 iPhone

**Comment by lipengfei911** [comment]
已发,请查收,我再试试分组的
