### ISSUE TITLE
Use Poetry or Pipenv

### ISSUE THREAD

**Issue by messense** [wechatpy/wechatpy#545]

**Comment by messense** [comment]
Poetry 跟 cargo 比较像，特别是 lockfile，Pipenv 的 lockfile 是 JSON 格式有点🤢。

**Comment by ldsink** [comment]
我目前用的 pipenv，Lock 感觉有点慢。一些问题 github 上的 master 分支解决了，但是 pypi 上的版本有问题。最近一年多都没有发新的版本，但是项目组说还在开发，今年可能弄个大版本能解决问题。好处是现在在 Pypa 下面。

Poetry 目前用起来比 pipenv 舒服，项目本身也更活跃。缺点是不是官方的。

我们作为第三方包，选用哪个方案，lockfile 应该都不建议加到 git 中，因为具体单个项目才追踪 lockfile。不同版本 python、 不同的第三方依赖版本都不一样，追踪 lockfile 的变动没有意义。

可以等今年 pipenv 出新版本了再比较一下，最终决定。现在用哪个，打包还是得生成 requirements 文件，暂时不着急。

**Comment by messense** [comment]
@ldsink lockfile 可以比较方便地用来缓存 CI 上建的 virtualenv.

参考：https://github.com/laixintao/iredis/blob/9b8ee4772962a033471f36a93b0c3487c46fa51a/.github/workflows/test.yaml#L36

**Comment by liriansu-opus** [comment]
我个人偏好是 `pipenv`，虽然这鬼项目快两年没更新了，但毕竟是 psf 官方推的项目，而且按说三月会发个新版本。

lockfile 的话我觉得提到项目里是 ok 的，只要做好 setup.py 里面的依赖版本声明就没问题

- pipenv 2020 March release milestone: https://github.com/pypa/pipenv/milestone/7
- keep pipenv/setup.py in sync: https://github.com/pypa/pipenv/issues/1263
