### ISSUE TITLE
用户分组管理有新增了删除分组

### ISSUE THREAD

**Issue by lipengfei911** [wechatpy/wechatpy#55]
望有空再看下,加进项目里
我试过,一直删除失败 -1 系统繁忙

**Comment by messense** [comment]
@lipengfei911 话说这个接口有问题吗？

**Comment by lipengfei911** [comment]
有问题,我试过一直删除失败 -1 系统繁忙
你试过可以删除吗

**Comment by messense** [comment]
@lipengfei911 没有试。按道理说这样的错误应该不是 SDK 的问题，是微信公众平台的问题吧。

文档里说错误码 -1 为“系统繁忙，此时请开发者稍候再试”

http://mp.weixin.qq.com/wiki/17/fa4e1434e57290788bde25603fa2fcbd.html

**Comment by lipengfei911** [comment]
嗯,我想也是微信那边问题

**Comment by messense** [comment]
OK，v0.8.7 已经发布到 PyPi
