### ISSUE TITLE
企业微信模块的名称是work还是enterprise？

### ISSUE THREAD

**Issue by laona** [wechatpy/wechatpy#574]
## 问题描述 (Description)
请问企业微信模块的名称是work还是enterprise？从wechatpy官方文档、Code代码中看到的都是work，但是从release下载的1.8.11-1.8.13，以及从pip安装的1.8.13，都是enterprise，是我哪里没做对吗？谢谢！
## 配置信息 (Environment/Version)

- OS

Mac
- Python

3.6
- wechatpy

1.8.13

**Comment by messense** [comment]
1.x 是 `enterprise`，后面会改成 `work`(master 分支上已经是了），文档请看 1.x 的 https://wechatpy.readthedocs.io/zh_CN/stable/
