### ISSUE TITLE
客服接口url错误

### ISSUE THREAD

**Issue by lipengfei911** [wechatpy/wechatpy#58]
链接里多了/cgi-bin/
这是我打印的https://api.weixin.qq.com/cgi-bin/customservice/kfaccount/add
这是官方api里的:https://api.weixin.qq.com/customservice/kfaccount/add?access_token=ACCESS_TOKEN

添加更新删除上传头像试过都报错

**Comment by messense** [comment]
好的，客服接口有的有 cgi-bin 有的没有........真是操蛋

**Comment by messense** [comment]
试下 develop 分支的代码看看，改了好几个 url

``` bash
pip install https://github.com/messense/wechatpy/archive/develop.zip
```

**Comment by lipengfei911** [comment]
试过可以了,
but 删除有错,是GET方式,就一个参数
![qq 20150525141037](https://cloud.githubusercontent.com/assets/7742152/7792644/44925b06-02e8-11e5-93b4-added63ca781.png)

上传头像报错
代码:wechatapi.customservice.upload_headimg('11111@wiicome', open(str(path), "rb"))
![qq 20150525142434](https://cloud.githubusercontent.com/assets/7742152/7792965/ca7e966e-02eb-11e5-9c41-230ef3042de4.png)

**Comment by messense** [comment]
好的，这个接口微信不知道什么时候又更新了.......也没个公告....

**Comment by messense** [comment]
上传头像报错上传是成功还是不成功呢？

**Comment by lipengfei911** [comment]
不成功

**Comment by messense** [comment]
![image](https://cloud.githubusercontent.com/assets/1556054/7793172/a7c13440-02ed-11e5-8db9-6543fed9d2f5.png)
把地址改成 https 试下

**Comment by lipengfei911** [comment]
https 还是报一样的错

**Comment by messense** [comment]
试试在 `wechatpy.client.base.py` 46 行和 47 行之间打印下 `res.text` 看下

**Comment by lipengfei911** [comment]
{
    "errcode": invalid kf_account,
    "errmsg": "invalid kf_account"
}
打印如上
这客服刚建的,绝对有啊
{"kf_account":"11111@wiicome","kf_nick":"22222","kf_id":"1020","kf_headimgurl":""},
试了好几遍,换个客服号,都这样,
难道又是微信那边问题?

**Comment by messense** [comment]
@lipengfei911 这个接口返回的 JSON 数据格式都不对啊，肯定微信那边有些问题。

**Comment by lipengfei911** [comment]
坑了,那这就先放着了,没头像算了

**Comment by messense** [comment]
去 http://mp.weixin.qq.com/qa/home/index.html 反馈下试试？我现在没有账号能登录进去。
