### ISSUE TITLE
请教下关于ComponentOAuth里fetch_access_token的调用问题

### ISSUE THREAD

**Issue by BadReese** [wechatpy/wechatpy#586]
## 问题描述 (Description)
您好，这是个很方便的库，感谢！
目前有个不太清楚的问题想请教。
我们做的是第三方开放平台代公众号开发，在做代公众号用户授权登陆的时候遇到了问题。
一般来说，在用户点击同意授权登陆的时候我们会拿到一个code，用这个code去换取用户的openId信息
![image](https://user-images.githubusercontent.com/18170860/86537192-baf91980-bf1f-11ea-8c7e-2433ef886d0b.png)
请问这个时候调用fetch_access_token(code)是否进行了access_token的刷新？
我在测试中发现，两次返回的access_token是不一样的，是否说明token刷新了呢？还是说纯粹是因为code不一样导致的返回access_token不同？

我们今天遭遇了调用接口上限问题，导致平台无法使用，所以很关注这个情况，非常希望得到抽空的回答，谢谢您。
另外，如果不是该问题，不知是否可以指点下还有其他什么情况会导致第三方开放平台的接口调用达到上限？
## 配置信息 (Environment/Version)

- OS
Linux
- Python
3.6
- wechatpy
1.8.13

**Comment by liriansu-opus** [comment]
> 请问这个时候调用fetch_access_token(code)是否进行了access_token的刷新？
> 我在测试中发现，两次返回的access_token是不一样的，是否说明token刷新了呢？
> 还是说纯粹是因为code不一样导致的返回access_token不同？

每次调用这个接口会主动刷新微信的 token，
所以返回的 access token 不同。

> 我们今天遭遇了调用接口上限问题，导致平台无法使用。

这个你们可以看后台的接口上限，
有分具体接口的次数。
按照给出的描述，猜测刷新 access token 过于频繁，
这个就需要手动用 Redis 或者别的方法进行授权码的缓存，
参见 [wechatpy 文档中](http://docs.wechatpy.org/zh_CN/stable/component.html#id2)的这一段：

> 授权码和刷新码有效期为7200秒，需要在失效之前更新授权码。
> 由于各个项目的差异性和复杂性，本项目并未实现更新逻辑，需要调用者根据项目来自己实现。

希望能帮到你

**Comment by BadReese** [comment]
您好，非常感谢回复。

我在初始化WeChatComponent的时候，开启了auto_retry
![image](https://user-images.githubusercontent.com/18170860/86549135-5b2b5e80-bf71-11ea-8121-675cd33ca175.png)
这个开关的作用不是在使用access_token的时候，发现过期就自动刷新吗？
我有开启redis做缓存
![image](https://user-images.githubusercontent.com/18170860/86549273-bcebc880-bf71-11ea-8845-22ff991a8c47.png)


另外，我搜索了一下发现，access_token似乎有2种，一种是通过用户授权的code来换取的，这种方式好像没有调用上限。
而直接获取的access_token是可以获取公众号下所有用户信息的，所以有调用上限。

**Comment by liriansu-opus** [comment]
没错，auto_retry 是自动刷新，假如你们服务请求并发低的话是没问题的；
但假如并发高，会出现多个进程都在刷 token 的 race condition 的情况。
高并发的服务推荐把 auto retry 关掉，自己实现刷新机制。

后面你的理解是完全正确的，
微信的设定里 access token 是有两种：
- 微信用户授权，使用前端传入 code 换取 token
- 微信平台授权，使用 refresh token 换取 access token

**Comment by BadReese** [comment]
好的，非常谢谢，那应该是并发量导致的token刷新超限。

我想我可以通过定时任务来刷新access_token，但不知道我缓存的token如何提供给wechatpy获取呢？
如果可以，劳驾提供一个DEMO指点一二，谢谢。

**Comment by liriansu-opus** [comment]
简单提供一个我负责的服务例子：

- 使用 celery 配置一个每 55 分钟跑一次的定时任务（这样只要不是连续三次刷新失败，都能确保可用）
- 然后 celery 任务的配置很简单，手动调用 `fetch_access_token` 即可：

```
@app.task()
def refresh_token():
    WeChatClient(appid=my_appid, secret=my_secret, session=redis.Redis(), auto_retry=False).fetch_access_token()
```

**Comment by BadReese** [comment]
好主意，
这里虽然设置auto_retry=False，但是在fetch_access_token 后，wechatpy都会自动缓存下access_token吗？
是以什么样的方式缓存呢？

**Comment by liriansu-opus** [comment]
> 虽然设置auto_retry=False，但是在fetch_access_token 后，wechatpy都会自动缓存下access_token吗？

是的

> 是以什么样的方式缓存呢？

传入了一个 `session=redis.Redis()`，所以 token 会存在 redis 里

**Comment by BadReese** [comment]
他的键名是wechatpy:component_access_token吗？

**Comment by BadReese** [comment]
接下来只要看运行情况就知道了，非常感谢，帮了大忙。
