### ISSUE TITLE
menu语法错误

### ISSUE THREAD

**Issue by hikingyu** [wechatpy/wechatpy#589]
wechatpy/client/api/menu.py第26行
return self._get("menu/get")
在https://developers.weixin.qq.com/doc/offiaccount/Custom_Menus/Querying_Custom_Menus.html中为：
get_current_selfmenu_info
即改成：
return self._get("get_current_selfmenu_info")
解决菜单获取返回码：4008 不合法的消息类型

**Comment by liriansu-opus** [comment]
这是两个接口，需要查询菜单则用 `client.menu.get()`，你提到的自定义菜单需要用 `client.menu.get_menu_info()`
