### ISSUE TITLE
客服删除还有错

### ISSUE THREAD

**Issue by lipengfei911** [wechatpy/wechatpy#59]
删除接口最后访问的链接为:
https://api.weixin.qq.com/customservice/kfaccount/del?access_token=xxxxxxxxx&kf_account=aa11111%5C%40wiicome

requests自动编码符号@为%40,然后就报错了:无效客服账号(invalid kf_account)

**Comment by messense** [comment]
然而 http URL 就应该编码啊

**Comment by lipengfei911** [comment]
然而微信要@符合，咋办

**Comment by messense** [comment]
稍后想想办法

发自我的 iPhone

**Comment by messense** [comment]
试试 develop 分支的新代码

**Comment by lipengfei911** [comment]
好的，多谢，明天我试试

**Comment by lipengfei911** [comment]
ok 删除可以用了
