### ISSUE TITLE
get_payment_data bug

### ISSUE THREAD

**Issue by jeremyzzzhj** [wechatpy/wechatpy#593]
## 问题描述 (Description)
代码错误，xml 解析出来后 data 是  
{
   'xml': {
    'appid': '.xxxxx'
    ...
   }
}
 这边 直接data['appid'] 报错，应该是data['xml']['appid'], 其他参数也一样

## 配置信息 (Environment/Version)

- OS

- Python

- wechatpy

**Comment by messense** [comment]
Thanks!
