### ISSUE TITLE
能否把 xmltodict 和  optionaldict 整合进去

### ISSUE THREAD

**Issue by yreme** [wechatpy/wechatpy#594]
wechatpy依赖  optionaldict.py  和  xmltodict.py 两个文件

能否直接将这两个文件整合进去？因为项目容器调用wechatpy，每个容器每次都要独立再打包此两个文件，非常麻烦。

两位文件见附件
[归档.zip](https://github.com/wechatpy/wechatpy/files/4987025/default.zip)

**Comment by messense** [comment]
不懂你是怎么弄的，pip/pipenv/poetry 等这些 Python 包管理工具安装 wechatpy 的话，这些依赖都是自动安装的。

**Comment by huimingz** [comment]
pip安装的时候这些依赖是自动安装的

**Comment by yreme** [comment]
谢谢这么快回复！

我用的是serverless  微服务 https://cloud.tencent.com/document/product/583/11061
由于腾讯云的python环境不支持wechatpy的模块，需要自己上传layer文件。

导致我在使用wechatpy的时候，还需要另外分别上传
- optionaldict
-  xmltodict
  
这两个模块

**Comment by messense** [comment]
@yreme 参考：https://cloud.tencent.com/document/product/583/39780#python-.E8.BF.90.E8.A1.8C.E6.97.B6

**Comment by yreme** [comment]
上面的我知道。。太麻烦了
