### ISSUE TITLE
PYPI上安装的 wechatpy 缺少 wechatpy.work 模块

### ISSUE THREAD

**Issue by zzbslayer** [wechatpy/wechatpy#596]
## 问题描述 (Description)
```sh
pip install wechatpy
```
通过 pip 安装的 wechatpy 缺少 wechatpy.work 模块，无法进行企业微信api的开发。
```sh
pip install https://github.com/wechatpy/wechatpy/archive/master.zip
```
直接安装 github master 版本是没有问题的。

## 配置信息 (Environment/Version)

- OS
Windows10 & CentOS 7

- Python
3.7 & 3.8

- wechatpy
1.8.13 not works
 github master works

## 重现步骤 (Reproducing)
```sh
pip install wechatpy
python
>>> import wechatpy # This works
>>> from wechatpy.work.crypto import WeChatCrypto # raise error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'wechatpy.work'
```

**Comment by huimingz** [comment]
master做了重命名修改#538，目前发布的没有，所以通过pip安装的应该通过`from wechatpy. enterprise  import xxx`进行调用。考虑到之后的兼容问题，建议可以用下面的方式
```python
try:
    from wechatpy.enterprise import xxx
except ImportError:
    from wechatpy.work import xxx
```

**Comment by messense** [comment]
issue 关闭，先置顶提高可见性。
