### ISSUE TITLE
主动发消息文本消息报错

### ISSUE THREAD

**Issue by zhaopei0418** [wechatpy/wechatpy#597]
## 问题描述 (Description)
调用主动发送消息时报下面错误
 File "send_message.py", line 24, in send_message
    res = client.message.send_text(openid, 'text')
TypeError: send_text() missing 1 required positional argument: 'content'

代码如下：
```
client = WeChatClient(appid, secret)
    for openid in openids:
        print("openid=", openid)
        res = client.message.send_text(openid, 'text')
        print("res=", res)

```
## 配置信息 (Environment/Version)

- OS

Mac
- Python

3.7.6
- wechatpy

1.8.13

## 重现步骤 (Reproducing)
开始发送消息就会报错

**Comment by messense** [comment]
贴的代码不全，是公众号还是企业号？

**Comment by zhaopei0418** [comment]
公众号, 代码不全,看看还需要哪些信息

**Comment by messense** [comment]
See https://wechatpy.readthedocs.io/zh_CN/stable/enterprise/client.html#wechatpy.enterprise.client.api.WeChatMessage.send

**Comment by zhaopei0418** [comment]
是公众号,你发的是企业号的,

**Comment by messense** [comment]
你自己说企业号的。。。贴一下你的 wechatpy 相关的 imports...

**Comment by zhaopei0418** [comment]
from datetime import datetime
from http.server import HTTPServer, BaseHTTPRequestHandler
from apscheduler.schedulers.background import BackgroundScheduler
from loguru import logger
from DBUtils.PooledDB import PooledDB
from wechatpy.enterprise import WeChatClient
import json
import requests
import os
import cx_Oracle
import traceback

**Comment by messense** [comment]
`from wechatpy import WeChatClient`

你用的是企业号的 client 来搞公众号的功能。
