### ISSUE TITLE
过时的接口实现

### ISSUE THREAD

**Issue by letsky** [wechatpy/wechatpy#609]
## 功能描述
此处接口已经被更改为了获取访问用户身份接口
https://github.com/wechatpy/wechatpy/blob/dc3bcf5ed5d3af04415cf25a55ae81b15c0c08e8/wechatpy/work/client/api/user.py#L169
## 相关资料
https://work.weixin.qq.com/api/doc/90000/90135/91437

**Comment by huimingz** [comment]
应该不影响使用吧

**Comment by letsky** [comment]
这个接口在oauth下已经实现了
https://github.com/wechatpy/wechatpy/blob/dc3bcf5ed5d3af04415cf25a55ae81b15c0c08e8/wechatpy/work/client/api/oauth.py#L45

此处代码应该去掉

**Comment by huimingz** [comment]
确实这两个地方都实现了相同的接口，`user`模块下的还多了个不必要的`agentid`参数。

考虑到可能已经有用户在使用`user`下的`get_info`接口，建议在该方法文档中添加deprecated注释，至于哪个版本移除，需要讨论

**Comment by messense** [comment]
2.0 版本中移除。
