### ISSUE TITLE
关于客服创建会话  503 Server Error: Service Unavailable

### ISSUE THREAD

**Issue by zhangwen9229** [wechatpy/wechatpy#61]
![Uploading 20150604115341.png…]()

customservice.create_session(self.msg.source, u"test@test", text=None)

**Comment by messense** [comment]
5xx 的错误码一般都是服务器出错，应该是微信服务器的问题吧。

发自我的 iPhone

**Comment by zhangwen9229** [comment]
那我下午再试试。   就是再点击菜单时，触发 创建会话。 就这样报错了。  截图暂时传不上。

**Comment by zhangwen9229** [comment]
![20150604115341](https://cloud.githubusercontent.com/assets/5137377/7977113/566e81f0-0ab9-11e5-9e82-575d2f4a205d.png)

**Comment by zhangwen9229** [comment]
@messense 手动创建会话不行
return (TransferCustomerServiceReply(message=self.msg)).render()
直接转发多客服  可以
但用户点击自定义菜单【人工服务】  后端 直接 创建会话，不可行吗？

**Comment by messense** [comment]
@zhangwen9229 你用的是哪个版本的 wechatpy？我看截图里面地址有些问题，不应该有 /cgi-bin/ 的。

**Comment by zhangwen9229** [comment]
上午升级了 最新版本    0.8.7 @messense 
class WeChatClient(BaseWeChatClient):
    """
    微信 API 操作类
    通过这个类可以操作微信 API，发送主动消息、群发消息和创建自定义菜单等。
    """

```
API_BASE_URL = 'https://api.weixin.qq.com/cgi-bin/'
```

**Comment by messense** [comment]
@zhangwen9229 Sorry. 上次多客服相关接口的修改还没发布新版本，你安装 develop 分支的代码试下。

**Comment by zhangwen9229** [comment]
@messense https://github.com/messense/wechatpy/blob/master/wechatpy/client/api/customservice.py#L137
你查看下这块， 代码上写的地址应该是没错。   我已安装develop代码，等会再测试试试

**Comment by zhangwen9229** [comment]
@messense  我刚测试完，  develop代码可以使用
customservice.create_session(self.msg.source, u"test@test", text=None)

**Comment by messense** [comment]
@zhangwen9229 Thanks. 发布了新版本到 PyPi 了。

**Comment by zhangwen9229** [comment]
@messense You are welcome. 我等会升级下最新版本

**Comment by zhangwen9229** [comment]
@messense 创建会话测试正常。  可以关闭了。
