### ISSUE TITLE
退款接口 提交成功 但是报参数错误

### ISSUE THREAD

**Issue by CyJaySong** [wechatpy/wechatpy#610]
## 配置信息 (Environment/Version)

- OS

Linux

- Python

3.6

- wechatpy

1.8.14

## 重现步骤 (Reproducing)
退款接口

**Comment by messense** [comment]
请提供更详细的报错信息。

**Comment by CyJaySong** [comment]
`"/www/.pyenv/versions/3.6.12/envs/ServerVenv/lib/python3.6/site-packages/wechatpy/pay/api/refund.py", line 43, in apply return self.post('secapi/pay/refund', data=data) File "/www/.pyenv/versions/3.6.12/envs/ServerVenv/lib/python3.6/site-packages/wechatpy/pay/base.py", line 18, in post return self._client.post(url, **kwargs) File "/www/.pyenv/versions/3.6.12/envs/ServerVenv/lib/python3.6/site-packages/wechatpy/pay/__init.py", line 191, in post **kwargs File "/www/.pyenv/versions/3.6.12/envs/ServerVenv/lib/python3.6/site-packages/wechatpy/pay/init.py", line 148, in request return self.handle_result(res) File "/www/.pyenv/versions/3.6.12/envs/ServerVenv/lib/python3.6/site-packages/wechatpy/pay/__init.py", line 176, in _handle_result response=res wechatpy.exceptions.WeChatPayException: Error code: FAIL, message: 0参数格式错误. Pay Error code: None, message: None
`

**Comment by messense** [comment]
先检查下你传入的参数有没有问题的吧，可以贴一下相关的代码。

**Comment by liriansu-opus** [comment]
这个按官方说法，是检查退款的金额啊什么的参数是否正确，比如退款需要为正整数

参考：https://developers.weixin.qq.com/community/pay/doc/0002c6b8e68750624478eaf0a56c00

**Comment by CyJaySong** [comment]
确实是退款金额的问题。
