### ISSUE TITLE
能添加上微信公众号实名验证接口吗？

### ISSUE THREAD

**Issue by djzbj** [wechatpy/wechatpy#612]
这个模块弄的很好，作者辛苦了！

目前要求实名认证的场景很多，能添加上微信公众号实名验证接口吗？

**Comment by messense** [comment]
麻烦贴一下文档地址。

**Comment by djzbj** [comment]
https://pay.weixin.qq.com/wiki/doc/api/realnameauth.php?chapter=60_1&index=2

**Comment by djzbj** [comment]
> 麻烦贴一下文档地址。

文档地址是：
https://pay.weixin.qq.com/wiki/doc/api/realnameauth.php?chapter=60_1&index=2

麻烦看看

**Comment by djzbj** [comment]
谢谢，辛苦了，我更新下。

**Comment by messense** [comment]
```bash
pip install -U --pre wechatpy
```
