### ISSUE TITLE
问询一下后续命名规范、类型标注和async支持的规划

### ISSUE THREAD

**Issue by liqiongyu** [wechatpy/wechatpy#615]
对，如题：
问询一下后续命名规范、类型标注和async支持的规划

今天有往master提交一个request，往后应该会继续跟进提交。
想问下主要开发团队，后续对命名规范、类型标注和async支持的规划是怎样的。
比如：企业微信中，department的id，有各种命名： id, partyid, department_id等。
其中类型标注也相对较少。

是否有相应的计划，在这块如果要提交代码，需要往哪个开发分支提交。

**Comment by messense** [comment]
async 有兴趣可以看看 https://github.com/wechatpy/wechatpy/issues/580

**Comment by messense** [comment]
1. 命名规范现在是尽量和微信官方文档保持一致
2. 类型标注，新增接口都需要，老的慢慢加，CI 已经加上了 mypy check
3. 往 master 分支提交代码
