### ISSUE TITLE
群发预览接口增加了对指定微信号发送预览

### ISSUE THREAD

**Issue by lipengfei911** [wechatpy/wechatpy#63]
有空再加上呗

**Comment by messense** [comment]
@lipengfei911 你是指新增的 `towxname` 参数是吧？需要设计下接口参数，暂时觉得可以通过正则匹配 openid，匹配不对的就当做 `towxname` 处理，否则当做 `touser` 处理。

**Comment by lipengfei911** [comment]
嗯 这个towxname 参数,正则可以,或者可以再加个可选参数?

**Comment by messense** [comment]
目前已经很多可选参数了，再增加可选参数是不是不太友好。而且 group_or_users 参数是位置参数，再增加可选参数这个位置参数还得给值，不太好。

**Comment by lipengfei911** [comment]
也对,那就正则

**Comment by lipengfei911** [comment]
@messense 区分微信号跟openid的正则写好了吗,

```
openid里有"-" "_" 微信号只有 "_" ,其他匹配"^[a-zA-Z_\d]+$"都一样
```

**Comment by messense** [comment]
@lipengfei911 我有个疑问是 openid 的长度，貌似目前都是 28 位？

**Comment by lipengfei911** [comment]
我数了下,好像是,都28

**Comment by messense** [comment]
@lipengfei911  develop 分支的代码，你试一下吧

**Comment by lipengfei911** [comment]
试过了可以,多谢!
