### ISSUE TITLE
自动回复中文时乱码

### ISSUE THREAD

**Issue by dante-is-shipping** [wechatpy/wechatpy#646]
## 问题描述 (Description)
在关注时配置关注回复时，
```python
 WELCOME_MSG = '欢迎关注公众号'
reply = create_reply(self.WELCOME_MSG, msg)
return reply.render()
```
![image](https://user-images.githubusercontent.com/24785694/118809510-4df33600-b8dd-11eb-9ceb-9b8f0fdae52c.png)

## 配置信息 (Environment/Version)

- OS

- Python

- wechatpy

**Comment by liriansu-opus** [comment]
这个看起来是环境的编码导致的，你可以试一下本地 print 一下字符串的值；

换用 python3, 或者在文件顶部加入 `# -*- coding: utf-8 -*-` 可以解决问题

可以参考: https://blog.csdn.net/joyfixing/article/details/79971667
