### ISSUE TITLE
继承了 WeChatClient，但是 __new__ 并没有正确的执行

### ISSUE THREAD

**Issue by cloverstd** [wechatpy/wechatpy#65]
Hi,
我继承了 WeChatClient，重写了 **init**，access_token，fetch_access_token 这三个方法，但是我发现 BaseWeChatClient 的 **new** 并没有正确的执行，导致 api._client 为 None

我尝试在继承的类中手动执行 WeChatClient.**new** 也没有用

**Comment by messense** [comment]
@cloverstd WeChatClient 的设计并没有考虑再次继承的问题，因为其初衷是用于直接使用的。Anyway, 如果你有解决方案，欢迎 PR.

**Comment by cloverstd** [comment]
@messense 
我是单独将 access_token 通过中间件存到了 redis 里，因为在其他地方也有用到 access_token
公众号不像企业号，access_token 可以重复获取得到相同的 access_token，所以如果在直接使用 WeChatClient 时，当 access_token 过期，WeChatClient 会再自动获取
我想替代 WeChatClient 来手动维护 access_token 

暂时想到的方法是使用 WeChatClient.**init** 中的 access_token 参数来解决

**Comment by messense** [comment]
@cloverstd 嗯，我了解你的意图了。你说的 **init** 是一种方法，当然也可以 dirty 一点设置 _access_token。有更好的设计方案么？欢迎探讨。

**Comment by cloverstd** [comment]
我觉得可以将 access_token 的获取分离开来，或者说提供类似一套 session 的机制，提供 RedisBackend、MemBackend 等主流的 cache 的 store，并且暴露出接口，可以自定义 backend 来储存 access_token

[微信的文档](http://mp.weixin.qq.com/wiki/11/0e4b294685f817b95cbed85ba5e82b8f.html)中也提到了，

> 如果第三方不使用中控服务器，而是选择各个业务逻辑点各自去刷新access_token，那么就可能会产生冲突，导致服务不稳定。

**Comment by messense** [comment]
@cloverstd 嗯，这可以是 wechatpy 在 1.0 版本之前需要实现的机制。最初的考虑是不想仅仅为了一个 access_token 的获取/更新来实现一套 session 机制，如果现在要做的话，需要一个详细的设计，并且尽可能不影响不使用该机制的调用方式也就是在不提供 session backend 的默认情况的实现需要和目前一致。

**Comment by cloverstd** [comment]
@messense 
向下兼容是必须的:D

我觉得可以重写 WeChatClient.fetch_access_token 和 BaseWeChatClient._handle_result 中处理 access_token 的地方，然后提供一个类似于 flask 扩展形式的 init_app 的方式来初始化 access_token backend
或者暴露一个 access_token middleware 给用户自己处理 access_token

**Comment by iblogc** [comment]
这个继承了 WeChatClient问题是不是还没有解决

**Comment by messense** [comment]
@korvin101 是的。上面也说了 WeChatClient 的设计并没有考虑再次继承的问题，因为其初衷是用于直接使用的。目前也没有时间去处理这个问题，anyway，欢迎 PR 提供解决方案。

**Comment by iblogc** [comment]
@messense 能力还太菜，新版代码已经看不懂了:joy:

**Comment by cloverstd** [comment]
@korvin101 
因为 WeChatClient.__init__ 有一个 access_token 的参数，所以我用了比较 dirty 的解决方法

``` python
def wechat_client():
    token = _redis.get(config.TOKEN_NAME)
    return WeChatClient(config.APP_ID, config.APP_SECRET, token)

```

**Comment by iblogc** [comment]
@cloverstd `fetch_access_token`方法怎么办，在老版上，我重写了`fetch_access_token`方法，新版本上不行了

**Comment by cloverstd** [comment]
@korvin101 
我跟你一样，我是升级时发现继承不了了

对于 __new__ 我不能执行，我也没想到怎么解决，所以只能使用 dirty 的方法

不过如果提供了 token session（#65） 的话，会方便一些。

**Comment by iblogc** [comment]
@cloverstd 是不是这一个https://github.com/jxtech/wechatpy/pull/67

**Comment by cloverstd** [comment]
@korvin101 是 #67 
刚刚写错了

**Comment by messense** [comment]
@cloverstd 
@korvin101 
试试 develop 分支的代码看是不是修复了这个问题。

**Comment by cloverstd** [comment]
@messense 
👍，可以工作

**Comment by iblogc** [comment]
@messense 可以:+1:
