### ISSUE TITLE
【新手求解】在使用群发图文接口时Postman总是出现 Server Error (500)！

### ISSUE THREAD

**Issue by kosuo** [wechatpy/wechatpy#651]
## 问题描述 (Description)
【新手求解】在使用群发图文接口时Postman总是出现 Server Error (500)！不知道要调整哪里？要怎么处理！

## 配置信息 (Environment/Version)

- Linux Centos 7

- wechatpy 1.8.15

## 重现步骤 (Reproducing)
`print("-------获得接口权限------")
wx_client = WechatBase().get_wx_client()
print(wx_client) # 以获得

print("-------开始群发消息------")
res = wx_client.message.send_mass_article(group_or_users=None, media_id="_hu5K-odsoXMMm7q2ywLyCt4yiJWCgPkN1OMTUw", is_to_all=True)
 print(res)

data = json.dumps(res, cls=DjangoJSONEncoder)
return HttpResponse(data, content_type="application/json")`

**Comment by messense** [comment]
报错的 traceback 有吗？

**Comment by kosuo** [comment]
我也觉得奇怪没有，直接就是 500错误 没有任何返回 json错误信息！  PS：通过获取素材列表就能正常的返回json数据

**Comment by kosuo** [comment]
> 报错的回溯有吗？

我觉得没有，直接500错误没有任何返回json错误信息：通过获取素材也就是正常的返回json数据！

**Comment by kosuo** [comment]
> 报错的 traceback 有吗？

*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 31119)
spawned uWSGI worker 1 (pid: 4691, cores: 2)
spawned uWSGI worker 2 (pid: 4694, cores: 2)
spawned uWSGI worker 3 (pid: 4695, cores: 2)
Python auto-reloader enabled
spawned uWSGI worker 4 (pid: 4698, cores: 2)
-------获得接口权限------
<wechatpy.client.WeChatClient object at 0x7f604f7dc1f0>
-------开始群发消息------

**Comment by messense** [comment]
你可以试试加上 try...except 在 except 里面自己打印下 traceback.

**Comment by kosuo** [comment]
> 你可以试试加上 try...except 在 except 里面自己打印下 traceback.

spawned uWSGI worker 4 (pid: 4844, cores: 2)
-------获得接口权限------
<wechatpy.client.WeChatClient object at 0x7fdf372161f0>
-------开始群发消息------
Traceback (most recent call last):
  File "/home/www/wechat/views.py", line 324, in get_all_material
    res = wx_client.message.send_mass_article(group_or_users=None, media_id="_hu5K-odsoXMMm7q2ywLyCt4yiJWCgPkN1OMTUw", is_to_all=True)
  File "/home/venv/lib/python3.8/site-packages/wechatpy/client/api/message.py", line 549, in send_mass_article
    return self._send_mass_message(
  File "/home/venv/lib/python3.8/site-packages/wechatpy/client/api/message.py", line 346, in _send_mass_message
    return self._post(
  File "/home/venv/lib/python3.8/site-packages/wechatpy/client/api/base.py", line 19, in _post
    return self._client.post(url, **kwargs)
  File "/home/venv/lib/python3.8/site-packages/wechatpy/client/base.py", line 182, in post
    return self._request(
  File "/home/venv/lib/python3.8/site-packages/wechatpy/client/base.py", line 101, in _request
    return self._handle_result(
  File "/home/venv/lib/python3.8/site-packages/wechatpy/client/base.py", line 158, in _handle_result
    raise WeChatClientException(
wechatpy.exceptions.WeChatClientException: Error code: -1, message: system error rid: 60e54213-00e3b1b7-1541cd

**Comment by kosuo** [comment]
> 你可以试试加上 try...except 在 except 里面自己打印下 traceback.

求助啊  大神.... 卡在这了 不知道要怎么处理？

**Comment by messense** [comment]
https://docs.python.org/zh-cn/3/tutorial/errors.html

**Comment by kosuo** [comment]
> https://docs.python.org/zh-cn/3/tutorial/errors.html

`    try:
        res = wx_client.message.send_mass_article(group_or_users="ocP002-DtiQa8vB__ThGyp8jHaxU", media_id="_hu5K-odsoXMMm7q2ywLyCt4yiJWCgPkN1OMTUw", is_to_all=True, preview=True)
        print(res)
    except:
        traceback.print_exc()

    return HttpResponse("ok")`

**uwsgi 网关：**
raise WeChatClientException(
wechatpy.exceptions.WeChatClientException: Error code: -1, message: system error rid: 60e55549-1edf7cc0-486b90a2
code不存在

**最后返回了个 code不存在？ 这个是否是SDK内部的错误？还是我业务逻辑的问题？**

**Comment by messense** [comment]
system error 建议咨询微信官方。

**Comment by kosuo** [comment]
好的 谢谢！那我提交微信官方问下

> system error 建议咨询微信官方。

好的 谢谢！那我提交微信官方问下

**Comment by kosuo** [comment]
> system error 建议咨询微信官方。

测试了几个主动发消息的接口 都是抛出这个错误，微信也没回复，加了几个群 说是SDK的问题，好难啊！感觉无任何头绪

` raise WeChatClientException(
wechatpy.exceptions.WeChatClientException: Error code: -1, message: system error rid: 60e5850c-4acc4749-1e0443dd`

**Comment by liriansu-opus** [comment]
-1 的话一般是微信内部 error。按我的经验，这个报错一般都是偶发不是必现的。

假如能 100% 复现的话，肯定就是微信对某些传参或者返回没处理好，然后微信方挂了。
可以去微信开发者社区提问: https://developers.weixin.qq.com/community/homepage

**Comment by kosuo** [comment]
> -1 的话一般是微信内部 error。按我的经验，这个报错一般都是偶发不是必现的。
> 
> 假如能 100% 复现的话，肯定就是微信对某些传参或者返回没处理好，然后微信方挂了。
> 可以去微信开发者社区提问: https://developers.weixin.qq.com/community/homepage

嗯 确实像你说的这样 现在就正常了！
