### ISSUE TITLE
关于微信公众号表情包信息接受

### ISSUE THREAD

**Issue by jing-bi** [wechatpy/wechatpy#656]
## 问题描述 (Description)

当用户发送微信表情包时,parse后的信息type = text, content = [Unsupported Message].

如何正确接受表情包信息?

**Comment by messense** [comment]
没有看到表情包消息相关文档？https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Receiving_standard_messages.html

可以贴一下 parse 之前的 XML 数据。

**Comment by sasaju** [comment]
> 没有看到表情包消息相关文档？https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Receiving_standard_messages.html
>  可以贴一下 parse 之前的 XML 数据。

```
<xml>
  <ToUserName><![CDATA[gh_xxxxx]]></ToUserName>
  <FromUserName><![CDATA[asdfasdvaosdifjas]]></FromUserName>
  <CreateTime>1650418273</CreateTime>
  <MsgType><![CDATA[text]]></MsgType>
  <Content><![CDATA[【收到不支持的消息类型，暂无法显示】]]></Content>
  <MsgId>45613213213</MsgId>
</xml>
```

**Comment by NullYing** [comment]
这是微信不发给你

**Comment by sasaju** [comment]
上个月我在研究这个问题，非要接收的话也不是完全没有办法。
目前我只想到了一种办法，我不知道这是微信后台的设计失误还是有意为之，表情包消息在接口上无法获取，但是在微信公众号后台却可以随意查看。
所以，我们可以通过爬虫模拟登陆（最好是二维码登陆，免去安全验证的问题），拿着cookie，访问该用户发送的信息，就可以拿到表情包了。整个过程十分繁琐，即使是用python也相当麻烦。
然而这个方法有个严重的缺陷，我们可以注意到这个登陆的cookie只有几天（好像是两天）的有效期，所以几天后需要重新登陆扫码，我目前的解决方法是每隔40小时发送给自己一次登陆二维码的邮件，然后扫描登陆。
有别的解决方案的话，欢迎探讨
