### ISSUE TITLE
增加 企业微信群相关功能接口

### ISSUE THREAD

**Issue by LiuJinGH** [wechatpy/wechatpy#664]
## 功能描述

增加 企业微信群相关功能接口

我在1.8.15版本中，发现还没有企业微信群配置相关的接口，希望能尽快添加上去。

## 相关资料

https://work.weixin.qq.com/api/doc/90000/90135/92119

**Comment by tssujt** [comment]
Implemented in #614 #644 #671

**Comment by tssujt** [comment]
可以 close @messense
