### ISSUE TITLE
传入access_token,报错'WeChatClient' object has no attribute 'corp_id'

### ISSUE THREAD

**Issue by IKkSssDendi** [wechatpy/wechatpy#670]
## 配置信息 (Environment/Version)

- OS
Windows 10

- Python
3.6

- wechatpy
1.8.15

## 重现步骤 (Reproducing)
client = WeChatClient(corp_id=CORP_ID, secret=SECRET,access_token=ACCESS_TOKEN)

问题出在：父类(BaseWeChatClient)中access_token_key的调用早于类(WeChatClient)中corp_id的赋值。
这个问题在过去的已经关闭的Issue #483 中有提及，且在 [修复企业微信初始化传入 access_token 报错](https://github.com/wechatpy/wechatpy/commit/0007e6106e29ebc10c0cddb55c5383d117d98a18)有修复，但是现在该部分代码是在这个问题修复之前的版本

**Comment by messense** [comment]
Fixed in v1.8.18.
