### ISSUE TITLE
新接口:批量获取用户基本信息

### ISSUE THREAD

**Issue by iblogc** [wechatpy/wechatpy#68]
[批量获取用户基本信息](http://mp.weixin.qq.com/wiki/14/bb5031008f1494a59c6f71fa0f319c66.html#.E6.89.B9.E9.87.8F.E8.8E.B7.E5.8F.96.E7.94.A8.E6.88.B7.E5.9F.BA.E6.9C.AC.E4.BF.A1.E6.81.AF)

**Comment by messense** [comment]
Thanks. 同时欢迎 PR 提供实现代码。:-)
