### ISSUE TITLE
是否应该 reraise requests.RequestException 为 WeChatClientException

### ISSUE THREAD

**Issue by messense** [wechatpy/wechatpy#70]
目前的设计，在调用 `WeChatClient` 的相关接口时，不会去捕获 `requests.RequestException`，而是使用了 `raise_for_status` 方法在 API status_code 为非 2xx 的情况下自动 raise `requests.RequestException`.

https://github.com/jxtech/wechatpy/blob/master/wechatpy/client/base.py#L63

如此导致在调用接口时，不仅要捕获 `WeChatClientException` 还需要考虑捕获 `requests.RequestException`，增加了调用者的负担。

可能的设计是将 `requests.RequestException` 捕获并 reraise 为 `WeChatClientException`，并对 `WeChatClientException` 增加 `request` 和 `response` 属性。参考类似实现：

https://github.com/jxtech/teambition-api/blob/master/teambition/client.py#L137

**Comment by cloverstd** [comment]
需要
应该让使用者专注于 SDK 层，而不用去处理底层的 HTTP 请求
