### ISSUE TITLE
关于永久图文素材接口即将下线的通知

### ISSUE THREAD

**Issue by caryyu** [wechatpy/wechatpy#714]
因图文素材已升级为草稿箱，公众平台将于2022年2月28日下线[新增永久图文素材接口](https://developers.weixin.qq.com/doc/offiaccount/Asset_Management/Adding_Permanent_Assets.html)和[修改永久图文素材接口](https://developers.weixin.qq.com/doc/offiaccount/Asset_Management/Editing_Permanent_Rich_Media_Assets.html)。届时，开发者将无法通过接口新增和修改永久图文素材。已经生成的永久图文素材仍可以访问、获取和删除，但无法修改。请开发者尽快调整接口，使用草稿箱（[草稿接口文档](https://developers.weixin.qq.com/doc/offiaccount/Draft_Box/Add_draft.html)）和内容发布接口（[发布能力接口文档](https://developers.weixin.qq.com/doc/offiaccount/Publish/Publish.html)）生成并获取文章链接。

---

我从 wechatpy 素材管理文档部分没有看到禁用或过时标注，我测试该通知中的新增永久图文素材确实表示无法继续使用了；希望 wechatpy 后续可以支持变更后的接口。

**Comment by ldsink** [comment]
我看接口还在，docs 部分有更新。微信是内部发送消息提示下线这两个接口。

现在已经无法调用了，代码层面我先提个 PR 去掉不能用的代码吧。

**Comment by caryyu** [comment]
@ldsink  目前只测试了 `2.0.0.alpha22` 的 `add_drafts` 接口，参数不用改变可以正常工作；由于我项目只用到这一个接口，其它接口暂时没有测试，我想其它的问题应该也不大，非常感谢，我先关闭该 Issue 了。
