### ISSUE TITLE
微信客户端无法渲染换行符\n

### ISSUE THREAD

**Issue by sailor0913** [wechatpy/wechatpy#744]
## 问题描述 (Description)
想在文本回复中加入换行符\n，实现换行。但是微信客户端会照原样输出"\n"不会换行。

- OS

Windows 
- Python

3.10
- wechatpy

1.8.18
## 重现步骤 (Reproducing)
```python
    if msg.content == "测试":
        articles = "测试\n123"
        reply = create_reply(articles, msg)
        return reply.render()
```
期望输出：
```
测试  
123  
```

实际输出：
```
测试\n123
```

**Comment by Athrun59** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by sailor0913** [comment]
经过测试，以下方法均不行：
```
'测试' + '\n' + '123'
"测试\r\n123"
```

**Comment by sailor0913** [comment]
已自行解决，不是wechatpy的问题。
原因是使用的fastapi，其默认返回的信息是json格式，导致微信返回的消息无法渲染\n
解决：使用HTMLResponse或指定media_type="application/xml"

```python
# 两种方式均可
return HTMLResponse(reply.render())
return Response(content=reply.render(), media_type="application/xml")
```

**Comment by laoutiao** [comment]
这位哥完美解决问题👍
