### ISSUE TITLE
请问有 商家转账到零钱 的api吗？

### ISSUE THREAD

**Issue by aricyu** [wechatpy/wechatpy#747]
请问有这个api吗？
[商家转账到零钱](https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter4_3_1.shtml)

**Comment by Athrun59** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
