### ISSUE TITLE
批量获取审批单号 filter 参数问题

### ISSUE THREAD

**Issue by jayng1127** [wechatpy/wechatpy#761]
## 问题描述 (Description)
官方文档参数为 filters。当前请求参数为filter.
## 配置信息 (Environment/Version)

- OS

Windows
- Python

3.8
- wechatpy

1.8.18
## 重现步骤 (Reproducing)
OA文件中的get_approval_info方法，请求参数为filter.

**Comment by Athrun59** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
