### ISSUE TITLE
企业微信客服部分接口没有？

### ISSUE THREAD

**Issue by jellyfrank** [wechatpy/wechatpy#765]
## 功能描述

没看到有企业微信客服相关的文档和代码呢？

**Comment by Athrun59** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by NullYing** [comment]
https://github.com/wechatpy/wechatpy/blob/master/wechatpy/work/client/api/kf.py

**Comment by Athrun59** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
