### ISSUE TITLE
js sdk access token问题

### ISSUE THREAD

**Issue by habout632** [wechatpy/wechatpy#88]
不知道是不是我没看懂还是什么 我发现get_ticket 没用到access token? 这样会不会出问题呀

**Comment by messense** [comment]
Nope. 不会有问题的。get_ticket 最终会 delegate 给 WeChatClient 调用 API，WeChatClient 会把 access_token 处理好的。

See https://github.com/jxtech/wechatpy/blob/master/wechatpy/client/base.py#L77
