### ISSUE TITLE
js sdk  更新

### ISSUE THREAD

**Issue by habout632** [wechatpy/wechatpy#89]
)
    ret_dict = {
        'noncestr': noncestr,
        'timestamp': timestamp,
        'url': url,
        'signature': signature,
    }
    return JsonResponse(ret_dict)

noncestr 应为nonceStr

**Comment by messense** [comment]
实际上这里是无所谓的，只是传给前端而已，前端用的是 `nonceStr`. See

https://github.com/jxtech/wechatpy/blob/master/examples/wxjs/main/templates/index.html#L17
