### ISSUE TITLE
iPhone微信jsapi支付出错

### ISSUE THREAD

**Issue by lipengfei911** [wechatpy/wechatpy#93]
wechatpy/wechatpy/pay/api/jsapi.py
第41行'timeStamp': timestamp or int(time.time()),
iphone手机js支付报错,安卓手机可以支付
需修改str(int(time.time())), iphone就可以了
作者麻烦你自己改下吧

**Comment by messense** [comment]
Will publish a new release later.

**Comment by messense** [comment]
v1.1.1 released.
