### ISSUE TITLE
寻求上传语音文件的示例

### ISSUE THREAD

**Issue by openpython** [wechatpy/wechatpy#98]
如何上传语音文件？采用下面的代码始终返回错误。
full_path='/var/www/abc.com/media/test.amr'
media.upload("voice", open(full_path,"rb"))
错误提示：
wechatpy.exceptions.WeChatClientException: Error code: 41005, message: media data missing hint: [Nuz4vA0667ent3]

另外，media.upload是增加临时素材吧？

**Comment by messense** [comment]
media.upload 是增加临时素材，这个问题我稍后有时间调试一下，谢谢反馈！

**Comment by messense** [comment]
我用测试号试了一下并没有出错。

``` python
from wechatpy import WeChatClient

client = WeChatClient('wxd7aa56e2c7b1f4f1', '2817b66a1d5829847196cf2f96ab2816')
f = open('/Users/messense/Desktop/test.amr', 'rb')
client.media.upload('voice', f)
f.close()
```

upload 的返回是：

> {u'created_at': 1446876673,
>  u'media_id': u'R7aPOMzave_yMzXrvCveteZwJWyFG3TS6sEP0jWSZtNLCHnibMuNeenHHZgbCtbx',
>  u'type': u'voice'}

test.amr 是我在这里 http://www.lnpan.com/htmls/format/id/7.html 随便下载的一个声音文件。

**Comment by openpython** [comment]
我是通过开放平台代公众号调用接口 API操作的，amr文件在微信公众平台测试无问题。
wechat_client=WeChatComponentClient(authorizer_appid,wechat_component, authorizer_access_token,authorizer_refresh_token)
media=WeChatMedia(wechat_client)
full_path='/var/www/abc.com/media/test.amr'
media.upload("voice", open(full_path,"rb"))

另外代公众号调用接口的有些bug，等会我整理单帖出来吧。

**Comment by messense** [comment]
开放平台代公众号调用接口的 `WeChatComponentClient` 的区别其实仅仅在于 access_token 获取的方法不一样，其它的调用方式都是一样的，直接 wechat_client.media.upload 就可以，不需要手动去使用 `WeChatMedia` 的。
