### ISSUE TITLE
目前使用中发现一些bug

### ISSUE THREAD

**Issue by openpython** [wechatpy/wechatpy#99]
我的环境是flask+mysql+redis(redis-py)，wechatpy版本1.1.1，主要使用代公众号调用接口，目前测试发现如下问题：
使用redis session get和set都会出问题，解决办法是在代码外添加key：

``` python
ticket=wechat_component.get_component_verify_ticket(request.data, msg_signature, timestamp, nonce)
        if ticket:
            redis_store.set("wechatpy:component_verify_ticket",ticket.verify_ticket)
```

redisstorage.py 代码修改：
get方法 `return json.loads(to_text(value))` 改为 `return to_text(value)`
set方法 `self.redis.set(key, value, ex=ttl)` 改为 `self.redis.set(key, value, ex=ttl)` 并注释掉 `value = json.dumps(value)`

http://wechatpy.readthedocs.org/zh_CN/latest/component.html 文档中的方法不存在，get_client只有一个参数。

``` python
client = component.get_client(appid, refresh_token, access_token)
menu_info = client.menu.get()
```

我是通过以下代码获取到client的：

``` python
wechat_client=WeChatComponentClient(authorizer_appid,wechat_component, authorizer_access_token,authorizer_refresh_token)
```

但是这个client与wechatpy.client.WeChatClient似乎不一样，现在测试获取设置currentmenu没问题，

```
menus=wechat_client.menu.get_menu_info()
```

上传素材文件无效：

``` python
f=open(full_path,"rb")
result=wechat_client.media.upload("voice",f)
```

**Comment by messense** [comment]
1. Redis 版本？
2. 目前 ReadTheDocs 构建有些问题，上面的文档不是最新的，待解决。
3. component 相关的接口是 @hunter007 贡献的，有问题可以请教他，因为 component 这块我也没实际去用过。
4. 这个问题需要进一步分析，你可以再 upload 的时候断点进去看看 requests 发出去的请求有没有问题。

**Comment by openpython** [comment]
Redis server version 2.2.12
redis-py 2.10.3，文档：http://redis-py.readthedocs.org/en/latest/index.html?highlight=set#redis.StrictRedis.set
我正在逐步测试每个api方法，遇到问题整理后再提交吧。
以前用过几个框架，这个是功能方法最全面的一个，稳定后应该可以作为微信api-python版的最佳框架了。

**Comment by messense** [comment]
你对 RedisStorage 提出的修改问题在于，RedisStorage 不仅仅可以用来存 access_token 之类的字符串型数据，也可以存数字、字典、列表等，所以使用了 json.dumps/loads 来编码/解码存在 Redis 中的数据。

component 的文档我刚刚看了一下确实有些问题，需要修复错误的说明。这个要麻烦一下 @hunter007 了。

因为我和其他贡献者所用到的 API 并不能全面包括目前支持的 API，难免会有些问题存在。谢谢反馈这些问题，社区问题反馈和代码贡献在这个项目的发展过程中起了很大的推动作用。

**Comment by hunter007** [comment]
两位，感谢提出建议。目前第三方平台接口和描述确实没有同步更新。我马上修改一下。
在此也说明一下这些 API 的使用方法：
1. 获取`WeChatComponent`对象的方法：直接实例化`wechatpy.component.WeChatComponent`即可。实例化需要三个参数：`component_app_id`、`component_app_secret`和 `session 实例`。前两个是必须的，第三个 session 是可选的，默认使用`wechatpy.session.memorystorage.MemoryStorage`。当你需要和其他框架结合使用时，只要符合`wechatpy.session.SessionStorage`接口就可以实例化后传入。
2. 获取`WeChatComponentClient`对象的方法：`WeChatComponentClient` 和 `WeChatClient`略微有点不同。在进行第三方平台开发的时候，应该使用`WeChatComponentClient`。两者获取授权码的方式不同，造成两者不能合并。为了调用者更简单地使用，在进行第三方平台开发的时候，应该通过`WeChatComponent`对象获取公众号的 client 对象。这时候也有两种情况：
   
   一）公众号刚刚授权成功时获取 client 对象
   二）公众号授权成功以后时获取 client 对象

对于（一），授权成功共信息中有authorization_code，通过 component. get_client_by(authorization_code)即可获取到公众号 client；对于（二），通过 component. get_client(authorizer_appid)即可获取到公众号 client。
获取之后的client，在使用上和 `WeChatClient`对象没有区别。

还有两个问题需要注意的地方：
1. 你的应用里肯定有接收`component_verify_ticket`的地方，你应该将`component_verify_ticket`放入component对象使用的 session 能访问到的地方。对于外部 session，或者使用同一个 session对象，或者使用相同配置的不同实例；对于默认的情况，你要确保所有操作在同一个线程内，因为MemoryStorage不是多线程安全的；
2. 公众号 client的授权码有效期是7200秒。在有效期内必须使用刷新码来更新这个授权码。鉴于各种项目非常不同，这块逻辑没有在本项目中实现，需要调用者根据项目来自己实现。在时效之前，只要调用 client. fetch_access_token()即可刷新，所以这个逻辑很简单。

你的代码：

```
ticket=wechat_component.get_component_verify_ticket(request.data, msg_signature, timestamp, nonce)
 if ticket:
            redis_store.set("wechatpy:component_verify_ticket",ticket.verify_ticket)
```

返回值是一个ComponentVerifyTicketMessage消息，不能直接放入 redis 中，不然 component 是不能理解的。你需要把ticket. verify_ticket放入 redis 中才对。

最后说一下我的项目中如何使用的。
1. 项目使用 redis 作为缓存。在某个 url 上接收component_verify_ticket，用 redis 对象 set 600秒。key 为 ComponentVerifyTicketMessage对象的 type，即component_verify_ticket。
2. 直接实例化WeChatComponent：

```
component = WeChatComponent(
        settings.COMPONENT_APP_ID,
        settings.COMPONENT_APP_SECRET,
        session=caches['wechat']
)
```

`caches['wechat']`是 django 中的 caches 封装，背后是 redis 的线程池。
3. 公众号授权成功时，使用`component.get_client_by(authorization_code)`。这是 wechatpy 做了两件事：
    A. 返回的公众号 client 包含了 component 对象，并使用 component 的 session 作为自己的 session；
    B. 将自己的授权码和刷新码用 session缓存起来，时间是7200秒。
4. 接下来就可以正常使用各个 API 了。

源代码中确实有些方法命名不恰当，文档也没有更新，说明也不够详细。我今天会进行更新。
请多加关注本项目。

**Comment by hunter007** [comment]
@openpython ，bug 已经修复，请按照新代码的文档说明使用。
@messense，这次修改不能兼容旧版本，请打包一个新版本。

**Comment by messense** [comment]
稍后会发布一个新版本。

发自我的 iPhone

**Comment by messense** [comment]
@openpython 
@hunter007 

新版本 1.2.0 已经发布到 PyPi.

**Comment by openpython** [comment]
已更到1.2版本，正在测试功能，发现使用redis作为session时，还是会出现参数错误，如下：

```
 wechat_component.cache_component_verify_ticket(request.data, msg_signature, timestamp, nonce)
  File "/usr/local/lib/python2.7/dist-packages/wechatpy/component.py", line 424, in cache_component_verify_ticket
    self.session.set(o.type, o.verify_ticket, 600)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 1055, in set
    return self.execute_command('SET', *pieces)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 565, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 577, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 574, in read_response
    raise response
redis.exceptions.ResponseError: wrong number of arguments for 'set' command

```

## 我项目里使用的 redis-py 2.10.3，文档：http://redis-py.readthedocs.org/en/latest/index.html?highlight=set#redis.StrictRedis.set，他的set只有两个参数。

刚看了下django-redis文档，他的参数是多个的。在django下使用是正常的。建议以redis-py框架作为标准设计redisstorage.py，或者加个判断当前环境是django还是其他web框架。

**Comment by hunter007** [comment]
你用的 redis-py 是
andymccurdy https://github.com/andymccurdy/redis-py https://github.com/andymccurdy/redis-py
的早期分支，请使用https://github.com/andymccurdy/redis-py https://github.com/andymccurdy/redis-py，此项目还在更新。

**Comment by openpython** [comment]
@hunter007 发的链接地址一样，敲错了？

**Comment by hunter007** [comment]
你可以确认一下你的环境中是不是正确地 redis-py.  从你之前发的邮件中的文档看，那是另一个 不更新的fork。

**Comment by openpython** [comment]
redis-py没错，找到问题了原因了，https://github.com/andymccurdy/redis-py/issues/493
这个命令只有在 Redis server 2.6.12 以后才支持的，我的环境默认安装的是Redis server version 2.2.12
